import { lazy } from 'react'

// 4-sinf NAZARIY darslari. Barcha yangi komponentlar faqat components/grade4/ ichida yaratiladi.
export const grade4Nazariy = [
  {
    slug: 'dars01-kop-xonali-sonlar-sinflari',
    title: "Dars 1. Ko'p xonali sonlar sinflari",
    desc: "Ko'p xonali sonni o'ngdan uch raqamli sinflarga ajratish, raqamning o'rin qiymatini aniqlash va ichki nol qatnashgan sonlarni tuzish.",
    Component: lazy(() => import('../components/grade4/Dars01.jsx')),
  },
  {
    slug: 'dars02-kop-xonali-sonlarni-oqish-va-yozish',
    title: "Dars 2. Ko'p xonali sonlarni o'qish va yozish",
    desc: "Ko'p xonali sonlarni sinflar bo'yicha o'qish, ovozli shakldan raqamli yozuvga o'tish, ichki nollarni saqlash va qayta o'qib tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars02.jsx')),
  },
  {
    slug: 'dars03-kop-xonali-sonning-xona-tarkibi',
    title: "Dars 3. Ko'p xonali sonning xona tarkibi",
    desc: "Raqam, xona va xona qiymatini farqlash, sonni xona qo'shiluvchilariga yoyish hamda yoyiq yozuvdan sonni tiklash.",
    Component: lazy(() => import('../components/grade4/Dars03.jsx')),
  },
  {
    slug: 'dars04-kop-xonali-sonlarni-taqqoslash',
    title: "Dars 4. Ko'p xonali sonlarni taqqoslash",
    desc: "Avval raqamlar sonini, keyin chapdagi birinchi farqli xonani taqqoslash, belgini to'g'ri qo'yish va sonlarni tartiblash.",
    Component: lazy(() => import('../components/grade4/Dars04.jsx')),
  },
  {
    slug: 'dars05-kop-xonali-sonlarni-yaxlitlash',
    title: "Dars 5. Ko'p xonali sonlarni yaxlitlash",
    desc: "Ko'p xonali sonlarni o'nlik, yuzlik va minglikkacha yaxlitlash hamda vaziyatga mos aniqlikni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars05.jsx')),
  },
  {
    slug: 'dars06-sonlarning-xonalari-va-sinflari',
    title: "Dars 6. Sonlarning xonalari va sinflari",
    desc: "Sinf va xona, o'qish-yozish, yoyiq tarkib, taqqoslash hamda yaxlitlashni bitta murakkab ma'lumot paketida birlashtirish.",
    Component: lazy(() => import('../components/grade4/Dars06.jsx')),
  },
  {
    slug: 'dars07-pozitsion-va-nopozitsion-sanoq-sistemalari',
    title: 'Dars 7. Pozitsion va nopozitsion sanoq sistemalari',
    desc: "Avval raqam pozitsiyasi va o'nlik pozitsion yozuvni, keyin Rim nopozitsion yozuvini o'rganish hamda ularning farqini dalil bilan tushuntirish.",
    Component: lazy(() => import('../components/grade4/Dars07.jsx')),
  },
  {
    slug: 'dars08-kop-xonali-sonlarni-qoshish-va-ayirish',
    title: "Dars 8. Ko'p xonali sonlarni qo'shish va ayirish",
    desc: "Ko'p xonali sonlarni xona ostiga xona qilib yozish, ko'chirish va almashtirish bilan hisoblash hamda natijani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars08.jsx')),
  },
  {
    slug: 'dars09-kop-xonali-sonni-bir-xonali-songa-kopaytirish',
    title: "Dars 9. Ko'p xonali sonni bir xonali songa ko'paytirish",
    desc: "Ko'p xonali sonni bir xonali songa yoyiq va ustun modellar orqali ko'paytirish, ko'chirish va nol qatnashgan xonalarni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars09.jsx')),
  },
  {
    slug: 'dars10-kop-xonali-sonni-ikki-xonali-songa-kopaytirish',
    title: "Dars 10. Ko'p xonali sonni ikki xonali songa ko'paytirish",
    desc: "Ikki to'liqsiz ko'paytmani tuzish, o'nliklar qatorini bir xona siljitish va natijani taxmin bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars10.jsx')),
  },
  {
    slug: 'dars11-kop-xonali-sonni-uch-xonali-songa-kopaytirish',
    title: "Dars 11. Ko'p xonali sonni uch xonali songa ko'paytirish",
    desc: "Birlik, o'nlik va yuzlik to'liqsiz ko'paytmalarini tegishli xonadan boshlab yozish, nol o'rnini saqlash va qatorlarni qo'shish.",
    Component: lazy(() => import('../components/grade4/Dars11.jsx')),
  },
  {
    slug: 'dars12-kop-xonali-sonni-bir-xonali-songa-bolish',
    title: "Dars 12. Ko'p xonali sonni bir xonali songa bo'lish",
    desc: "Birinchi to'liqsiz bo'linuvchini topish, bo'linmadagi raqamlar sonini oldindan aniqlash, qadam siklini bajarish va bo'linmadagi nolni saqlash.",
    Component: lazy(() => import('../components/grade4/Dars12.jsx')),
  },
  {
    slug: 'dars13-kop-xonali-sonni-ikki-xonali-songa-bolish',
    title: "Dars 13. Ko'p xonali sonni ikki xonali songa bo'lish",
    desc: "Bo'luvchini yaxlitlab sinash raqamini topish, uni ko'paytirish bilan tekshirish va katta chiqsa bittaga kamaytirish.",
    Component: lazy(() => import('../components/grade4/Dars13.jsx')),
  },
  {
    slug: 'dars14-harakat-masalalari',
    title: 'Dars 14. Harakatga doir masalalar',
    desc: "Tezlik, vaqt va masofani jadvalda bog'lash, uchta qoidani ajratish va javob birligini to'g'ri yozish.",
    Component: lazy(() => import('../components/grade4/Dars14.jsx')),
  },
  {
    slug: 'dars15-ortacha-arifmetik',
    title: "Dars 15. O'rtacha arifmetik",
    desc: "Qiymatlar yig'indisini teng taqsimlash orqali o'rtacha arifmetikni topish va natijalarni adolatli taqqoslash.",
    Component: lazy(() => import('../components/grade4/Dars15.jsx')),
  },
  {
    slug: 'dars16-formulalar',
    title: 'Dars 16. Formulalar',
    desc: "Konkret shakl va katakli modeldan perimetr hamda yuza formulalariga o'tish, qiymat qo'yish va ikki kattalikni farqlash.",
    Component: lazy(() => import('../components/grade4/Dars16.jsx')),
  },
  {
    slug: 'dars17-shkalalar',
    title: 'Dars 17. Shkalalar',
    desc: "Sonlar nuri va birlik kesma, bir bo'linma qiymatini farq orqali topish hamda chizg'ich, termometr, soat va spidometrni bir qoida bilan o'qish.",
    Component: lazy(() => import('../components/grade4/Dars17.jsx')),
  },
  {
    slug: 'dars18-kasr-tushunchasi',
    title: 'Dars 18. Kasr tushunchasi',
    desc: "Butunni teng qismlarga ajratish, surat va maxraj ma'nosini model, yozuv hamda sonlar nurida bog'lash.",
    Component: lazy(() => import('../components/grade4/Dars18.jsx')),
  },
  {
    slug: 'dars19-kasrlarni-taqqoslash',
    title: 'Dars 19. Kasrlarni taqqoslash',
    desc: "Kasrlarni teng maxraj, teng surat va yarim bilan taqqoslash strategiyalaridan mosini tanlab solishtirish.",
    Component: lazy(() => import('../components/grade4/Dars19.jsx')),
  },
  {
    slug: 'dars20-kasrlarni-qoshish',
    title: "Dars 20. Kasrlarni qo'shish",
    desc: "Bir xil maxrajli kasrlarni model va sonlar nurida qo'shish, suratlarni qo'shib maxrajni o'zgartirmaslik.",
    Component: lazy(() => import('../components/grade4/Dars20.jsx')),
  },
  {
    slug: 'dars21-kasrlarni-ayirish',
    title: 'Dars 21. Kasrlarni ayirish',
    desc: "Bir xil maxrajli kasrlarni olib tashlash va farq modeli bilan ayirish, natijani qo'shish orqali tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars21.jsx')),
  },
  {
    slug: 'dars22-sonning-kasr-qismini-topish',
    title: 'Dars 22. Sonning kasr qismini topish',
    desc: "Butunni teng ulushlarga ajratib, avval bitta ulushni, so'ng kasr suratiga mos qismini topish va natijani model bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars22.jsx')),
  },
  {
    slug: 'dars23-kasrli-masalalar',
    title: 'Dars 23. Kasrli masalalar: qism va butun',
    desc: "Kasrli masalalarda ma'lum va noma'lum miqdorni ajratish, butundan qismni topish yoki ma'lum qismdan butunni tiklash hamda javobni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars23.jsx')),
  },
  {
    slug: 'dars24-onli-kasrlar',
    title: "Dars 24. O'nli kasrlar",
    desc: "Maxraji 10, 100 va 1 000 bo'lgan kasrlarni o'nli yozuv bilan bog'lash, butun va kasr qismini o'qish hamda xona jadvalida ko'rsatish.",
    Component: lazy(() => import('../components/grade4/Dars24.jsx')),
  },
  {
    slug: 'dars25-toplamlar-eyler-venn-diagrammasi',
    title: "Dars 25. To'plamlar va Eyler–Venn diagrammasi",
    desc: "To'plamni umumiy belgi bilan hosil qilish, elementlarni sanash, halqa ichi va tashqarisini ajratish, juft va toq sonlarni ajratilgan halqalarda ko'rsatish hamda ikki belgi bo'yicha to'rt zonaga joylashtirish.",
    Component: lazy(() => import('../components/grade4/Dars25.jsx')),
  },
  {
    slug: 'dars26-uzunlik-birliklari',
    title: 'Dars 26. Uzunlik birliklari',
    desc: "mm, cm, dm, m va km orasidagi munosabatlarni modelda bog'lash, mos birlikni tanlash va tarkibli uzunlikni bitta birlikda yozish.",
    Component: lazy(() => import('../components/grade4/Dars26.jsx')),
  },
  {
    slug: 'dars27-massa-birliklari',
    title: 'Dars 27. Massa birliklari',
    desc: "g, kg, sentner va t orasidagi munosabatlarni tarozi modelida bog'lash, mos birlikni tanlash va tarkibli massani bitta birlikda yozish.",
    Component: lazy(() => import('../components/grade4/Dars27.jsx')),
  },
  {
    slug: 'dars28-vaqt-birliklari',
    title: 'Dars 28. Vaqt birliklari',
    desc: "Soniya, minut, soat, sutka, hafta, oy, yil va asr orasidagi noo'nlik munosabatlarni tushunish, vaqtni aylantirish va davomiylikni topish.",
    Component: lazy(() => import('../components/grade4/Dars28.jsx')),
  },
  {
    slug: 'dars29-yuza-birliklari',
    title: 'Dars 29. Yuza birliklari',
    desc: "mm², cm², dm², m² va km²ni birlik kvadrat sifatida qurish, yuza birliklari orasidagi munosabatlarni aniqlash va mos birlikni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars29.jsx')),
  },
  {
    slug: 'dars30-kattalik-birliklarini-aylantirish',
    title: 'Dars 30. Kattalik birliklarini aylantirish',
    desc: "Uzunlik, massa, vaqt va yuza birliklarini o'z munosabatlari asosida aylantirish, aralash birliklarni birlashtirish va natijani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars30.jsx')),
  },
  {
    slug: 'dars31-kattaliklarga-doir-masalalar',
    title: 'Dars 31. Kattaliklarga doir masalalar',
    desc: "Aralash birlikli masalada ma'lum va noma'lum kattaliklarni ajratish, birliklarni tenglashtirish, amalni tanlash va javobni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars31.jsx')),
  },
  {
    slug: 'dars32-hajm-birliklari',
    title: 'Dars 32. Hajm birliklari',
    desc: "Hajmni birlik kublar orqali tushunish, cm³, dm³, m³ va litr orasidagi munosabatlarni qo'llash.",
    Component: lazy(() => import('../components/grade4/Dars32.jsx')),
  },
  {
    slug: 'dars33-burchak-turlari',
    title: 'Dars 33. Burchak turlari',
    desc: "Burchaklarni ochilishiga ko'ra o'tkir, to'g'ri, o'tmas va yoyiq turlarga ajratish.",
    Component: lazy(() => import('../components/grade4/Dars33.jsx')),
  },
  {
    slug: 'dars34-burchaklarni-yasash',
    title: 'Dars 34. Burchaklarni yasash',
    desc: "Transportir markazi, asos chizig'i va to'g'ri shkaladan foydalanib berilgan gradusli burchakni yasash va tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars34.jsx')),
  },
  {
    slug: 'dars35-uchburchak-turlari',
    title: 'Dars 35. Uchburchak turlari',
    desc: "Uchburchaklarni tomonlari va burchaklariga ko'ra mustaqil tasniflash hamda bir figuraga ikki xil nom berish.",
    Component: lazy(() => import('../components/grade4/Dars35.jsx')),
  },
  {
    slug: 'dars36-togri-tortburchak-va-kvadrat',
    title: "Dars 36. To'g'ri to'rtburchak va kvadrat",
    desc: "To'g'ri to'rtburchak va kvadrat xossalarini solishtirish, kvadratni maxsus to'g'ri to'rtburchak sifatida tushunish.",
    Component: lazy(() => import('../components/grade4/Dars36.jsx')),
  },
  {
    slug: 'dars37-perimetr-va-yuza',
    title: 'Dars 37. Figuralarning perimetri va yuzi',
    desc: "Chegara uzunligi bilan egallangan sirtni farqlash, to'g'ri to'rtburchak va kvadrat perimetri hamda yuzini hisoblash.",
    Component: lazy(() => import('../components/grade4/Dars37.jsx')),
  },
  {
    slug: 'dars38-geometrik-yasashlar',
    title: 'Dars 38. Geometrik yasashlar',
    desc: "Chizg'ich, go'niya va transportir bilan kesma, perpendikulyar, parallel chiziq va burchak yasash.",
    Component: lazy(() => import('../components/grade4/Dars38.jsx')),
  },
  {
    slug: 'dars39-nuqta-koordinatalari',
    title: 'Dars 39. Nuqta koordinatalari va koordinata burchagi',
    desc: "Birinchi chorakda koordinata boshi, x va y o'qlarini o'qish, nuqtani avval x, keyin y bo'yicha joylashtirish.",
    Component: lazy(() => import('../components/grade4/Dars39.jsx')),
  },
  {
    slug: 'dars40-fazoviy-shakllar-va-yoyilmalar',
    title: 'Dars 40. Fazoviy shakllar va yoyilmalar',
    desc: "Kub va to'g'ri burchakli parallelepipedning yoq, qirra va uchlarini ajratish, yaroqli yoyilmani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars40.jsx')),
  },
  {
    slug: 'dars41-simmetriya-va-burilish-simmetriyasi',
    title: 'Dars 41. Simmetriya va burilish simmetriyasi',
    desc: "Simmetriya o'qi, mos nuqtalar, aylanish markazi va eng kichik mos tushish burchagini aniqlash.",
    Component: lazy(() => import('../components/grade4/Dars41.jsx')),
  },
  {
    slug: 'dars42-tenglamalar',
    title: 'Dars 42. Tenglamalar',
    desc: "Tenglik, noma'lum va tenglama ildizini tushunish, noma'lum komponent uchun teskari amalni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars42.jsx')),
  },
  {
    slug: 'dars43-tenglamalarni-yechish-va-tekshirish',
    title: 'Dars 43. Tenglamalarni yechish va tekshirish',
    desc: "Tenglama ildizini topish, boshlang'ich tenglamaga qo'yish va ikki tomon tengligini tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars43.jsx')),
  },
  {
    slug: 'dars44-murakkab-masalalar',
    title: 'Dars 44. Murakkab masalalar',
    desc: "Yashirin oraliq savolni topish, bog'langan amallar tartibini modelda asoslash va yakuniy javobni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars44.jsx')),
  },
  {
    slug: 'dars45-harakatga-doir-masalalar',
    title: 'Dars 45. Harakatga doir masalalar',
    desc: "Ikki obyektning yaqinlashish, uzoqlashish va quvib yetish harakatida yig'indi yoki ayirma tezlikni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars45.jsx')),
  },
  {
    slug: 'dars46-qism-va-butunni-topish',
    title: 'Dars 46. Qism va butunni topishga doir masalalar',
    desc: "Kasr orqali bitta ulushni, kerakli qismni, noma'lum butunni va qolgan miqdorni ketma-ket topish.",
    Component: lazy(() => import('../components/grade4/Dars46.jsx')),
  },
  {
    slug: 'dars47-tengsizliklarni-tanlash-usuli',
    title: 'Dars 47. Tengsizliklarni tanlash usulida yechish',
    desc: "Berilgan chekli sohada qiymatlarni tartib bilan tekshirish, chegarani aniqlash va barcha yechimlarni yozish.",
    Component: lazy(() => import('../components/grade4/Dars47.jsx')),
  },
  {
    slug: 'dars48-qoshish-xossalari',
    title: "Dars 48. Qo'shishning o'rin almashtirish va guruhlash xossalari",
    desc: "Qo'shiluvchilarni natijani o'zgartirmay almashtirish va guruhlash, qulay juftlar orqali tez hisoblash.",
    Component: lazy(() => import('../components/grade4/Dars48.jsx')),
  },
  {
    slug: 'dars49-mulohazalar-va-hukmlar',
    title: 'Dars 49. Mulohazalar va hukmlar',
    desc: "Matematik mulohazani savol va buyruqdan ajratish, rostlikni hisob, model yoki qarshi misol bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars49.jsx')),
  },
  {
    slug: 'dars50-grafiklar-va-malumotlar',
    title: "Dars 50. Grafiklar va ma'lumotlarni tasvirlash usullari",
    desc: "Jadval, ustunli diagramma va chiziqli grafikni o'qish, masshtabni hisobga olish va ma'lumotdan xulosa chiqarish.",
    Component: lazy(() => import('../components/grade4/Dars50.jsx')),
  },
  {
    slug: 'dars51-yakuniy-takrorlash',
    title: "Dars 51. O'rganilgan mavzularni yakuniy takrorlash",
    desc: "Vaziyatni tushunish, mos modelni tanlash, hisoblash, tekshirish va izohlashni kurs mavzulari bo'ylab bog'lash.",
    Component: lazy(() => import('../components/grade4/Dars51.jsx')),
  },
]

// 4-sinf AMALIY mashg'ulotlari. Har nazariy darsga 10 tekshiriladigan topshiriq
// (ETALON_4SINF §9). Amaliyot ovozsiz ishlaydi.
export const grade4Amaliy = [
  {
    slug: 'dars01-amaliyot-sinflar',
    title: "Dars 1. Amaliyot: sonlar sinflari",
    desc: "10 topshiriq: sinf chegarasi, xona qiymati, ichki nollar, xatoni topish va yangi shaklga ko'chirish.",
    Component: lazy(() => import('../components/grade4/Dars01Practice.jsx')),
  },
  {
    slug: 'dars02-amaliyot-oqish-yozish',
    title: "Dars 2. Amaliyot: sonlarni o'qish va yozish",
    desc: "10 topshiriq: sinflar bo'yicha o'qish, ovozli shakldan yozuvga o'tish, ichki nollar va qayta o'qib tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars02Practice.jsx')),
  },
  {
    slug: 'dars03-amaliyot-xona-tarkibi',
    title: "Dars 3. Amaliyot: sonning xona tarkibi",
    desc: "10 topshiriq: raqamning xona qiymati, yoyiq yozuv, sonni tiklash, ichki nollar va xatoni tahlil qilish.",
    Component: lazy(() => import('../components/grade4/Dars03Practice.jsx')),
  },
  {
    slug: 'dars04-amaliyot-taqqoslash',
    title: "Dars 4. Amaliyot: sonlarni taqqoslash",
    desc: "10 topshiriq: raqamlar soni, birinchi farqli xona, belgilar, tartiblash va noto'g'ri strategiyani tuzatish.",
    Component: lazy(() => import('../components/grade4/Dars04Practice.jsx')),
  },
  {
    slug: 'dars05-amaliyot-yaxlitlash',
    title: "Dars 5. Amaliyot: sonlarni yaxlitlash",
    desc: "10 topshiriq: o'nlik, yuzlik, minglik va o'n minglikkacha yaxlitlash, chegaraviy holat va aniqlik tanlash.",
    Component: lazy(() => import('../components/grade4/Dars05Practice.jsx')),
  },
  {
    slug: 'dars06-amaliyot-xonalar-sinflar',
    title: "Dars 6. Amaliyot: sonlarning xonalari va sinflari",
    desc: "10 topshiriq: o'qish, yoyish, xona qiymati, taqqoslash va yaxlitlashni bir paketda birlashtirish.",
    Component: lazy(() => import('../components/grade4/Dars06Practice.jsx')),
  },
  {
    slug: 'dars07-amaliyot-sanoq-sistemalari',
    title: 'Dars 7. Amaliyot: pozitsion va nopozitsion sanoq sistemalari',
    desc: "10 topshiriq: Rim yozuvi 1 dan 20 gacha, xona qiymati, ikki sanoq sistemasini farqlash, xatoni tahlil qilish va transfer.",
    Component: lazy(() => import('../components/grade4/Dars07Practice.jsx')),
  },
  {
    slug: 'dars08-amaliyot-qoshish-ayirish',
    title: "Dars 8. Amaliyot: ko'p xonali sonlarni qo'shish va ayirish",
    desc: "10 topshiriq: xonalarni tekislash, ko'chirish, nollar orqali maydalash, teskari amal va natijani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars08Practice.jsx')),
  },
  {
    slug: 'dars09-amaliyot-bir-xonali-kopaytirish',
    title: "Dars 9. Amaliyot: bir xonali songa ko'paytirish",
    desc: "10 topshiriq: teng guruhlar, ustun yozuvi, xona bo'yicha ko'paytirish, ichki nol, taxmin va qulay strategiya.",
    Component: lazy(() => import('../components/grade4/Dars09Practice.jsx')),
  },
  {
    slug: 'dars10-amaliyot-ikki-xonali-kopaytirish',
    title: "Dars 10. Amaliyot: ikki xonali songa ko'paytirish",
    desc: "10 topshiriq: ikki to'liqsiz ko'paytma, o'nliklar qatorini siljitish, nol holati, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars10Practice.jsx')),
  },
  {
    slug: 'dars11-amaliyot-uch-xonali-kopaytirish',
    title: "Dars 11. Amaliyot: uch xonali songa ko'paytirish",
    desc: "10 topshiriq: uchta to'liqsiz ko'paytma, 0–1–2 xona siljishi, o'rtadagi nol, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars11Practice.jsx')),
  },
  {
    slug: 'dars12-amaliyot-bir-xonali-bolish',
    title: "Dars 12. Amaliyot: bir xonali songa bo'lish",
    desc: "10 topshiriq: birinchi to'liqsiz bo'linuvchi, yozma bo'lish sikli, ichki nol, qoldiq, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars12Practice.jsx')),
  },
  {
    slug: 'dars13-amaliyot-ikki-xonali-bolish',
    title: "Dars 13. Amaliyot: ikki xonali songa bo'lish",
    desc: "10 topshiriq: sinov raqami, yaqin ko'paytma, to'liqsiz bo'linuvchi, qoldiq, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars13Practice.jsx')),
  },
  {
    slug: 'dars14-amaliyot-harakat-masalalari',
    title: 'Dars 14. Amaliyot: harakat masalalari',
    desc: "10 topshiriq: masofa, tezlik va vaqt bog'lanishi, amal tanlash, birliklar, xato tahlili va ikki qismli transfer.",
    Component: lazy(() => import('../components/grade4/Dars14Practice.jsx')),
  },
  {
    slug: 'dars15-amaliyot-ortacha-arifmetik',
    title: "Dars 15. Amaliyot: o'rtacha arifmetik",
    desc: "10 topshiriq: yig'indi va qiymatlar soni, tenglashtirish, son chizig'i, chegara holati, xato tahlili va taqqoslash.",
    Component: lazy(() => import('../components/grade4/Dars15Practice.jsx')),
  },
  {
    slug: 'dars16-amaliyot-formulalar',
    title: 'Dars 16. Amaliyot: formulalar',
    desc: "10 topshiriq: perimetr va yuza formulalari, qiymat qo'yish, birliklar, chegara holati, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars16Practice.jsx')),
  },
  {
    slug: 'dars17-amaliyot-shkalalar',
    title: 'Dars 17. Amaliyot: shkalalar',
    desc: "10 topshiriq: bo'linma qiymati, ko'rsatkichni o'qish, belgilar va bo'linmalarni farqlash hamda vertikal shkalaga transfer.",
    Component: lazy(() => import('../components/grade4/Dars17Practice.jsx')),
  },
  {
    slug: 'dars18-amaliyot-kasr-tushunchasi',
    title: 'Dars 18. Amaliyot: kasr tushunchasi',
    desc: "10 topshiriq: teng qismlar, surat va maxraj, kasr modeli, kasrni qurish hamda son nuridan modelga o'tish.",
    Component: lazy(() => import('../components/grade4/Dars18Practice.jsx')),
  },
  {
    slug: 'dars19-amaliyot-kasrlarni-taqqoslash',
    title: 'Dars 19. Amaliyot: kasrlarni taqqoslash',
    desc: "10 topshiriq: teng maxraj, teng surat, yarim mo'ljali, tartiblash, xato tahlili va strategiyani tanlash.",
    Component: lazy(() => import('../components/grade4/Dars19Practice.jsx')),
  },
  {
    slug: 'dars20-amaliyot-kasrlarni-qoshish',
    title: "Dars 20. Amaliyot: kasrlarni qo'shish",
    desc: "10 topshiriq: teng maxrajli kasrlarni qo'shish, maxrajni saqlash, noma'lum qo'shiluvchi va bir butun natija.",
    Component: lazy(() => import('../components/grade4/Dars20Practice.jsx')),
  },
  {
    slug: 'dars21-amaliyot-kasrlarni-ayirish',
    title: 'Dars 21. Amaliyot: kasrlarni ayirish',
    desc: "10 topshiriq: teng maxrajli kasrlarni ayirish, qoldiq, noma'lum ayiriluvchi, nol natija va qo'shish bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars21Practice.jsx')),
  },
  {
    slug: 'dars22-amaliyot-sonning-kasr-qismini-topish',
    title: 'Dars 22. Amaliyot: sonning kasr qismini topish',
    desc: "10 topshiriq: teng ulushni topish, maxrajga bo'lish, suratga ko'paytirish, butun kasr va xatoni tahlil qilish.",
    Component: lazy(() => import('../components/grade4/Dars22Practice.jsx')),
  },
  {
    slug: 'dars23-amaliyot-kasrli-masalalar',
    title: 'Dars 23. Amaliyot: kasrli masalalar',
    desc: "10 topshiriq: butundan qismni, ma'lum qismdan butunni topish, masala yo'nalishini ajratish va qoldiq orqali transfer.",
    Component: lazy(() => import('../components/grade4/Dars23Practice.jsx')),
  },
  {
    slug: 'dars24-amaliyot-onli-kasrlar',
    title: "Dars 24. Amaliyot: o'nli kasrlar",
    desc: "10 topshiriq: o'ndan, yuzdan va mingdan birlar, xona jadvali, nol o'rintutgichi va o'nli yozuv strategiyasi.",
    Component: lazy(() => import('../components/grade4/Dars24Practice.jsx')),
  },
  {
    slug: 'dars25-amaliyot-toplamlar-eyler-venn-diagrammasi',
    title: "Dars 25. Amaliyot: to'plamlar va Eyler–Venn diagrammasi",
    desc: "10 topshiriq: ikki belgi bo'yicha faqat A, ikkala, faqat B va tashqaridagi elementlarni tasniflash hamda sanash.",
    Component: lazy(() => import('../components/grade4/Dars25Practice.jsx')),
  },
  {
    slug: 'dars26-amaliyot-uzunlik-birliklari',
    title: 'Dars 26. Amaliyot: uzunlik birliklari',
    desc: "10 topshiriq: mm, cm, dm, m va km orasida aylantirish, aralash birliklar, qoldiq va masala strategiyasi.",
    Component: lazy(() => import('../components/grade4/Dars26Practice.jsx')),
  },
  {
    slug: 'dars27-amaliyot-massa-birliklari',
    title: 'Dars 27. Amaliyot: massa birliklari',
    desc: "10 topshiriq: g, kg, sentner va tonna orasida aylantirish, aralash birliklar, tartiblash va xato tahlili.",
    Component: lazy(() => import('../components/grade4/Dars27Practice.jsx')),
  },
  {
    slug: 'dars28-amaliyot-vaqt-birliklari',
    title: 'Dars 28. Amaliyot: vaqt birliklari',
    desc: "10 topshiriq: sekunddan yilgacha vaqt birliklari, aralash vaqt, normallashtirish, kalendar chegarasi va davomiylik.",
    Component: lazy(() => import('../components/grade4/Dars28Practice.jsx')),
  },
  {
    slug: 'dars29-amaliyot-yuza-birliklari',
    title: 'Dars 29. Amaliyot: yuza birliklari',
    desc: "10 topshiriq: kvadrat birliklar, koeffitsiyentning kvadrati, mos birlik, yuza masalasi va xato tahlili.",
    Component: lazy(() => import('../components/grade4/Dars29Practice.jsx')),
  },
  {
    slug: 'dars30-amaliyot-kattalik-birliklarini-aylantirish',
    title: 'Dars 30. Amaliyot: kattalik birliklarini aylantirish',
    desc: "10 topshiriq: uzunlik, massa, vaqt va yuza birliklari uchun oilaga xos koeffitsiyent va natijani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars30Practice.jsx')),
  },
  {
    slug: 'dars31-amaliyot-kattaliklarga-doir-masalalar',
    title: 'Dars 31. Amaliyot: kattaliklarga doir masalalar',
    desc: "10 topshiriq: tugallangan yozuv, uch qadam va tekshiruv, qarz olish, noma'lum qo'shiluvchi, nol qism va xato tahlili.",
    Component: lazy(() => import('../components/grade4/Dars31Practice.jsx')),
  },
  {
    slug: 'dars32-amaliyot-hajm-birliklari',
    title: 'Dars 32. Amaliyot: hajm birliklari',
    desc: "10 topshiriq: birlik kublar, qatlam usuli, ming qadami, litr va kub detsimetr, nol yo'qolishi va teskari o'tish.",
    Component: lazy(() => import('../components/grade4/Dars32Practice.jsx')),
  },
  {
    slug: 'dars33-amaliyot-burchak-turlari',
    title: 'Dars 33. Amaliyot: burchak turlari',
    desc: "10 topshiriq: ochilish va tomon uzunligi, 90° bilan solishtirish, shkalani o'qish, chegaraviy 89-90-91 va soat millari.",
    Component: lazy(() => import('../components/grade4/Dars33Practice.jsx')),
  },
  {
    slug: 'dars34-amaliyot-burchaklarni-yasash',
    title: 'Dars 34. Amaliyot: burchaklarni yasash',
    desc: "10 topshiriq: transportir markazi, asos chizig'i, ikki shkala, yasash tartibi, turi bo'yicha tekshirish va xato joyi.",
    Component: lazy(() => import('../components/grade4/Dars34Practice.jsx')),
  },
  {
    slug: 'dars35-amaliyot-uchburchak-turlari',
    title: 'Dars 35. Amaliyot: uchburchak turlari',
    desc: "10 topshiriq: ikkita nom, eng katta burchak, teng tomonlar soni, ikki qatorli blanka, imkonsiz uchburchak va tavsifdan nom.",
    Component: lazy(() => import('../components/grade4/Dars35Practice.jsx')),
  },
  {
    slug: 'dars36-amaliyot-togri-tortburchak-va-kvadrat',
    title: "Dars 36. Amaliyot: to'g'ri to'rtburchak va kvadrat",
    desc: "10 topshiriq: ortiqcha xossa, tekshiruv tartibi, ichma-ich to'plamlar, romb tuzog'i, saralash xatosi va tavsifdan nom.",
    Component: lazy(() => import('../components/grade4/Dars36Practice.jsx')),
  },
  {
    slug: 'dars37-amaliyot-perimetr-va-yuza',
    title: 'Dars 37. Amaliyot: perimetr va yuza',
    desc: "10 topshiriq: chegara va sirt, teng perimetr tuzog'i, katak bilan o'lchash, noma'lum tomon, birlik tekshiruvi va perimetrdan yuzaga.",
    Component: lazy(() => import('../components/grade4/Dars37Practice.jsx')),
  },
  {
    slug: 'dars38-amaliyot-geometrik-yasashlar',
    title: 'Dars 38. Amaliyot: geometrik yasashlar',
    desc: "10 topshiriq: asbob va savol, moslash qadami, qo'shni burchaklar yozuvi, perpendikulyar bayonnomasi, ko'zga qarab chizish tuzog'i va xatoni tuzatish.",
    Component: lazy(() => import('../components/grade4/Dars38Practice.jsx')),
  },
  {
    slug: 'dars39-amaliyot-nuqta-koordinatalari',
    title: 'Dars 39. Amaliyot: nuqta koordinatalari',
    desc: "10 topshiriq: yozuv tartibi, nuqtani to'rda topish, o'qlardagi nol, koordinata boshi, almashtirish xatosi va ikki obyektni farqlash.",
    Component: lazy(() => import('../components/grade4/Dars39Practice.jsx')),
  },
  {
    slug: 'dars40-amaliyot-fazoviy-shakllar-va-yoyilmalar',
    title: 'Dars 40. Amaliyot: fazoviy shakllar va yoyilmalar',
    desc: "10 topshiriq: yoq, qirra va uch, ko'rinmagan qismlarni sanash, yoyilmadagi kvadratlar, buklash tartibi, kub va quti farqi.",
    Component: lazy(() => import('../components/grade4/Dars40Practice.jsx')),
  },
  {
    slug: 'dars41-amaliyot-simmetriya-va-burilish-simmetriyasi',
    title: 'Dars 41. Amaliyot: simmetriya va burilish simmetriyasi',
    desc: "10 topshiriq: simmetriya o'qini topish, ko'zguni katakda qurish, o'q ustidagi elementlar, burish burchagi va koshinlarni saralash.",
    Component: lazy(() => import('../components/grade4/Dars41Practice.jsx')),
  },
  {
    slug: 'dars42-amaliyot-tenglamalar',
    title: 'Dars 42. Amaliyot: tenglamalar',
    desc: "10 topshiriq: noma'lumning o'rnini aniqlash, butun-qism lentasi, matndan tenglama tuzish, nol chegarasi va teskari amal xatosi.",
    Component: lazy(() => import('../components/grade4/Dars42Practice.jsx')),
  },
  {
    slug: 'dars43-amaliyot-tenglamalarni-yechish-va-tekshirish',
    title: 'Dars 43. Amaliyot: tenglamalarni yechish va tekshirish',
    desc: "10 topshiriq: teskari amalni tanlash, noma'lum ko'paytuvchi va bo'linuvchi, murakkab tenglama, qo'yib tekshirish va tekshiruv hukmi.",
    Component: lazy(() => import('../components/grade4/Dars43Practice.jsx')),
  },
  {
    slug: 'dars44-amaliyot-murakkab-masalalar',
    title: 'Dars 44. Amaliyot: murakkab masalalar',
    desc: "10 topshiriq: oraliq savolni ajratish, reja tuzish, ikki yo'l bilan yechish, amallar sonini aniqlash va oraliq qiymat xatosi.",
    Component: lazy(() => import('../components/grade4/Dars44Practice.jsx')),
  },
  {
    slug: 'dars45-amaliyot-harakatga-doir-masalalar',
    title: 'Dars 45. Amaliyot: harakatga doir masalalar',
    desc: "10 topshiriq: tezlik, masofa va vaqt bog'lanishi, masofa shkalasi, noldan boshlanmagan shkala, birlik va amal xatolari.",
    Component: lazy(() => import('../components/grade4/Dars45Practice.jsx')),
  },
  {
    slug: 'dars46-amaliyot-qism-va-butunni-topish',
    title: 'Dars 46. Amaliyot: qism va butunni topish',
    desc: "10 topshiriq: bitta ulush, butundan qism, qismdan butun, kasr quruvchi, butun kasr chegarasi va qoldiq.",
    Component: lazy(() => import('../components/grade4/Dars46Practice.jsx')),
  },
  {
    slug: 'dars47-amaliyot-tengsizliklarni-tanlash-usuli',
    title: 'Dars 47. Amaliyot: tengsizliklarni tanlash usulida yechish',
    desc: "10 topshiriq: belgilar ma'nosi, eng katta yechim, son o'qidagi chegara, yechimlar soni va qat'iy belgi xatosi.",
    Component: lazy(() => import('../components/grade4/Dars47Practice.jsx')),
  },
  {
    slug: 'dars48-amaliyot-qoshish-xossalari',
    title: "Dars 48. Amaliyot: qo'shishning xossalari",
    desc: "10 topshiriq: o'rin almashtirish va guruhlash, qulay juft, xossalarni farqlash, ayirish chegarasi va xato yozuvlar.",
    Component: lazy(() => import('../components/grade4/Dars48Practice.jsx')),
  },
  {
    slug: 'dars49-amaliyot-mulohazalar-va-hukmlar',
    title: 'Dars 49. Amaliyot: mulohazalar va hukmlar',
    desc: "10 topshiriq: mulohazani savol va buyruqdan ajratish, hisob bilan tekshirish, ichki inkor, teskari mulohaza va qarshi misol.",
    Component: lazy(() => import('../components/grade4/Dars49Practice.jsx')),
  },
  {
    slug: 'dars50-amaliyot-grafiklar-va-malumotlar',
    title: "Dars 50. Amaliyot: grafiklar va ma'lumotlar",
    desc: "10 topshiriq: o'qlarni o'qish, shkala, diagrammadan jadvalga o'tish, noldan boshlanmagan o'q va grafik bo'yicha xulosa.",
    Component: lazy(() => import('../components/grade4/Dars50Practice.jsx')),
  },
  {
    slug: 'dars51-amaliyot-yakuniy-takrorlash',
    title: 'Dars 51. Amaliyot: yakuniy takrorlash',
    desc: "10 topshiriq: son o'qi, yuza kataklari, xonalar sinfi, ustun qo'shish, kasr qismi, birlik aylantirish va perimetr bilan yuzani ajratish.",
    Component: lazy(() => import('../components/grade4/Dars51Practice.jsx')),
  },
]
