import { lazy } from 'react'

// 1-sinf NAZARIY darslari (Dars01–36). Yangi dars shu yerga qo'shiladi.
export const grade1Nazariy = [
  {
    slug: 'dars01-sanash-1-5',
    title: 'Dars 1. Predmetlarni sanash va 1–5 sonlar',
    desc: 'Predmetlarni birma-bir sanash, kardinallik, raqam ↔ miqdor (1–5).',
    Component: lazy(() => import('../components/grade1/Dars01.jsx')),
  },
  {
    slug: 'dars02-raqamlar-1-5',
    title: 'Dars 2. Raqamlar 1–5',
    desc: 'Raqam shaklini tanish (1–5), raqam ↔ miqdor, 1–5 tartiblash.',
    Component: lazy(() => import('../components/grade1/Dars02.jsx')),
  },
  {
    slug: 'dars03-sonlar-6-10-nol',
    title: 'Dars 3. Sonlar 6–10 va 0 soni',
    desc: "6–10 ni \"5 va yana\" bilan sanash, son ↔ miqdor, 6–10 tartiblash, nol (bo'sh uy).",
    Component: lazy(() => import('../components/grade1/Dars03.jsx')),
  },
  {
    slug: 'dars04-taqqoslash-10',
    title: 'Dars 4. Sonlarni taqqoslash (10 gacha)',
    desc: "Ikki to'plamni sanab taqqoslash, katta / kichik / teng, > < = belgilari.",
    Component: lazy(() => import('../components/grade1/Dars04.jsx')),
  },
  {
    slug: 'dars05-sonning-tarkibi-2-5',
    title: 'Dars 5. Sonning tarkibi 2–5',
    desc: "Sonni ikki qismga bo'lish (ikki savat), 2–5 tarkibi, juftlar; tap/drag bilan.",
    Component: lazy(() => import('../components/grade1/Dars05.jsx')),
  },
  {
    slug: 'dars06-son-tarkibi-6-10',
    title: 'Dars 6. Son tarkibi 6–10',
    desc: "Ikki rangli ten-frame (qizil/yashil): sonni ikki qismga bo'lish (6–10), o'nlik juftlari; Dars05 metodi.",
    Component: lazy(() => import('../components/grade1/Dars06.jsx')),
  },
  {
    slug: 'dars07-qoshish-manosi',
    title: "Dars 7. Qo'shishning ma'nosi",
    desc: "Ikki guruhni birlashtirish — qo'shish (+); birlashsa ko'payadi (10 ichida).",
    Component: lazy(() => import('../components/grade1/Dars07.jsx')),
  },
  {
    slug: 'dars08-ayirish-manosi',
    title: "Dars 8. Ayirishning ma'nosi",
    desc: "Olib tashlash/berish — ayirish (−); olinsa kamayadi (10 ichida).",
    Component: lazy(() => import('../components/grade1/Dars08.jsx')),
  },
  {
    slug: 'dars09-amallar-5-ichida',
    title: "Dars 9. 5 ichida qo'shish va ayirish",
    desc: "Son o'qida sakrash (+ oldinga, − orqaga); 5 ichida amaliyot.",
    Component: lazy(() => import('../components/grade1/Dars09.jsx')),
  },
  {
    slug: 'dars10-amallar-10-ichida',
    title: "Dars 10. 10 ichida qo'shish va ayirish",
    desc: "Son o'qi 0–10; aralash qo'shish va ayirish.",
    Component: lazy(() => import('../components/grade1/Dars10.jsx')),
  },
  {
    slug: 'dars11-orin-almashtirish',
    title: "Dars 11. O'rin almashtirish",
    desc: "3+2 = 2+3; qo'shiluvchilar o'rin almashsa, yig'indi o'zgarmaydi.",
    Component: lazy(() => import('../components/grade1/Dars11.jsx')),
  },
  {
    slug: 'dars12-tenglik-tengsizlik-qavslar',
    title: "Dars 12. Tenglik, tengsizlik va qavslar",
    desc: "Yozuv to'g'rimi-noto'g'rimi; =, >, < belgilari; qavs ichini avval sanaymiz (10 ichida).",
    Component: lazy(() => import('../components/grade1/Dars12.jsx')),
  },
  {
    slug: 'dars13-onlik-sanoq-birligi',
    title: "Dars 13. O'nlik — sanoq birligi",
    desc: "10 ta birlik = 1 o'nlik (dasta); maktab, Jasur qo'shiladi.",
    Component: lazy(() => import('../components/grade1/Dars13.jsx')),
  },
  {
    slug: 'dars14-sonlar-11-15',
    title: "Dars 14. Sonlar 11–15",
    desc: "1 o'nlik + birliklar = o'n bir...o'n besh (Rekenrek 2 qator).",
    Component: lazy(() => import('../components/grade1/Dars14.jsx')),
  },
  {
    slug: 'dars15-sonlar-16-20',
    title: "Dars 15. Sonlar 16–20",
    desc: "1 o'nlik + birliklar = o'n olti...yigirma; bozor sahnasi.",
    Component: lazy(() => import('../components/grade1/Dars15.jsx')),
  },
  {
    slug: 'dars16-ongacha-toldirish',
    title: "Dars 16. 10gacha to'ldirish",
    desc: "To'liq o'nlikgacha nechta yetishmaydi (8+2, 7+3); 10 katakli javon.",
    Component: lazy(() => import('../components/grade1/Dars16.jsx')),
  },
  {
    slug: 'dars17-otib-qoshish',
    title: "Dars 17. O'nlikdan o'tib qo'shish",
    desc: "8+5 = 8+2+3 = 10+3 = 13; avval 10 ga to'ldir, keyin qolganini.",
    Component: lazy(() => import('../components/grade1/Dars17.jsx')),
  },
  {
    slug: 'dars18-otib-qoshish-amaliyot',
    title: "Dars 18. O'tib qo'shish — amaliyot",
    desc: "20 ichida o'nlikdan o'tib qo'shish mashqi (bozor, olma).",
    Component: lazy(() => import('../components/grade1/Dars18.jsx')),
  },
  {
    slug: 'dars19-otib-ayirish',
    title: "Dars 19. O'nlikdan o'tib ayirish",
    desc: "13−5 = 13−3−2 = 10−2 = 8; avval 10 ga tushir, keyin qolganini.",
    Component: lazy(() => import('../components/grade1/Dars19.jsx')),
  },
  {
    slug: 'dars20-otib-ayirish-amaliyot',
    title: "Dars 20. O'tib ayirish — amaliyot",
    desc: "20 ichida o'nlikdan o'tib ayirish mashqi (uy sahnasi).",
    Component: lazy(() => import('../components/grade1/Dars20.jsx')),
  },
  {
    slug: 'dars21-sonlar-21-100',
    title: "Dars 21. Sonlar 21–100: o'nlik va birlik",
    desc: "10 birlik = 1 o'nlik; ikki xonali son = o'nliklar + birliklar (AppleViz).",
    Component: lazy(() => import('../components/grade1/Dars21.jsx')),
  },
  {
    slug: 'dars22-ikki-xonali-taqqoslash',
    title: "Dars 22. Ikki xonali sonlarni o'qish, yozish va taqqoslash",
    desc: "Avval o'nlik, teng bo'lsa birlik; > < = belgilari (timsoh).",
    Component: lazy(() => import('../components/grade1/Dars22.jsx')),
  },
  {
    slug: 'dars23-sonli-ketma-ketlik',
    title: "Dars 23. Sonli ketma-ketlik: 5 va 10 lab",
    desc: "Skip-count 10 lab va 5 lab, oldinga va orqaga (100 dan).",
    Component: lazy(() => import('../components/grade1/Dars23.jsx')),
  },
  {
    slug: 'dars24-yumaloq-onliklar',
    title: "Dars 24. Yumaloq o'nliklarni qo'shish va ayirish",
    desc: "20+30, 80−30: o'nliklarni sanaymiz (столбиксиз).",
    Component: lazy(() => import('../components/grade1/Dars24.jsx')),
  },
  {
    slug: 'dars25-ikki-plus-bir-xonali',
    title: "Dars 25. Ikki xonali + bir xonali (o'tishsiz)",
    desc: "34+5: birlikni birlikka qo'shamiz, o'nlik o'zgarmaydi.",
    Component: lazy(() => import('../components/grade1/Dars25.jsx')),
  },
  {
    slug: 'dars26-ikki-plus-ikki-xonali',
    title: "Dars 26. Ikki xonali + ikki xonali (o'tishsiz)",
    desc: "34+25: o'nlikni o'nlikka, birlikni birlikka (razryad bo'yicha).",
    Component: lazy(() => import('../components/grade1/Dars26.jsx')),
  },
  {
    slug: 'dars27-ikki-xonali-ayirish',
    title: "Dars 27. Ikki xonali va 100 dan ayirish",
    desc: "68−25 razryad bo'yicha; 100−N (yuz = 10 o'nlik); xato topish.",
    Component: lazy(() => import('../components/grade1/Dars27.jsx')),
  },
  {
    slug: 'dars28-masala-yigindiga',
    title: "Dars 28. Masala tuzilishi. Yig'indiga masala",
    desc: "Masala 4 qism: shart → savol → amal → javob; birlashtirilsa qo'shamiz.",
    Component: lazy(() => import('../components/grade1/Dars28.jsx')),
  },
  {
    slug: 'dars29-qoldiq-nomalum-qoshiluvchi',
    title: "Dars 29. Qoldiqqa va noma'lum qo'shiluvchiga masala",
    desc: "Olib qo'yilsa — ayiramiz (qoldiq); qancha qo'shilgan — butundan qismni ayiramiz; xato topish.",
    Component: lazy(() => import('../components/grade1/Dars29.jsx')),
  },
  {
    slug: 'dars30-tarkibli-masala-jadval',
    title: "Dars 30. Tarkibli masala: jadval bilan (jami va qoldi)",
    desc: "Masalani jadvalga yozamiz: edi/keldi/jami (qo'shish), edi/ketdi/qoldi (ayirish); bo'sh katakni topamiz.",
    Component: lazy(() => import('../components/grade1/Dars30.jsx')),
  },
  {
    slug: 'dars31-ikki-qadamli-masala',
    title: "Dars 31. Ikki qadamli masala",
    desc: "Avval birinchi qadam, keyin ikkinchi (birinchi javobini ishlatadi); yechimni qadamma-qadam quramiz.",
    Component: lazy(() => import('../components/grade1/Dars31.jsx')),
  },
  {
    slug: 'dars32-fazo-va-chiziqlar',
    title: "Dars 32. Fazo va chiziqlar",
    desc: "Chiziq turlari: to'g'ri / egri / siniq; fazoviy so'zlar: tepada, pastda, chapda, o'ngda, orasida.",
    Component: lazy(() => import('../components/grade1/Dars32.jsx')),
  },
  {
    slug: 'dars33-shakllar',
    title: "Dars 33. Shakllar",
    desc: "Doira, kvadrat, uchburchak, to'rtburchak; shaklni tanish va burchaklar sonini sanash.",
    Component: lazy(() => import('../components/grade1/Dars33.jsx')),
  },
  {
    slug: 'dars34-detsimetr-va-metr',
    title: "Dars 34. Detsimetr va metr",
    desc: "1 dm = 10 sm; 1 m = 10 dm; chizg'ich bilan o'lchash; uzunliklarni qo'shish.",
    Component: lazy(() => import('../components/grade1/Dars34.jsx')),
  },
  {
    slug: 'dars35-massa-kilogramm',
    title: "Dars 35. Massa — kilogramm",
    desc: "Og'irroq/yengilroq (tarozi); kilogramm — massa o'lchovi; kg da sodda sanoq.",
    Component: lazy(() => import('../components/grade1/Dars35.jsx')),
  },
  {
    slug: 'dars36-piktogramma-jadval',
    title: "Dars 36. Piktogramma va jadvalni o'qish",
    desc: "Rasm-piktogramma va sodda jadvalni o'qish; nima ko'p/kam; jami nechta.",
    Component: lazy(() => import('../components/grade1/Dars36.jsx')),
  },
]

// 1-sinf AMALIY mashg'ulotlar. Hozircha faqat mexanika namunalari galereyasi;
// har darsga to'liq amaliyot darsi keyin bosqichma-bosqich shu yerga qo'shiladi.
export const grade1Amaliy = [
  {
    slug: 'dars01-amaliyot',
    title: 'Dars 1 amaliyoti — sanash 1–5 (10 topshiriq)',
    desc: 'Ra\'noning tongi bo\'ylab 10 ta interaktiv topshiriq (sanash va tanlash), osondan qiyinga; harakatlanuvchi animatsiyalar.',
    Component: lazy(() => import('../components/grade1/practice/dars01/Dars01Practice.jsx')),
  },
  {
    slug: 'dars02-amaliyot',
    title: 'Dars 2 amaliyoti — raqamlar 1–5 (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (raqamni tanlash va juftlarni ulash), osondan qiyinga; harakatlanuvchi animatsiyalar.',
    Component: lazy(() => import('../components/grade1/practice/dars02/Dars02Practice.jsx')),
  },
  {
    slug: 'dars03-amaliyot',
    title: 'Dars 3 amaliyoti — sonlar 6–10 va 0 (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq («5 va yana» modeli, nol, drag-ulash, son hosil qilish), osondan qiyinga; harakatlanuvchi animatsiyalar.',
    Component: lazy(() => import('../components/grade1/practice/dars03/Dars03Practice.jsx')),
  },
  {
    slug: 'dars04-amaliyot',
    title: 'Dars 4 amaliyoti — taqqoslash 10 gacha (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (mantiqiy parad, ko\'p/kam/teng, > < = belgilari, teng qilish, timsohni ovqatlantirish), 6 oson + 4 qiyin.',
    Component: lazy(() => import('../components/grade1/practice/dars04/Dars04Practice.jsx')),
  },
  {
    slug: 'dars05-amaliyot',
    title: 'Dars 5 amaliyoti — sonning tarkibi 2–5 (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (yashirin qism, son uyi, teng bo\'lish, mantiqiy parad, dorboz tarozisi), 5 oson + 5 qiyin. Sirk syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars05/Dars05Practice.jsx')),
  },
  {
    slug: 'dars06-amaliyot',
    title: 'Dars 6 amaliyoti — son tarkibi 6–10 (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (ikki rangli o\'nlik-ramka, son uyi, o\'nlik juftlari, navbat-naqsh mantiq, avtobusni to\'ldirish), 5 oson + 5 qiyin. Avtobus sayohati syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars06/Dars06Practice.jsx')),
  },
  {
    slug: 'dars07-amaliyot',
    title: 'Dars 7 amaliyoti — qo\'shishning ma\'nosi (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (guruhlar qo\'shilishi, yozuv tanlash, o\'suvchi naqsh mantiq, «Birlashtir!» tugmasi), 5 oson + 5 qiyin. O\'yin maydonchasi syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars07/Dars07Practice.jsx')),
  },
  {
    slug: 'dars08-amaliyot',
    title: 'Dars 8 amaliyoti — ayirishning ma\'nosi (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (olib tashlash-kamayish, noma\'lum ayriluvchi, kamayuvchi naqsh, «Ayirishni bajar» — bola o\'zi uchiradi), 1 oson + 3 o\'rta + 6 qiyin. Qishloq hovlisi syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars08/Dars08Practice.jsx')),
  },
  {
    slug: 'dars09-amaliyot',
    title: 'Dars 9 amaliyoti — 5 ichida qo\'shish va ayirish (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (son o\'qida sakrash, teskari-detektiv, aralash zanjir, analogiya-mantiq, «Qurbaqani sakrat!»), 1 oson + 3 o\'rta + 6 qiyin. Hovuz bo\'yida syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars09/Dars09Practice.jsx')),
  },
  {
    slug: 'dars10-amaliyot',
    title: 'Dars 10 amaliyoti — 10 ichida qo\'shish va ayirish (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (yuk-lifti son o\'qi, detektiv, aralash zanjir, ortiqchani top, «Sehrli mashina»), 1 oson + 3 o\'rta + 6 qiyin. Fabrika syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars10/Dars10Practice.jsx')),
  },
  {
    slug: 'dars11-amaliyot',
    title: 'Dars 11 amaliyoti — o\'rin almashtirish (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (a+b=b+a, kommutativ tenglama, juftlash, simmetriya-mantiq, «Vagonlarni almashtir!»), 1 oson + 3 o\'rta + 6 qiyin. Poyezd bekati syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars11/Dars11Practice.jsx')),
  },
  {
    slug: 'dars12-amaliyot',
    title: 'Dars 12 amaliyoti — tenglik, tengsizlik va qavslar (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (=, >, < belgilari, yozuv to\'g\'rimi, qavs-ichi-avval, tartiblash-mantiq, «Qavs qutisi»), 1 oson + 3 o\'rta + 6 qiyin. Timsohlar ko\'li syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars12/Dars12Practice.jsx')),
  },
  {
    slug: 'dars13-amaliyot',
    title: 'Dars 13 amaliyoti — o\'nlik, sanoq birligi (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (10 birlik = 1 o\'nlik, dasta yasash, o\'nlikka to\'ldirish, o\'nlik/birlik guruhlash, «O\'nlikni yasab ol!»), 1 oson + 3 o\'rta + 6 qiyin. Qalam do\'koni syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars13/Dars13Practice.jsx')),
  },
  {
    slug: 'dars14-amaliyot',
    title: 'Dars 14 amaliyoti — Sonlar 11–15 (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (1 o\'nlik + birliklar = o\'n bir…o\'n besh, teng ajratish, ketma-ketlik, o\'rin qiymati, «O\'n uchni yasab ol!»), 1 oson + 3 o\'rta + 6 qiyin. Qalam do\'koni syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars14/Dars14Practice.jsx')),
  },
  {
    slug: 'dars15-amaliyot',
    title: 'Dars 15 amaliyoti — Sonlar 16–20 (10 topshiriq)',
    desc: '10 ta interaktiv topshiriq (1 o\'nlik + birliklar = o\'n olti…yigirma, ajratish, son↔model juftlash, 20 = 2 o\'nlik, «Yigirmani yasab ol!»), 1 oson + 3 o\'rta + 6 qiyin. Qalam do\'koni syujeti.',
    Component: lazy(() => import('../components/grade1/practice/dars15/Dars15Practice.jsx')),
  },
  {
    slug: 'amaliyot-namunalar',
    title: '★ Amaliyot namunalari (25 ta)',
    desc: 'Sanash, juftlar, taqqoslash, son uyi, o\'nlik, o\'tish, razryad, xato top, masala jadvali, kattaliklar va boshqalar.',
    Component: lazy(() => import('../components/grade1/practice/PracticePreview.jsx')),
  },
]
