import { lazy } from 'react'

// 4-sinf NAZARIY darslari. Barcha yangi komponentlar faqat components/grade4/ ichida yaratiladi.
export const grade4Nazariy = [
  {
    slug: 'dars01-kop-xonali-sonlar-sinflari',
    title: "Dars 1. Ko'p xonali sonlar sinflari",
    desc: "Ko'p xonali sonni o'ngdan uch raqamli sinflarga ajratish, raqamning o'rin qiymatini aniqlash va ichki nol qatnashgan sonlarni tuzish.",
    Component: lazy(() => import('../components/grade4/Dars01.jsx')),
  },
  {
    slug: 'dars02-kop-xonali-sonlarni-oqish-va-yozish',
    title: "Dars 2. Ko'p xonali sonlarni o'qish va yozish",
    desc: "Ko'p xonali sonlarni sinflar bo'yicha o'qish, ovozli shakldan raqamli yozuvga o'tish, ichki nollarni saqlash va qayta o'qib tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars02.jsx')),
  },
  {
    slug: 'dars03-kop-xonali-sonning-xona-tarkibi',
    title: "Dars 3. Ko'p xonali sonning xona tarkibi",
    desc: "Raqam, xona va xona qiymatini farqlash, sonni xona qo'shiluvchilariga yoyish hamda yoyiq yozuvdan sonni tiklash.",
    Component: lazy(() => import('../components/grade4/Dars03.jsx')),
  },
  {
    slug: 'dars04-kop-xonali-sonlarni-taqqoslash',
    title: "Dars 4. Ko'p xonali sonlarni taqqoslash",
    desc: "Avval raqamlar sonini, keyin chapdagi birinchi farqli xonani taqqoslash, belgini to'g'ri qo'yish va sonlarni tartiblash.",
    Component: lazy(() => import('../components/grade4/Dars04.jsx')),
  },
  {
    slug: 'dars05-kop-xonali-sonlarni-yaxlitlash',
    title: "Dars 5. Ko'p xonali sonlarni yaxlitlash",
    desc: "Ko'p xonali sonlarni o'nlik, yuzlik va minglikkacha yaxlitlash hamda vaziyatga mos aniqlikni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars05.jsx')),
  },
  {
    slug: 'dars06-sonlarning-xonalari-va-sinflari',
    title: "Dars 6. Sonlarning xonalari va sinflari",
    desc: "Sinf va xona, o'qish-yozish, yoyiq tarkib, taqqoslash hamda yaxlitlashni bitta murakkab ma'lumot paketida birlashtirish.",
    Component: lazy(() => import('../components/grade4/Dars06.jsx')),
  },
  {
    slug: 'dars07-pozitsion-va-nopozitsion-sanoq-sistemalari',
    title: 'Dars 7. Pozitsion va nopozitsion sanoq sistemalari',
    desc: "Rim raqamlarini o'qish va yozish, so'ng pozitsion hamda nopozitsion yozuvlarni dalil bilan farqlash.",
    Component: lazy(() => import('../components/grade4/Dars07.jsx')),
  },
  {
    slug: 'dars08-kop-xonali-sonlarni-qoshish-va-ayirish',
    title: "Dars 8. Ko'p xonali sonlarni qo'shish va ayirish",
    desc: "Ko'p xonali sonlarni xona ostiga xona qilib yozish, ko'chirish va almashtirish bilan hisoblash hamda natijani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars08.jsx')),
  },
  {
    slug: 'dars09-kop-xonali-sonni-bir-xonali-songa-kopaytirish',
    title: "Dars 9. Ko'p xonali sonni bir xonali songa ko'paytirish",
    desc: "Ko'p xonali sonni bir xonali songa yoyiq va ustun modellar orqali ko'paytirish, ko'chirish va nol qatnashgan xonalarni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars09.jsx')),
  },
  {
    slug: 'dars10-kop-xonali-sonni-ikki-xonali-songa-kopaytirish',
    title: "Dars 10. Ko'p xonali sonni ikki xonali songa ko'paytirish",
    desc: "Ikki to'liqsiz ko'paytmani tuzish, o'nliklar qatorini bir xona siljitish va natijani taxmin bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars10.jsx')),
  },
  {
    slug: 'dars11-kop-xonali-sonni-uch-xonali-songa-kopaytirish',
    title: "Dars 11. Ko'p xonali sonni uch xonali songa ko'paytirish",
    desc: "Birlik, o'nlik va yuzlik to'liqsiz ko'paytmalarini tegishli xonadan boshlab yozish, nol o'rnini saqlash va qatorlarni qo'shish.",
    Component: lazy(() => import('../components/grade4/Dars11.jsx')),
  },
  {
    slug: 'dars12-kop-xonali-sonni-bir-xonali-songa-bolish',
    title: "Dars 12. Ko'p xonali sonni bir xonali songa bo'lish",
    desc: "Birinchi to'liqsiz bo'linuvchini topish, yozma bo'lish siklini bajarish, bo'linmadagi nolni saqlash va natijani teskari amal bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars12.jsx')),
  },
  {
    slug: 'dars13-kop-xonali-sonni-ikki-xonali-songa-bolish',
    title: "Dars 13. Ko'p xonali sonni ikki xonali songa bo'lish",
    desc: "Bo'linma raqamini yaqin ko'paytmalar orqali tanlash, sinov raqamini tuzatish va natijani teskari ko'paytirish bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars13.jsx')),
  },
  {
    slug: 'dars14-harakat-masalalari',
    title: 'Dars 14. Harakatga doir masalalar',
    desc: "Masofa, tezlik va vaqtni o'zgarmas yo'l modelida bog'lash, noma'lum kattalikni aniqlash va mos amalni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars14.jsx')),
  },
  {
    slug: 'dars15-ortacha-arifmetik',
    title: "Dars 15. O'rtacha arifmetik",
    desc: "Qiymatlar yig'indisini teng taqsimlash orqali o'rtacha arifmetikni topish va natijalarni adolatli taqqoslash.",
    Component: lazy(() => import('../components/grade4/Dars15.jsx')),
  },
  {
    slug: 'dars16-formulalar',
    title: 'Dars 16. Formulalar',
    desc: "Konkret shakl va katakli modeldan perimetr hamda yuza formulalariga o'tish, qiymat qo'yish va ikki kattalikni farqlash.",
    Component: lazy(() => import('../components/grade4/Dars16.jsx')),
  },
  {
    slug: 'dars17-shkalalar',
    title: 'Dars 17. Shkalalar',
    desc: "Shkaladagi bo'linma qiymatini topish, belgilar va oraliqlarni farqlash hamda noldan boshlanmaydigan gorizontal va vertikal shkalalarni o'qish.",
    Component: lazy(() => import('../components/grade4/Dars17.jsx')),
  },
  {
    slug: 'dars18-kasr-tushunchasi',
    title: 'Dars 18. Kasr tushunchasi',
    desc: "Butunni teng qismlarga ajratish, surat va maxraj ma'nosini model, yozuv hamda sonlar nurida bog'lash.",
    Component: lazy(() => import('../components/grade4/Dars18.jsx')),
  },
  {
    slug: 'dars19-kasrlarni-taqqoslash',
    title: 'Dars 19. Kasrlarni taqqoslash',
    desc: "Kasrlarni teng maxraj, teng surat va yarim bilan taqqoslash strategiyalaridan mosini tanlab solishtirish.",
    Component: lazy(() => import('../components/grade4/Dars19.jsx')),
  },
  {
    slug: 'dars20-kasrlarni-qoshish',
    title: "Dars 20. Kasrlarni qo'shish",
    desc: "Bir xil maxrajli kasrlarni model va sonlar nurida qo'shish, suratlarni qo'shib maxrajni o'zgartirmaslik.",
    Component: lazy(() => import('../components/grade4/Dars20.jsx')),
  },
  {
    slug: 'dars21-kasrlarni-ayirish',
    title: 'Dars 21. Kasrlarni ayirish',
    desc: "Bir xil maxrajli kasrlarni olib tashlash va farq modeli bilan ayirish, natijani qo'shish orqali tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars21.jsx')),
  },
  {
    slug: 'dars22-sonning-kasr-qismini-topish',
    title: 'Dars 22. Sonning kasr qismini topish',
    desc: "Butunni teng ulushlarga ajratib, avval bitta ulushni, so'ng kasr suratiga mos qismini topish va natijani model bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars22.jsx')),
  },
  {
    slug: 'dars23-kasrli-masalalar',
    title: 'Dars 23. Kasrli masalalar: qism va butun',
    desc: "Kasrli masalalarda ma'lum va noma'lum miqdorni ajratish, butundan qismni topish yoki ma'lum qismdan butunni tiklash hamda javobni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars23.jsx')),
  },
  {
    slug: 'dars24-onli-kasrlar',
    title: "Dars 24. O'nli kasrlar",
    desc: "Maxraji 10, 100 va 1 000 bo'lgan kasrlarni o'nli yozuv bilan bog'lash, butun va kasr qismini o'qish hamda xona jadvalida ko'rsatish.",
    Component: lazy(() => import('../components/grade4/Dars24.jsx')),
  },
  {
    slug: 'dars25-toplamlar-eyler-venn-diagrammasi',
    title: "Dars 25. To'plamlar va Eyler-Venn diagrammasi",
    desc: "Obyektlarni ikki mustaqil belgi bo'yicha faqat A, ikkalasi, faqat B yoki tashqari zonaga joylashtirish va diagrammadagi elementlarni sanash.",
    Component: lazy(() => import('../components/grade4/Dars25.jsx')),
  },
  {
    slug: 'dars26-uzunlik-birliklari',
    title: 'Dars 26. Uzunlik birliklari',
    desc: "mm, cm, dm, m va km orasidagi munosabatlarni modelda bog'lash, mos birlikni tanlash va tarkibli uzunlikni bitta birlikda yozish.",
    Component: lazy(() => import('../components/grade4/Dars26.jsx')),
  },
  {
    slug: 'dars27-massa-birliklari',
    title: 'Dars 27. Massa birliklari',
    desc: "g, kg, sentner va t orasidagi munosabatlarni guruhlash modeli bilan bog'lash, mos birlikni tanlash va tarkibli massani aylantirish.",
    Component: lazy(() => import('../components/grade4/Dars27.jsx')),
  },
  {
    slug: 'dars28-vaqt-birliklari',
    title: 'Dars 28. Vaqt birliklari',
    desc: "Soniya, minut, soat, sutka, hafta, oy, yil va asr orasidagi noo'nlik munosabatlarni tushunish, vaqtni aylantirish va davomiylikni topish.",
    Component: lazy(() => import('../components/grade4/Dars28.jsx')),
  },
  {
    slug: 'dars29-yuza-birliklari',
    title: 'Dars 29. Yuza birliklari',
    desc: "mm², cm², dm², m² va km²ni birlik kvadrat sifatida qurish, yuza birliklari orasidagi munosabatlarni aniqlash va mos birlikni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars29.jsx')),
  },
  {
    slug: 'dars30-kattalik-birliklarini-aylantirish',
    title: 'Dars 30. Kattalik birliklarini aylantirish',
    desc: "Uzunlik, massa, vaqt va yuza birliklarini o'z munosabatlari asosida aylantirish, aralash birliklarni birlashtirish va natijani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars30.jsx')),
  },
  {
    slug: 'dars31-kattaliklarga-doir-masalalar',
    title: 'Dars 31. Kattaliklarga doir masalalar',
    desc: "Aralash birlikli masalada ma'lum va noma'lum kattaliklarni ajratish, birliklarni tenglashtirish, amalni tanlash va javobni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars31.jsx')),
  },
  {
    slug: 'dars32-hajm-birliklari',
    title: 'Dars 32. Hajm birliklari',
    desc: "Hajmni birlik kublar orqali tushunish, cm³, dm³, m³ va litr orasidagi munosabatlarni qo'llash.",
    Component: lazy(() => import('../components/grade4/Dars32.jsx')),
  },
  {
    slug: 'dars33-burchak-turlari',
    title: 'Dars 33. Burchak turlari',
    desc: "Burchaklarni ochilishiga ko'ra o'tkir, to'g'ri, o'tmas va yoyiq turlarga ajratish.",
    Component: lazy(() => import('../components/grade4/Dars33.jsx')),
  },
  {
    slug: 'dars34-burchaklarni-yasash',
    title: 'Dars 34. Burchaklarni yasash',
    desc: "Transportir markazi, asos chizig'i va to'g'ri shkaladan foydalanib berilgan gradusli burchakni yasash va tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars34.jsx')),
  },
  {
    slug: 'dars35-uchburchak-turlari',
    title: 'Dars 35. Uchburchak turlari',
    desc: "Uchburchaklarni tomonlari va burchaklariga ko'ra mustaqil tasniflash hamda bir figuraga ikki xil nom berish.",
    Component: lazy(() => import('../components/grade4/Dars35.jsx')),
  },
  {
    slug: 'dars36-togri-tortburchak-va-kvadrat',
    title: "Dars 36. To'g'ri to'rtburchak va kvadrat",
    desc: "To'g'ri to'rtburchak va kvadrat xossalarini solishtirish, kvadratni maxsus to'g'ri to'rtburchak sifatida tushunish.",
    Component: lazy(() => import('../components/grade4/Dars36.jsx')),
  },
  {
    slug: 'dars37-perimetr-va-yuza',
    title: 'Dars 37. Figuralarning perimetri va yuzi',
    desc: "Chegara uzunligi bilan egallangan sirtni farqlash, to'g'ri to'rtburchak va kvadrat perimetri hamda yuzini hisoblash.",
    Component: lazy(() => import('../components/grade4/Dars37.jsx')),
  },
  {
    slug: 'dars38-geometrik-yasashlar',
    title: 'Dars 38. Geometrik yasashlar',
    desc: "Chizg'ich, go'niya va transportir bilan kesma, perpendikulyar, parallel chiziq va burchak yasash.",
    Component: lazy(() => import('../components/grade4/Dars38.jsx')),
  },
  {
    slug: 'dars39-nuqta-koordinatalari',
    title: 'Dars 39. Nuqta koordinatalari va koordinata burchagi',
    desc: "Birinchi chorakda koordinata boshi, x va y o'qlarini o'qish, nuqtani avval x, keyin y bo'yicha joylashtirish.",
    Component: lazy(() => import('../components/grade4/Dars39.jsx')),
  },
  {
    slug: 'dars40-fazoviy-shakllar-va-yoyilmalar',
    title: 'Dars 40. Fazoviy shakllar va yoyilmalar',
    desc: "Kub va to'g'ri burchakli parallelepipedning yoq, qirra va uchlarini ajratish, yaroqli yoyilmani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars40.jsx')),
  },
  {
    slug: 'dars41-simmetriya-va-burilish-simmetriyasi',
    title: 'Dars 41. Simmetriya va burilish simmetriyasi',
    desc: "Simmetriya o'qi, mos nuqtalar, aylanish markazi va eng kichik mos tushish burchagini aniqlash.",
    Component: lazy(() => import('../components/grade4/Dars41.jsx')),
  },
  {
    slug: 'dars42-tenglamalar',
    title: 'Dars 42. Tenglamalar',
    desc: "Tenglik, noma'lum va tenglama ildizini tushunish, noma'lum komponent uchun teskari amalni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars42.jsx')),
  },
  {
    slug: 'dars43-tenglamalarni-yechish-va-tekshirish',
    title: 'Dars 43. Tenglamalarni yechish va tekshirish',
    desc: "Tenglama ildizini topish, boshlang'ich tenglamaga qo'yish va ikki tomon tengligini tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars43.jsx')),
  },
  {
    slug: 'dars44-murakkab-masalalar',
    title: 'Dars 44. Murakkab masalalar',
    desc: "Yashirin oraliq savolni topish, bog'langan amallar tartibini modelda asoslash va yakuniy javobni tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars44.jsx')),
  },
  {
    slug: 'dars45-harakatga-doir-masalalar',
    title: 'Dars 45. Harakatga doir masalalar',
    desc: "Ikki obyektning yaqinlashish, uzoqlashish va quvib yetish harakatida yig'indi yoki ayirma tezlikni tanlash.",
    Component: lazy(() => import('../components/grade4/Dars45.jsx')),
  },
  {
    slug: 'dars46-qism-va-butunni-topish',
    title: 'Dars 46. Qism va butunni topishga doir masalalar',
    desc: "Kasr orqali bitta ulushni, kerakli qismni, noma'lum butunni va qolgan miqdorni ketma-ket topish.",
    Component: lazy(() => import('../components/grade4/Dars46.jsx')),
  },
  {
    slug: 'dars47-tengsizliklarni-tanlash-usuli',
    title: 'Dars 47. Tengsizliklarni tanlash usulida yechish',
    desc: "Berilgan chekli sohada qiymatlarni tartib bilan tekshirish, chegarani aniqlash va barcha yechimlarni yozish.",
    Component: lazy(() => import('../components/grade4/Dars47.jsx')),
  },
  {
    slug: 'dars48-qoshish-xossalari',
    title: "Dars 48. Qo'shishning o'rin almashtirish va guruhlash xossalari",
    desc: "Qo'shiluvchilarni natijani o'zgartirmay almashtirish va guruhlash, qulay juftlar orqali tez hisoblash.",
    Component: lazy(() => import('../components/grade4/Dars48.jsx')),
  },
  {
    slug: 'dars49-mulohazalar-va-hukmlar',
    title: 'Dars 49. Mulohazalar va hukmlar',
    desc: "Matematik mulohazani savol va buyruqdan ajratish, rostlikni hisob, model yoki qarshi misol bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars49.jsx')),
  },
  {
    slug: 'dars50-grafiklar-va-malumotlar',
    title: "Dars 50. Grafiklar va ma'lumotlarni tasvirlash usullari",
    desc: "Jadval, ustunli diagramma va chiziqli grafikni o'qish, masshtabni hisobga olish va ma'lumotdan xulosa chiqarish.",
    Component: lazy(() => import('../components/grade4/Dars50.jsx')),
  },
  {
    slug: 'dars51-yakuniy-takrorlash',
    title: "Dars 51. O'rganilgan mavzularni yakuniy takrorlash",
    desc: "Vaziyatni tushunish, mos modelni tanlash, hisoblash, tekshirish va izohlashni kurs mavzulari bo'ylab bog'lash.",
    Component: lazy(() => import('../components/grade4/Dars51.jsx')),
  },
]

// 4-sinf AMALIY mashg'ulotlari. Har nazariy darsga 10 tekshiriladigan topshiriq
// (ETALON_4SINF §9). Amaliyot ovozsiz ishlaydi.
export const grade4Amaliy = [
  {
    slug: 'dars01-amaliyot-sinflar',
    title: "Dars 1. Amaliyot: sonlar sinflari",
    desc: "10 topshiriq: sinf chegarasi, xona qiymati, ichki nollar, xatoni topish va yangi shaklga ko'chirish.",
    Component: lazy(() => import('../components/grade4/Dars01Practice.jsx')),
  },
  {
    slug: 'dars02-amaliyot-oqish-yozish',
    title: "Dars 2. Amaliyot: sonlarni o'qish va yozish",
    desc: "10 topshiriq: sinflar bo'yicha o'qish, ovozli shakldan yozuvga o'tish, ichki nollar va qayta o'qib tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars02Practice.jsx')),
  },
  {
    slug: 'dars03-amaliyot-xona-tarkibi',
    title: "Dars 3. Amaliyot: sonning xona tarkibi",
    desc: "10 topshiriq: raqamning xona qiymati, yoyiq yozuv, sonni tiklash, ichki nollar va xatoni tahlil qilish.",
    Component: lazy(() => import('../components/grade4/Dars03Practice.jsx')),
  },
  {
    slug: 'dars04-amaliyot-taqqoslash',
    title: "Dars 4. Amaliyot: sonlarni taqqoslash",
    desc: "10 topshiriq: raqamlar soni, birinchi farqli xona, belgilar, tartiblash va noto'g'ri strategiyani tuzatish.",
    Component: lazy(() => import('../components/grade4/Dars04Practice.jsx')),
  },
  {
    slug: 'dars05-amaliyot-yaxlitlash',
    title: "Dars 5. Amaliyot: sonlarni yaxlitlash",
    desc: "10 topshiriq: o'nlik, yuzlik, minglik va o'n minglikkacha yaxlitlash, chegaraviy holat va aniqlik tanlash.",
    Component: lazy(() => import('../components/grade4/Dars05Practice.jsx')),
  },
  {
    slug: 'dars06-amaliyot-xonalar-sinflar',
    title: "Dars 6. Amaliyot: sonlarning xonalari va sinflari",
    desc: "10 topshiriq: o'qish, yoyish, xona qiymati, taqqoslash va yaxlitlashni bir paketda birlashtirish.",
    Component: lazy(() => import('../components/grade4/Dars06Practice.jsx')),
  },
  {
    slug: 'dars07-amaliyot-sanoq-sistemalari',
    title: 'Dars 7. Amaliyot: pozitsion va nopozitsion sanoq sistemalari',
    desc: "10 topshiriq: Rim yozuvi 1 dan 20 gacha, xona qiymati, ikki sanoq sistemasini farqlash, xatoni tahlil qilish va transfer.",
    Component: lazy(() => import('../components/grade4/Dars07Practice.jsx')),
  },
  {
    slug: 'dars08-amaliyot-qoshish-ayirish',
    title: "Dars 8. Amaliyot: ko'p xonali sonlarni qo'shish va ayirish",
    desc: "10 topshiriq: xonalarni tekislash, ko'chirish, nollar orqali maydalash, teskari amal va natijani tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars08Practice.jsx')),
  },
  {
    slug: 'dars09-amaliyot-bir-xonali-kopaytirish',
    title: "Dars 9. Amaliyot: bir xonali songa ko'paytirish",
    desc: "10 topshiriq: teng guruhlar, ustun yozuvi, xona bo'yicha ko'paytirish, ichki nol, taxmin va qulay strategiya.",
    Component: lazy(() => import('../components/grade4/Dars09Practice.jsx')),
  },
  {
    slug: 'dars10-amaliyot-ikki-xonali-kopaytirish',
    title: "Dars 10. Amaliyot: ikki xonali songa ko'paytirish",
    desc: "10 topshiriq: ikki to'liqsiz ko'paytma, o'nliklar qatorini siljitish, nol holati, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars10Practice.jsx')),
  },
  {
    slug: 'dars11-amaliyot-uch-xonali-kopaytirish',
    title: "Dars 11. Amaliyot: uch xonali songa ko'paytirish",
    desc: "10 topshiriq: uchta to'liqsiz ko'paytma, 0–1–2 xona siljishi, o'rtadagi nol, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars11Practice.jsx')),
  },
  {
    slug: 'dars12-amaliyot-bir-xonali-bolish',
    title: "Dars 12. Amaliyot: bir xonali songa bo'lish",
    desc: "10 topshiriq: birinchi to'liqsiz bo'linuvchi, yozma bo'lish sikli, ichki nol, qoldiq, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars12Practice.jsx')),
  },
  {
    slug: 'dars13-amaliyot-ikki-xonali-bolish',
    title: "Dars 13. Amaliyot: ikki xonali songa bo'lish",
    desc: "10 topshiriq: sinov raqami, yaqin ko'paytma, to'liqsiz bo'linuvchi, qoldiq, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars13Practice.jsx')),
  },
  {
    slug: 'dars14-amaliyot-harakat-masalalari',
    title: 'Dars 14. Amaliyot: harakat masalalari',
    desc: "10 topshiriq: masofa, tezlik va vaqt bog'lanishi, amal tanlash, birliklar, xato tahlili va ikki qismli transfer.",
    Component: lazy(() => import('../components/grade4/Dars14Practice.jsx')),
  },
  {
    slug: 'dars15-amaliyot-ortacha-arifmetik',
    title: "Dars 15. Amaliyot: o'rtacha arifmetik",
    desc: "10 topshiriq: yig'indi va qiymatlar soni, tenglashtirish, son chizig'i, chegara holati, xato tahlili va taqqoslash.",
    Component: lazy(() => import('../components/grade4/Dars15Practice.jsx')),
  },
  {
    slug: 'dars16-amaliyot-formulalar',
    title: 'Dars 16. Amaliyot: formulalar',
    desc: "10 topshiriq: perimetr va yuza formulalari, qiymat qo'yish, birliklar, chegara holati, xato tahlili va transfer.",
    Component: lazy(() => import('../components/grade4/Dars16Practice.jsx')),
  },
  {
    slug: 'dars17-amaliyot-shkalalar',
    title: 'Dars 17. Amaliyot: shkalalar',
    desc: "10 topshiriq: bo'linma qiymati, ko'rsatkichni o'qish, belgilar va bo'linmalarni farqlash hamda vertikal shkalaga transfer.",
    Component: lazy(() => import('../components/grade4/Dars17Practice.jsx')),
  },
  {
    slug: 'dars18-amaliyot-kasr-tushunchasi',
    title: 'Dars 18. Amaliyot: kasr tushunchasi',
    desc: "10 topshiriq: teng qismlar, surat va maxraj, kasr modeli, kasrni qurish hamda son nuridan modelga o'tish.",
    Component: lazy(() => import('../components/grade4/Dars18Practice.jsx')),
  },
  {
    slug: 'dars19-amaliyot-kasrlarni-taqqoslash',
    title: 'Dars 19. Amaliyot: kasrlarni taqqoslash',
    desc: "10 topshiriq: teng maxraj, teng surat, yarim mo'ljali, tartiblash, xato tahlili va strategiyani tanlash.",
    Component: lazy(() => import('../components/grade4/Dars19Practice.jsx')),
  },
  {
    slug: 'dars20-amaliyot-kasrlarni-qoshish',
    title: "Dars 20. Amaliyot: kasrlarni qo'shish",
    desc: "10 topshiriq: teng maxrajli kasrlarni qo'shish, maxrajni saqlash, noma'lum qo'shiluvchi va bir butun natija.",
    Component: lazy(() => import('../components/grade4/Dars20Practice.jsx')),
  },
  {
    slug: 'dars21-amaliyot-kasrlarni-ayirish',
    title: 'Dars 21. Amaliyot: kasrlarni ayirish',
    desc: "10 topshiriq: teng maxrajli kasrlarni ayirish, qoldiq, noma'lum ayiriluvchi, nol natija va qo'shish bilan tekshirish.",
    Component: lazy(() => import('../components/grade4/Dars21Practice.jsx')),
  },
]
