import { lazy } from 'react'

// 6-sinf NAZARIY darslari (Dars01–…). Yangi dars shu yerga qo'shiladi.
// Reja: DARSLAR_REJASI_1-11.md «6 класс» (53 dars, Б1–Б6).
// Darslik: src/books/grade6/matematika_6_uzb_2022.pdf.
// Etalon kontrakt (meros): grade5/Dars01 infratuzilmasi.
//
// UZ TERMIN (darslik, 22-bet): «кратное» = KARRALI («N ga karrali»,
// «N ning karralisi», «karrali sonlar»). `karra` — FAQAT ko'paytirish
// o'qilishi («olti karra olti»), hech qachon «кратное» emas.
//
// ⚠️ Б1 bloki (1–7-darslar, «Bo'linish») DARSLAR_REJASI da `черновик · сверка РУз`
// deb belgilangan. 2022-yilgi o'zbek darsligida bu mavzu alohida bob emas —
// u «5-sinfda o'tilganlarni takrorlash» ichida (10-bet, «Tub va murakkab sonlar.
// EKUB va EKUK»). Blokning o'rni metodist qaroriga qoldirilgan.
export const grade6Nazariy = [
  {
    slug: 'dars01-boluvchilar-va-karrali-sonlar',
    title: "Dars 1. Bo'luvchilar va karrali sonlar",
    desc: "Bitta bo'lish misolidan ikkita nom: a soni b ga qoldiqsiz bo'linsa, b — a ning bo'luvchisi, a — b ning karralisi. Bo'luvchilarni juftlab qidirish; 1 va sonning o'zi doim bo'luvchi; karrali sonlar cheksiz, bo'luvchilar sanoqli.",
    Component: lazy(() => import('../components/grade6/Dars01.jsx')),
  },
  {
    slug: 'dars02-2-5-10-ga-bolinish-alomatlari',
    title: "Dars 2. 2, 5 va 10 ga bo'linish alomatlari",
    desc: "Sonning oxirgi raqamiga qarab uning 2, 5 va 10 ga qoldiqsiz bo'linishini tez aniqlash. Juft va toq sonlarni farqlash hamda bir son uchun bir nechta alomatni birgalikda qo'llash.",
    Component: lazy(() => import('../components/grade6/Dars02.jsx')),
  },
  {
    slug: 'dars03-3-va-9-ga-bolinish-alomatlari',
    title: "Dars 3. 3 va 9 ga bo'linish alomatlari",
    desc: "Son raqamlari yig'indisi orqali 3 va 9 ga bo'linishni tekshirish. 9 ga bo'linadigan sonning 3 ga ham bo'linishi va noma'lum raqamni topish.",
    Component: lazy(() => import('../components/grade6/Dars03.jsx')),
  },
  {
    slug: 'dars04-tub-va-murakkab-sonlar',
    title: 'Dars 4. Tub va murakkab sonlar',
    desc: "Bo'luvchilar soniga qarab tub va murakkab sonlarni ajratish. 1 sonining alohida holati hamda 18 dan 180 gacha bo'lgan sonlarni ustun usulida tub ko'paytuvchilarga ajratish.",
    Component: lazy(() => import('../components/grade6/Dars04.jsx')),
  },
  {
    slug: 'dars05-eng-katta-umumiy-boluvchi',
    title: "Dars 5. Eng katta umumiy bo'luvchi (EKUB)",
    desc: "Ikki sonning umumiy bo'luvchilarini va ularning eng kattasini topish. Ro'yxat hamda tub ko'paytuvchilarga yoyish usullari, o'zaro tub sonlar.",
    Component: lazy(() => import('../components/grade6/Dars05.jsx')),
  },
  {
    slug: 'dars06-eng-kichik-umumiy-karrali',
    title: 'Dars 6. Eng kichik umumiy karrali (EKUK)',
    desc: "Ikki sonning umumiy karrali sonlari ichidan eng kichigini topish. Karrali sonlar qatori, tub ko'paytuvchilarga yoyish va EKUB bilan EKUK orasidagi bog'lanish.",
    Component: lazy(() => import('../components/grade6/Dars06.jsx')),
  },
  {
    slug: 'dars07-kasrning-asosiy-xossasi',
    title: 'Dars 7. Kasrning asosiy xossasi',
    desc: "Kasrning surat va maxrajini bir xil natural songa ko'paytirish yoki umumiy bo'luvchiga bo'lish uning qiymatini o'zgartirmasligi. Teng kasrlar, kasrni kengaytirish va qisqartirish.",
    Component: lazy(() => import('../components/grade6/Dars07.jsx')),
  },
  {
    slug: 'dars08-kasrlarni-qisqartirish',
    title: 'Dars 8. Kasrlarni qisqartirish',
    desc: "Kasrning surat va maxrajini bir xil umumiy bo'luvchiga bo'lish. Qisqarmas kasrlar va EKUB yordamida kasrni bir qadamda eng sodda ko'rinishga keltirish.",
    Component: lazy(() => import('../components/grade6/Dars08.jsx')),
  },
  {
    slug: 'dars09-kasrlarni-umumiy-maxrajga-keltirish',
    title: 'Dars 9. Kasrlarni umumiy maxrajga keltirish',
    desc: "Maxrajlarning EKUKini topish, qo'shimcha ko'paytuvchilarni aniqlash va kasrlarni qiymatini o'zgartirmasdan eng kichik umumiy maxrajda yozish.",
    Component: lazy(() => import('../components/grade6/Dars09.jsx')),
  },
  {
    slug: 'dars10-har-xil-maxrajli-kasrlarni-qoshish-va-ayirish',
    title: "Dars 10. Har xil maxrajli kasrlarni qo'shish va ayirish",
    desc: "Kasrlarni eng kichik umumiy maxrajga keltirish, suratlarni qo'shish yoki ayirish va yakuniy javobni qisqartirish.",
    Component: lazy(() => import('../components/grade6/Dars10.jsx')),
  },
  {
    slug: 'dars11-oddiy-kasrlarni-kopaytirish',
    title: "Dars 11. Oddiy kasrlarni ko'paytirish",
    desc: "Suratlarni va maxrajlarni o'zaro ko'paytirish, ko'paytirishdan oldin qisqartirish hamda sonning kasr qismini topish.",
    Component: lazy(() => import('../components/grade6/Dars11.jsx')),
  },
  {
    slug: 'dars12-oddiy-kasrlarni-bolish',
    title: "Dars 12. Oddiy kasrlarni bo'lish",
    desc: "Bo'lishni teskari kasrga ko'paytirish bilan almashtirish, butun son qatnashgan misollar va natijani ko'paytirish orqali tekshirish.",
    Component: lazy(() => import('../components/grade6/Dars12.jsx')),
  },
  {
    slug: 'dars13-ozaro-teskari-sonlar-va-sonni-qismiga-kora-topish',
    title: "Dars 13. O'zaro teskari sonlar va sonni qismiga ko'ra topish",
    desc: "Ko'paytmasi 1 bo'lgan o'zaro teskari sonlar, nolning alohida holati va ma'lum kasr qismi orqali butun sonni topish.",
    Component: lazy(() => import('../components/grade6/Dars13.jsx')),
  },
  {
    slug: 'dars14-onli-kasrlarni-kopaytirish-va-bolish',
    title: "Dars 14. O'nli kasrlarni ko'paytirish va bo'lish",
    desc: "O'nli kasrlarni ko'paytirish va bo'lish algoritmlari, 10, 100 va 1000 bilan amallarda vergulni to'g'ri siljitish.",
    Component: lazy(() => import('../components/grade6/Dars14.jsx')),
  },
  {
    slug: 'dars15-davriy-onli-kasrlar-va-yaxlitlash',
    title: "Dars 15. Davriy o'nli kasrlar va yaxlitlash",
    desc: "Tugaydigan va davriy o'nli kasrlarni ajratish, davrni qavsda yozish hamda sonlarni o'ndan birlar va yuzdan birlargacha yaxlitlash.",
    Component: lazy(() => import('../components/grade6/Dars15.jsx')),
  },
  {
    slug: 'dars16-kasrlar-va-onli-kasrlarga-oid-masalalar',
    title: "Dars 16. Kasrlar va o'nli kasrlarga oid masalalar",
    desc: "Kasr va o'nli kasrlarni bitta qulay ko'rinishga keltirib, xarid, retsept, masofa va budjetga oid masalalarni bosqichma-bosqich yechish.",
    Component: lazy(() => import('../components/grade6/Dars16.jsx')),
  },
  {
    slug: 'dars17-nisbat',
    title: 'Dars 17. Nisbat',
    desc: "Ikki miqdorni nisbat bilan taqqoslash, nisbatdagi tartibni saqlash, nisbatni soddalashtirish hamda qismning qismga va butunga nisbatini farqlash.",
    Component: lazy(() => import('../components/grade6/Dars17.jsx')),
  },
  {
    slug: 'dars18-proporsiya',
    title: 'Dars 18. Proporsiya',
    desc: "Ikki nisbat tengligini proporsiya sifatida yozish, chetki va o'rta hadlar ko'paytmasi orqali tekshirish hamda noma'lum hadni topish.",
    Component: lazy(() => import('../components/grade6/Dars18.jsx')),
  },
  {
    slug: 'dars19-togri-va-teskari-proporsional-miqdorlar',
    title: "Dars 19. To'g'ri va teskari proporsional miqdorlar",
    desc: "Miqdorlarning bir yo'nalishda yoki qarama-qarshi yo'nalishda o'zgarishini hayotiy misollar, jadval va formulalar yordamida farqlash.",
    Component: lazy(() => import('../components/grade6/Dars19.jsx')),
  },
  {
    slug: 'dars20-masshtab',
    title: 'Dars 20. Masshtab',
    desc: "1 : n masshtabning ma'nosi, uzunlik birliklarini birxillashtirish, xaritadagi va haqiqiy masofani ikki asosiy formula bilan topish.",
    Component: lazy(() => import('../components/grade6/Dars20.jsx')),
  },
  {
    slug: 'dars21-foizlar',
    title: 'Dars 21. Foizlar',
    desc: "Foizni yuzdan bir ulush sifatida tushunish, oddiy va o'nli kasrlarga aylantirish, sonning foizini va bir son ikkinchisining necha foizi ekanini topish.",
    Component: lazy(() => import('../components/grade6/Dars21.jsx')),
  },
  {
    slug: 'dars22-foizga-oid-masalalar',
    title: 'Dars 22. Foizga oid masalalar',
    desc: "Qism, foiz va butunni topish formulalari; chegirma, narx oshishi hamda ketma-ket foiz o'zgarishlariga oid hayotiy masalalar.",
    Component: lazy(() => import('../components/grade6/Dars22.jsx')),
  },
  {
    slug: 'dars23-proporsiyaga-oid-masalalar',
    title: 'Dars 23. Proporsiyaga oid masalalar',
    desc: "Masaladagi bog'lanish turini aniqlash, jadval va proporsiya tuzish hamda xarid, ish, retsept va yoqilg'i masalalarini tekshirib yechish.",
    Component: lazy(() => import('../components/grade6/Dars23.jsx')),
  },
  {
    slug: 'dars24-koordinata-togri-chizigi',
    title: "Dars 24. Koordinata to'g'ri chizig'i",
    desc: "Sanoq boshi, birlik kesma, musbat va manfiy yo'nalishlar, nuqta koordinatasi, qarama-qarshi sonlar va chiziqdagi siljish.",
    Component: lazy(() => import('../components/grade6/Dars24.jsx')),
  },
  {
    slug: 'dars25-sonning-moduli',
    title: 'Dars 25. Sonning moduli',
    desc: "Modulni sonning noldan masofasi sifatida tushunish, modulli ifodalar va sodda tenglamalar hamda ikki nuqta orasidagi masofani topish.",
    Component: lazy(() => import('../components/grade6/Dars25.jsx')),
  },
  {
    slug: 'dars26-ratsional-sonlarni-taqqoslash',
    title: 'Dars 26. Ratsional sonlarni taqqoslash',
    desc: "Musbat va manfiy butun sonlar, oddiy va o'nli kasrlarni koordinata chizig'i hamda modul orqali taqqoslash va o'sish tartibida joylashtirish.",
    Component: lazy(() => import('../components/grade6/Dars26.jsx')),
  },
  {
    slug: 'dars27-ratsional-sonlarni-qoshish',
    title: "Dars 27. Ratsional sonlarni qo'shish",
    desc: "Bir xil va har xil ishorali sonlarni koordinata chizig'i, modul va hayotiy harorat hamda hisob misollari yordamida qo'shish.",
    Component: lazy(() => import('../components/grade6/Dars27.jsx')),
  },
  {
    slug: 'dars28-ratsional-sonlarni-ayirish',
    title: 'Dars 28. Ratsional sonlarni ayirish',
    desc: "Ayirishni qarama-qarshi sonni qo'shishga aylantirish, ikki minus qoidasini tushunish va koordinatalar orasidagi masofani topish.",
    Component: lazy(() => import('../components/grade6/Dars28.jsx')),
  },
  {
    slug: 'dars29-ratsional-sonlarni-kopaytirish-va-bolish',
    title: "Dars 29. Ratsional sonlarni ko'paytirish va bo'lish",
    desc: "Ishoralar jadvali, modullar, kasrli ratsional sonlar va amallar tartibi orqali ko'paytirish hamda bo'lish.",
    Component: lazy(() => import('../components/grade6/Dars29.jsx')),
  },
  {
    slug: 'dars30-koordinata-tekisligi',
    title: 'Dars 30. Koordinata tekisligi',
    desc: "x va y o'qlari, koordinatalar tartibi, to'rtta chorak, o'qlardagi nuqtalar va gorizontal hamda vertikal masofalar.",
    Component: lazy(() => import('../components/grade6/Dars30.jsx')),
  },
  {
    slug: 'dars31-harfli-ifodalar',
    title: 'Dars 31. Harfli ifodalar',
    desc: "O'zgaruvchi, koeffitsiyent, ifoda qiymati va perimetr, yo'l hamda xaridga oid formulalarni harflar bilan yozish.",
    Component: lazy(() => import('../components/grade6/Dars31.jsx')),
  },
  {
    slug: 'dars32-qavslarni-ochish',
    title: 'Dars 32. Qavslarni ochish',
    desc: "Taqsimot qonuni, qavs oldidagi plus va minus, manfiy ko'paytuvchi hamda umumiy ko'paytuvchini qavs tashqarisiga chiqarish.",
    Component: lazy(() => import('../components/grade6/Dars32.jsx')),
  },
  {
    slug: 'dars33-oxshash-hadlarni-ixchamlash',
    title: "Dars 33. O'xshash hadlarni ixchamlash",
    desc: "Bir xil harfli qismlarni aniqlash, koeffitsiyentlarni qo'shish yoki ayirish va qavsli ifodalarni bosqichma-bosqich soddalashtirish.",
    Component: lazy(() => import('../components/grade6/Dars33.jsx')),
  },
  {
    slug: 'dars34-chiziqli-tenglamalar',
    title: 'Dars 34. Chiziqli tenglamalar',
    desc: "Tenglik muvozanati, bir va ikki bosqichli tenglamalar, qavsli hamda noma'lum ikki tomonda qatnashgan tenglamalarni yechish.",
    Component: lazy(() => import('../components/grade6/Dars34.jsx')),
  },
  {
    slug: 'dars35-tenglama-yordamida-masalalar-yechish',
    title: 'Dars 35. Tenglama yordamida masalalar yechish',
    desc: "Masala shartidan noma'lum va ifodalarni tanlash, tenglama tuzish, yechimni shartga qaytarish va mazmunan tekshirish.",
    Component: lazy(() => import('../components/grade6/Dars35.jsx')),
  },
  {
    slug: 'dars36-iqtisodiy-va-ishga-oid-masalalar',
    title: 'Dars 36. Iqtisodiy va ishga oid masalalar',
    desc: "Narx, miqdor, jami qiymat, chegirma, foyda, ish unumdorligi va birgalikdagi ish formulalari asosidagi masalalar.",
    Component: lazy(() => import('../components/grade6/Dars36.jsx')),
  },
  {
    slug: 'dars37-aylana-va-doira',
    title: 'Dars 37. Aylana va doira',
    desc: "Aylana bilan doira farqi, markaz, radius, diametr, vatar, yoy va nuqtaning doiraga nisbatan joylashuvi.",
    Component: lazy(() => import('../components/grade6/Dars37.jsx')),
  },
  {
    slug: 'dars38-aylana-uzunligi',
    title: 'Dars 38. Aylana uzunligi',
    desc: "π sonining ma'nosi, C=πd=2πr formulalari, teskari hisoblar, yarim aylana va g'ildirak aylanishiga oid masalalar.",
    Component: lazy(() => import('../components/grade6/Dars38.jsx')),
  },
  {
    slug: 'dars39-doira-yuzi',
    title: 'Dars 39. Doira yuzi',
    desc: "S=πr² formulasi, radius kvadrati, diametrdan yuza, yarim va chorak doira hamda halqa yuzini hisoblash.",
    Component: lazy(() => import('../components/grade6/Dars39.jsx')),
  },
  {
    slug: 'dars40-oq-simmetriyasi',
    title: "Dars 40. O'q simmetriyasi",
    desc: "Ko'zgu o'qi, aks nuqtalarning teng masofasi, shaklni akslantirish, simmetriya o'qlari va koordinatalardagi qoidalar.",
    Component: lazy(() => import('../components/grade6/Dars40.jsx')),
  },
  {
    slug: 'dars41-markaziy-simmetriya',
    title: 'Dars 41. Markaziy simmetriya',
    desc: "Simmetriya markazi, 180 daraja burilish, o'rta nuqta xossasi va sanoq boshiga nisbatan koordinatalarni akslantirish.",
    Component: lazy(() => import('../components/grade6/Dars41.jsx')),
  },
  {
    slug: 'dars42-uchburchak-elementlari-turlari-va-perimetri',
    title: 'Dars 42. Uchburchak: elementlari, turlari va perimetri',
    desc: "Uchlar, tomonlar, burchaklar, 180 daraja xossasi, tomon va burchak bo'yicha turlar, perimetr va uchburchak tengsizligi.",
    Component: lazy(() => import('../components/grade6/Dars42.jsx')),
  },
  {
    slug: 'dars43-uchburchak-va-murakkab-shakllar-yuzi',
    title: 'Dars 43. Uchburchak va murakkab shakllar yuzi',
    desc: "Asos, balandlik, S=ah/2 formulasi, katakli shakllar va murakkab yuzalarni qismlarga ajratish yoki ayirish usuli.",
    Component: lazy(() => import('../components/grade6/Dars43.jsx')),
  },
  {
    slug: 'dars44-fazoviy-shakllar-hajmi-va-olchov-birliklari',
    title: "Dars 44. Fazoviy shakllar hajmi va o'lchov birliklari",
    desc: "Kub va to'g'ri burchakli parallelepiped hajmi, kub birliklar, dm³ va cm³ aylantirish hamda litr bilan bog'lanish.",
    Component: lazy(() => import('../components/grade6/Dars44.jsx')),
  },
  {
    slug: 'dars45-malumotlar-bilan-ishlash',
    title: "Dars 45. Ma'lumotlar bilan ishlash",
    desc: "Jadval va diagrammalarni o'qish, moda, mediana, o'rtacha arifmetik, o'zgarish kengligi va ma'lumotdan xulosa chiqarish.",
    Component: lazy(() => import('../components/grade6/Dars45.jsx')),
  },
  {
    slug: 'dars46-geometriya-va-malumotlar-bolimi-yakuni',
    title: "Dars 46. Geometriya va ma'lumotlar bo'limi yakuni",
    desc: "Aylana, doira, simmetriya, uchburchak, yuza, hajm va ma'lumotlar tahlili formulalarini tizimli takrorlash.",
    Component: lazy(() => import('../components/grade6/Dars46.jsx')),
  },
]

// 6-sinf AMALIY darslari.
export const grade6Amaliy = [
  {
    slug: 'dars01-boluvchilar-va-karrali-sonlar-amaliyot',
    title: "Dars 1 amaliyoti. Bo'luvchilar va karrali sonlar",
    desc: "10 ta variantli, ha yoki yo'q hamda moslashtirish topshirig'i.",
    Component: lazy(() => import('../components/grade6/practice/Dars01Practice.jsx')),
  },
  {
    slug: 'dars02-2-5-10-ga-bolinish-alomatlari-amaliyot',
    title: "Dars 2 amaliyoti. 2, 5 va 10 ga bo'linish alomatlari",
    desc: "10 ta variantli, ha yoki yo'q hamda moslashtirish topshirig'i.",
    Component: lazy(() => import('../components/grade6/practice/Dars02Practice.jsx')),
  },
  {
    slug: 'dars03-3-va-9-ga-bolinish-alomatlari-amaliyot',
    title: "Dars 3 amaliyoti. 3 va 9 ga bo'linish alomatlari",
    desc: "10 ta variantli, ha yoki yo'q hamda moslashtirish topshirig'i.",
    Component: lazy(() => import('../components/grade6/practice/Dars03Practice.jsx')),
  },
  {
    slug: 'dars04-tub-va-murakkab-sonlar-amaliyot',
    title: "Dars 4 amaliyoti. Tub va murakkab sonlar",
    desc: "10 ta variantli, ha yoki yo'q hamda moslashtirish topshirig'i.",
    Component: lazy(() => import('../components/grade6/practice/Dars04Practice.jsx')),
  },
  {
    slug: 'dars05-eng-katta-umumiy-boluvchi-amaliyot',
    title: "Dars 5 amaliyoti. Eng katta umumiy bo'luvchi",
    desc: "10 ta variantli, ha yoki yo'q hamda moslashtirish topshirig'i.",
    Component: lazy(() => import('../components/grade6/practice/Dars05Practice.jsx')),
  },
  {
    slug: 'dars06-eng-kichik-umumiy-karrali-amaliyot',
    title: "Dars 6 amaliyoti. Eng kichik umumiy karrali",
    desc: "10 ta variantli, ha yoki yo'q hamda moslashtirish topshirig'i.",
    Component: lazy(() => import('../components/grade6/practice/Dars06Practice.jsx')),
  },
  {
    slug: 'dars07-kasrning-asosiy-xossasi-amaliyot',
    title: "Dars 7 amaliyoti. Kasrning asosiy xossasi",
    desc: "Kasrni kengaytirish, qisqartirish va teng kasrlarni aniqlashga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars07Practice.jsx')),
  },
  {
    slug: 'dars08-kasrlarni-qisqartirish-amaliyot',
    title: "Dars 8 amaliyoti. Kasrlarni qisqartirish",
    desc: "Kasrlarni umumiy bo'luvchi va EKUB yordamida qisqartirishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars08Practice.jsx')),
  },
  {
    slug: 'dars09-kasrlarni-umumiy-maxrajga-keltirish-amaliyot',
    title: "Dars 9 amaliyoti. Kasrlarni umumiy maxrajga keltirish",
    desc: "Eng kichik umumiy maxraj va qo'shimcha ko'paytuvchilarga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars09Practice.jsx')),
  },
  {
    slug: 'dars10-har-xil-maxrajli-kasrlarni-qoshish-va-ayirish-amaliyot',
    title: "Dars 10 amaliyoti. Har xil maxrajli kasrlarni qo'shish va ayirish",
    desc: "Har xil maxrajli kasrlarni qo'shish, ayirish va javobni qisqartirishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars10Practice.jsx')),
  },
  {
    slug: 'dars11-oddiy-kasrlarni-kopaytirish-amaliyot',
    title: "Dars 11 amaliyoti. Oddiy kasrlarni ko'paytirish",
    desc: "Kasrlarni ko'paytirish, oldindan qisqartirish va sonning kasr qismini topishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars11Practice.jsx')),
  },
  {
    slug: 'dars12-oddiy-kasrlarni-bolish-amaliyot',
    title: "Dars 12 amaliyoti. Oddiy kasrlarni bo'lish",
    desc: "Bo'lishni teskari kasrga ko'paytirish bilan almashtirishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars12Practice.jsx')),
  },
  {
    slug: 'dars13-ozaro-teskari-sonlar-va-sonni-qismiga-kora-topish-amaliyot',
    title: "Dars 13 amaliyoti. O'zaro teskari sonlar va sonni qismiga ko'ra topish",
    desc: "O'zaro teskari sonlar va ma'lum kasr qismi orqali butun sonni topishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars13Practice.jsx')),
  },
  {
    slug: 'dars14-onli-kasrlarni-kopaytirish-va-bolish-amaliyot',
    title: "Dars 14 amaliyoti. O'nli kasrlarni ko'paytirish va bo'lish",
    desc: "O'nli kasrlar bilan amallar va vergulni to'g'ri siljitishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars14Practice.jsx')),
  },
  {
    slug: 'dars15-davriy-onli-kasrlar-va-yaxlitlash-amaliyot',
    title: "Dars 15 amaliyoti. Davriy o'nli kasrlar va yaxlitlash",
    desc: "Davriy o'nli kasrlarni aniqlash va sonlarni kerakli xonagacha yaxlitlashga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars15Practice.jsx')),
  },
  {
    slug: 'dars16-kasrlar-va-onli-kasrlarga-oid-masalalar-amaliyot',
    title: "Dars 16 amaliyoti. Kasrlar va o'nli kasrlarga oid masalalar",
    desc: "Kasr va o'nli kasr qatnashgan hayotiy masalalarga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars16Practice.jsx')),
  },
  {
    slug: 'dars17-nisbat-amaliyot',
    title: 'Dars 17 amaliyoti. Nisbat',
    desc: "Nisbatni yozish, soddalashtirish va nisbatda taqsimlashga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars17Practice.jsx')),
  },
  {
    slug: 'dars18-proporsiya-amaliyot',
    title: 'Dars 18 amaliyoti. Proporsiya',
    desc: "Proporsiyani tekshirish va noma'lum hadni topishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars18Practice.jsx')),
  },
  {
    slug: 'dars19-togri-va-teskari-proporsional-miqdorlar-amaliyot',
    title: "Dars 19 amaliyoti. To'g'ri va teskari proporsional miqdorlar",
    desc: "To'g'ri va teskari proporsional bog'lanishlarga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars19Practice.jsx')),
  },
  {
    slug: 'dars20-masshtab-amaliyot',
    title: 'Dars 20 amaliyoti. Masshtab',
    desc: "Xarita, reja va haqiqiy masofani masshtab orqali topishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars20Practice.jsx')),
  },
  {
    slug: 'dars21-foizlar-amaliyot',
    title: 'Dars 21 amaliyoti. Foizlar',
    desc: "Foizni kasrga aylantirish, sonning foizini va qismning foizini topishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars21Practice.jsx')),
  },
  {
    slug: 'dars22-foizga-oid-masalalar-amaliyot',
    title: 'Dars 22 amaliyoti. Foizga oid masalalar',
    desc: "Chegirma, narx oshishi va ketma-ket foiz o'zgarishlariga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars22Practice.jsx')),
  },
  {
    slug: 'dars23-proporsiyaga-oid-masalalar-amaliyot',
    title: 'Dars 23 amaliyoti. Proporsiyaga oid masalalar',
    desc: "Xarid, ish, retsept va sarf masalalarini proporsiya bilan yechishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars23Practice.jsx')),
  },
  {
    slug: 'dars24-koordinata-togri-chizigi-amaliyot',
    title: "Dars 24 amaliyoti. Koordinata to'g'ri chizig'i",
    desc: "Nuqta koordinatasi, siljish va nuqtalar orasidagi masofaga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars24Practice.jsx')),
  },
  {
    slug: 'dars25-sonning-moduli-amaliyot',
    title: 'Dars 25 amaliyoti. Sonning moduli',
    desc: "Modul, modulli ifoda, tenglama va nuqtalar orasidagi masofaga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars25Practice.jsx')),
  },
  {
    slug: 'dars26-ratsional-sonlarni-taqqoslash-amaliyot',
    title: 'Dars 26 amaliyoti. Ratsional sonlarni taqqoslash',
    desc: "Ratsional sonlarni taqqoslash va tartib bilan joylashtirishga oid 10 ta interaktiv topshiriq.",
    Component: lazy(() => import('../components/grade6/practice/Dars26Practice.jsx')),
  },
  { slug: 'dars27-ratsional-sonlarni-qoshish-amaliyot', title: "Dars 27 amaliyoti. Ratsional sonlarni qo'shish", desc: "Ratsional sonlarni qo'shishga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars27Practice.jsx')) },
  { slug: 'dars28-ratsional-sonlarni-ayirish-amaliyot', title: 'Dars 28 amaliyoti. Ratsional sonlarni ayirish', desc: "Ratsional sonlarni ayirishga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars28Practice.jsx')) },
  { slug: 'dars29-ratsional-sonlarni-kopaytirish-va-bolish-amaliyot', title: "Dars 29 amaliyoti. Ratsional sonlarni ko'paytirish va bo'lish", desc: "Ratsional sonlarni ko'paytirish va bo'lishga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars29Practice.jsx')) },
  { slug: 'dars30-koordinata-tekisligi-amaliyot', title: 'Dars 30 amaliyoti. Koordinata tekisligi', desc: "Koordinata tekisligiga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars30Practice.jsx')) },
  { slug: 'dars31-harfli-ifodalar-amaliyot', title: 'Dars 31 amaliyoti. Harfli ifodalar', desc: "Harfli ifodalarga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars31Practice.jsx')) },
  { slug: 'dars32-qavslarni-ochish-amaliyot', title: 'Dars 32 amaliyoti. Qavslarni ochish', desc: "Qavslarni ochishga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars32Practice.jsx')) },
  { slug: 'dars33-oxshash-hadlarni-ixchamlash-amaliyot', title: "Dars 33 amaliyoti. O'xshash hadlarni ixchamlash", desc: "O'xshash hadlarni ixchamlashga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars33Practice.jsx')) },
  { slug: 'dars34-chiziqli-tenglamalar-amaliyot', title: 'Dars 34 amaliyoti. Chiziqli tenglamalar', desc: "Chiziqli tenglamalarga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars34Practice.jsx')) },
  { slug: 'dars35-tenglama-yordamida-masalalar-amaliyot', title: 'Dars 35 amaliyoti. Tenglama yordamida masalalar yechish', desc: "Tenglama yordamida masalalar yechishga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars35Practice.jsx')) },
  { slug: 'dars36-iqtisodiy-va-ish-masalalari-amaliyot', title: 'Dars 36 amaliyoti. Iqtisodiy va ishga oid masalalar', desc: "Iqtisodiy va ish masalalariga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars36Practice.jsx')) },
  { slug: 'dars37-aylana-va-doira-amaliyot', title: 'Dars 37 amaliyoti. Aylana va doira', desc: "Aylana va doiraga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars37Practice.jsx')) },
  { slug: 'dars38-aylana-uzunligi-amaliyot', title: 'Dars 38 amaliyoti. Aylana uzunligi', desc: "Aylana uzunligiga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars38Practice.jsx')) },
  { slug: 'dars39-doira-yuzi-amaliyot', title: 'Dars 39 amaliyoti. Doira yuzi', desc: "Doira yuziga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars39Practice.jsx')) },
  { slug: 'dars40-oq-simmetriyasi-amaliyot', title: "Dars 40 amaliyoti. O'q simmetriyasi", desc: "O'q simmetriyasiga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars40Practice.jsx')) },
  { slug: 'dars41-markaziy-simmetriya-amaliyot', title: 'Dars 41 amaliyoti. Markaziy simmetriya', desc: "Markaziy simmetriyaga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars41Practice.jsx')) },
  { slug: 'dars42-uchburchak-amaliyot', title: 'Dars 42 amaliyoti. Uchburchak elementlari, turlari va perimetri', desc: "Uchburchaklarga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars42Practice.jsx')) },
  { slug: 'dars43-uchburchak-va-murakkab-shakllar-yuzi-amaliyot', title: 'Dars 43 amaliyoti. Uchburchak va murakkab shakllar yuzi', desc: "Shakllar yuziga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars43Practice.jsx')) },
  { slug: 'dars44-fazoviy-shakllar-hajmi-amaliyot', title: "Dars 44 amaliyoti. Fazoviy shakllar hajmi va o'lchov birliklari", desc: "Hajm va o'lchov birliklariga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars44Practice.jsx')) },
  { slug: 'dars45-malumotlar-bilan-ishlash-amaliyot', title: "Dars 45 amaliyoti. Ma'lumotlar bilan ishlash", desc: "Ma'lumotlar bilan ishlashga oid 10 ta interaktiv topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars45Practice.jsx')) },
  { slug: 'dars46-geometriya-va-malumotlar-yakuni-amaliyot', title: "Dars 46 amaliyoti. Geometriya va ma'lumotlar bo'limi yakuni", desc: "Geometriya va ma'lumotlar bo'limiga oid 10 ta yakuniy topshiriq.", Component: lazy(() => import('../components/grade6/practice/Dars46Practice.jsx')) },
]
