const choice = (prompt, promptRu, options, answer, explanation, explanationRu) => ({
  type: 'choice', prompt, promptRu, options, answer, explanation, explanationRu,
});
const input = (prompt, promptRu, answer, explanation, explanationRu) => ({
  type: 'input', prompt, promptRu, answer: String(answer), explanation, explanationRu,
});
const match = (prompt, promptRu, left, right, pairs, explanation, explanationRu) => ({
  type: 'match', prompt, promptRu, left, right, pairs, explanation, explanationRu,
});
const bool = (prompt, promptRu, answer, explanation, explanationRu) => ({
  type: 'bool', prompt, promptRu, options: ["Ha", "Yo'q"], answer: answer ? "Ha" : "Yo'q",
  explanation, explanationRu,
});

const L = (title, titleRu, topic, items) => ({
  title: `Dars ${title} amaliyoti. ${topic}`,
  titleRu: `Практика к уроку ${title}. ${titleRu}`,
  topic,
  topicRu: titleRu,
  items: items.map(item => ({ ...item, topicRu: titleRu })),
});

const lessons = {
  27: L(27, 'Сложение рациональных чисел', "Ratsional sonlarni qo'shish", [
    choice("Bir xil ishorali −7 va −5 sonlarini qo‘shib, natijani tanlang.", 'Сложите числа −7 и −5 с одинаковыми знаками и выберите результат.', ['−2', '2', '−12', '12'], '−12', 'Modullar 7 + 5 = 12, ikkala son manfiy bo‘lgani uchun javob −12.', 'Модули дают 7 + 5 = 12; оба числа отрицательные, поэтому ответ −12.'),
    input("−14 + 9 yig‘indini hisoblab, javobni yozing.", 'Вычислите сумму −14 + 9 и запишите ответ.', -5, 'Modullar ayirmasi 14 − 9 = 5; katta modul manfiy songa tegishli, demak −5.', 'Разность модулей 14 − 9 = 5; больший модуль у отрицательного числа, значит −5.'),
    match("Har bir yig‘indini uning qiymati bilan moslashtiring.", 'Соедините каждую сумму с её значением.', ['−6 + (−8)', '−11 + 15', '13 + (−7)'], ['−14', '4', '6'], [0, 1, 2], 'Bir xil ishoralarda modullar qo‘shiladi, har xil ishoralarda kichik modul kattasidan ayriladi.', 'При одинаковых знаках модули складывают, при разных — меньший модуль вычитают из большего.'),
    choice("Harorat −3 °C edi va 8 °C ga ko‘tarildi. Yangi haroratni toping.", 'Температура была −3 °C и повысилась на 8 °C. Найдите новую температуру.', ['−11 °C', '−5 °C', '5 °C', '11 °C'], '5 °C', '−3 + 8 = 5, shuning uchun yangi harorat 5 °C.', '−3 + 8 = 5, поэтому новая температура равна 5 °C.'),
    bool("Qarama-qarshi 18 va −18 sonlarining yig‘indisi nolga teng.", 'Сумма противоположных чисел 18 и −18 равна нулю.', true, 'Qarama-qarshi sonlar modullari teng, ishoralari turlicha; ularning yig‘indisi 0.', 'У противоположных чисел равные модули и разные знаки, поэтому их сумма равна 0.'),
    match("Hisoblashlarni to‘g‘ri javoblari bilan bog‘lang.", 'Соедините вычисления с правильными ответами.', ['−2,5 + 1,2', '3,7 + (−5,1)', '−4,6 + (−2,3)'], ['−1,3', '−1,4', '−6,9'], [0, 1, 2], 'Har bir ifodada ishoralar qoidasi qo‘llanadi: natijalar −1,3; −1,4 va −6,9.', 'По правилу знаков получаем соответственно −1,3; −1,4 и −6,9.'),
    choice("−3/4 + 1/2 yig‘indini umumiy maxrajga keltirib hisoblang.", 'Приведите к общему знаменателю и вычислите −3/4 + 1/2.', ['−1/4', '1/4', '−5/4', '5/4'], '−1/4', '1/2 = 2/4, demak −3/4 + 2/4 = −1/4.', '1/2 = 2/4, поэтому −3/4 + 2/4 = −1/4.'),
    input("−27 + 35 + (−6) ifodaning qiymatini yozing.", 'Вычислите −27 + 35 + (−6) и запишите ответ.', 2, '−27 + 35 = 8, so‘ng 8 − 6 = 2.', '−27 + 35 = 8, затем 8 − 6 = 2.'),
    match("Yig‘indilarni natijalari bilan moslashtiring.", 'Соедините суммы с их результатами.', ['−1/3 + 5/6', '−7/10 + 1/5', '2/9 + (−8/9)'], ['1/2', '−1/2', '−2/3'], [0, 1, 2], 'Umumiy maxrajga keltirilganda javoblar 1/2, −1/2 va −2/3 bo‘ladi.', 'После приведения к общему знаменателю получаем 1/2, −1/2 и −2/3.'),
    choice("Hisob raqamida −125 ming so‘m qarz bor edi, unga 80 ming so‘m tushdi. Yangi holatni toping.", 'На счёте был долг 125 тысяч сумов, затем поступило 80 тысяч. Найдите новое состояние счёта.', ['−205 ming', '−45 ming', '45 ming', '205 ming'], '−45 ming', '−125 + 80 = −45. Hisobda 45 ming so‘m qarz qoladi.', '−125 + 80 = −45. На счёте остаётся долг 45 тысяч сумов.'),
  ]),
  28: L(28, 'Вычитание рациональных чисел', 'Ratsional sonlarni ayirish', [
    choice("9 − (−4) ayirmani qo‘shishga aylantirib hisoblang.", 'Замените вычитание сложением и вычислите 9 − (−4).', ['5', '−5', '13', '−13'], '13', 'Manfiy sonni ayirish unga qarama-qarshi musbat sonni qo‘shishdir: 9 + 4 = 13.', 'Вычесть отрицательное число — значит прибавить положительное: 9 + 4 = 13.'),
    input("−8 − 7 ayirmaning qiymatini yozing.", 'Запишите значение разности −8 − 7.', -15, '−8 − 7 = −8 + (−7) = −15.', '−8 − 7 = −8 + (−7) = −15.'),
    match("Ayirmalarni javoblari bilan moslashtiring.", 'Соедините разности с ответами.', ['12 − 19', '−6 − (−10)', '−15 − 3'], ['−7', '4', '−18'], [0, 1, 2], 'Ayirish qarama-qarshi sonni qo‘shish bilan almashtiriladi.', 'Вычитание заменяется сложением противоположного числа.'),
    choice("Ertalab 6 °C, kechasi −2 °C bo‘ldi. Harorat necha darajaga pasaydi?", 'Утром было 6 °C, ночью стало −2 °C. На сколько градусов понизилась температура?', ['4 °C', '6 °C', '8 °C', '10 °C'], '8 °C', 'Pasayish miqdori 6 − (−2) = 8 °C.', 'Величина понижения: 6 − (−2) = 8 °C.'),
    bool("−5 − (−9) ifodaning qiymati 4 ga teng.", 'Значение выражения −5 − (−9) равно 4.', true, '−5 − (−9) = −5 + 9 = 4.', '−5 − (−9) = −5 + 9 = 4.'),
    match("O‘nli sonli ayirmalarni natijalar bilan bog‘lang.", 'Соедините разности десятичных чисел с результатами.', ['2,4 − 5,9', '−1,7 − (−3,2)', '−4,8 − 2,6'], ['−3,5', '1,5', '−7,4'], [0, 1, 2], 'Qarama-qarshi sonni qo‘shish qoidasi natijalarni to‘g‘ri beradi.', 'Правило прибавления противоположного числа даёт эти результаты.'),
    choice("5/6 − (−1/3) ayirmani hisoblang.", 'Вычислите разность 5/6 − (−1/3).', ['1/2', '7/6', '−7/6', '3/6'], '7/6', '5/6 − (−1/3) = 5/6 + 2/6 = 7/6.', '5/6 − (−1/3) = 5/6 + 2/6 = 7/6.'),
    input("−20 − (−7) − 5 ifodaning qiymatini yozing.", 'Вычислите −20 − (−7) − 5 и запишите ответ.', -18, '−20 + 7 − 5 = −13 − 5 = −18.', '−20 + 7 − 5 = −13 − 5 = −18.'),
    match("Har bir ayirmani mos qiymat bilan juftlang.", 'Соедините каждую разность с её значением.', ['−2/5 − 1/10', '3/4 − (−1/8)', '−5/6 − (−1/2)'], ['−1/2', '7/8', '−1/3'], [0, 1, 2], 'Umumiy maxrajdan foydalanib −1/2, 7/8 va −1/3 olinadi.', 'После приведения к общему знаменателю получаем −1/2, 7/8 и −1/3.'),
    choice("Suv sathi 3 metr edi, keyin 7 metr pasaydi. Yangi sathni toping.", 'Уровень воды был 3 метра, затем понизился на 7 метров. Найдите новый уровень.', ['10 m', '4 m', '−4 m', '−10 m'], '−4 m', 'Boshlang‘ich sathdan pasayishni ayiramiz: 3 − 7 = −4 metr.', 'Из начального уровня вычитаем понижение: 3 − 7 = −4 метра.'),
  ]),
  29: L(29, 'Умножение и деление рациональных чисел', "Ratsional sonlarni ko'paytirish va bo'lish", [
    choice("−6 · 7 ko‘paytmaning ishorasi va qiymatini toping.", 'Найдите знак и значение произведения −6 · 7.', ['−42', '42', '−13', '13'], '−42', 'Har xil ishorali sonlar ko‘paytmasi manfiy: 6 · 7 = 42, javob −42.', 'Произведение чисел с разными знаками отрицательно: 6 · 7 = 42, ответ −42.'),
    input("−72 : (−9) bo‘linmaning qiymatini yozing.", 'Запишите значение частного −72 : (−9).', 8, 'Bir xil ishorali sonlar bo‘linmasi musbat: 72 : 9 = 8.', 'Частное чисел с одинаковыми знаками положительно: 72 : 9 = 8.'),
    match("Amallarni natijalari bilan moslashtiring.", 'Соедините действия с результатами.', ['−8 · (−5)', '54 : (−6)', '−3 · 11'], ['40', '−9', '−33'], [0, 1, 2], 'Bir xil ishora musbat, har xil ishora manfiy natija beradi.', 'Одинаковые знаки дают плюс, разные — минус.'),
    choice("−1,5 · 0,8 ko‘paytmani hisoblang.", 'Вычислите произведение −1,5 · 0,8.', ['−1,2', '1,2', '−12', '12'], '−1,2', '15 · 8 = 120; ikki kasr xonasi ajratiladi va ishora manfiy: −1,2.', '15 · 8 = 120; отделяем два знака после запятой и ставим минус: −1,2.'),
    bool("Nolga teng bo‘lmagan har qanday a soni uchun 0 : a = 0.", 'Для любого ненулевого числа a верно равенство 0 : a = 0.', true, 'Nolni nolga teng bo‘lmagan songa bo‘lganda natija 0 bo‘ladi.', 'При делении нуля на ненулевое число получается 0.'),
    match("Kasrli amallarni javoblari bilan bog‘lang.", 'Соедините действия с дробями с ответами.', ['−2/3 · 9/4', '−5/8 : 15/16', '7/10 · (−5/14)'], ['−3/2', '−2/3', '−1/4'], [0, 1, 2], 'Qisqartirib hisoblanganda natijalar −3/2, −2/3 va −1/4 chiqadi.', 'После сокращения получаем −3/2, −2/3 и −1/4.'),
    choice("Uchta manfiy ko‘paytuvchi (−2) · (−3) · (−4) natijasini toping.", 'Найдите значение произведения трёх отрицательных множителей (−2) · (−3) · (−4).', ['−24', '24', '−9', '9'], '−24', 'Manfiy ko‘paytuvchilar soni toq, shuning uchun natija manfiy; 2 · 3 · 4 = 24.', 'Отрицательных множителей нечётное число, поэтому результат отрицательный; 2 · 3 · 4 = 24.'),
    input("−4 · 6 : (−3) ifodaning qiymatini yozing.", 'Вычислите −4 · 6 : (−3) и запишите ответ.', 8, '−4 · 6 = −24, so‘ng −24 : (−3) = 8.', '−4 · 6 = −24, затем −24 : (−3) = 8.'),
    match("Ifodalarni to‘g‘ri qiymatlar bilan juftlang.", 'Соедините выражения с правильными значениями.', ['(−2)⁴', '(−3)³', '−5²'], ['16', '−27', '−25'], [0, 1, 2], 'Juft daraja musbat, toq daraja manfiy; −5² yozuvida minus darajaga kirmaydi.', 'Чётная степень положительна, нечётная отрицательна; в −5² минус не входит в степень.'),
    choice("Bir aksiyaning qiymati har kuni 3 ming so‘mdan kamaydi. 6 kundagi umumiy o‘zgarishni toping.", 'Цена акции ежедневно уменьшалась на 3 тысячи сумов. Найдите общее изменение за 6 дней.', ['−18 ming', '18 ming', '−9 ming', '9 ming'], '−18 ming', 'Kunlik o‘zgarish −3, kunlar soni 6: −3 · 6 = −18 ming.', 'Ежедневное изменение −3, число дней 6: −3 · 6 = −18 тысяч.'),
  ]),
  30: L(30, 'Координатная плоскость', 'Koordinata tekisligi', [
    choice("A(−4; 3) nuqta koordinata tekisligining qaysi choragida joylashgan?", 'В какой четверти координатной плоскости находится точка A(−4; 3)?', ['I chorak', 'II chorak', 'III chorak', 'IV chorak'], 'II chorak', 'x manfiy, y musbat bo‘lsa, nuqta II chorakda yotadi.', 'Если x отрицателен, а y положителен, точка лежит во II четверти.'),
    input("B(5; −7) nuqtaning ordinatasini yozing.", 'Запишите ординату точки B(5; −7).', -7, 'Ordinata koordinatalar juftligidagi ikkinchi son, ya’ni −7.', 'Ордината — второе число в паре координат, то есть −7.'),
    match("Nuqtalarni ular joylashgan chorak bilan moslashtiring.", 'Соедините точки с четвертями, в которых они находятся.', ['P(2; 6)', 'Q(−3; −5)', 'R(4; −1)'], ['I', 'III', 'IV'], [0, 1, 2], 'I: (+;+), III: (−;−), IV: (+;−).', 'I: (+;+), III: (−;−), IV: (+;−).'),
    choice("Qaysi nuqta y o‘qida joylashgan?", 'Какая точка находится на оси y?', ['(3; 0)', '(0; −6)', '(4; 2)', '(−5; 1)'], '(0; −6)', 'y o‘qidagi nuqtaning x koordinatasi 0 bo‘ladi.', 'У точки на оси y координата x равна 0.'),
    bool("C(−8; 0) nuqta x o‘qida joylashgan.", 'Точка C(−8; 0) находится на оси x.', true, 'y = 0 bo‘lgan barcha nuqtalar x o‘qida yotadi.', 'Все точки с y = 0 лежат на оси x.'),
    match("Nuqtalarni koordinata ishoralari bilan bog‘lang.", 'Соедините точки со знаками их координат.', ['M(−2; 9)', 'N(7; 4)', 'K(−6; −3)'], ['(−;+)', '(+;+)', '(−;−)'], [0, 1, 2], 'Koordinatalarning ishoralari nuqtaning choragini aniqlaydi.', 'Знаки координат определяют четверть точки.'),
    choice("D(−2; 5) nuqtadan 4 birlik o‘ngga siljiganda hosil bo‘ladigan nuqtani toping.", 'Найдите точку, полученную сдвигом D(−2; 5) на 4 единицы вправо.', ['(−6; 5)', '(2; 5)', '(−2; 9)', '(−2; 1)'], '(2; 5)', 'O‘ngga siljishda x ga 4 qo‘shiladi, y o‘zgarmaydi: (2; 5).', 'При сдвиге вправо к x прибавляют 4, y не меняется: (2; 5).'),
    input("E(3; −4) nuqtadan x o‘qigacha bo‘lgan masofani yozing.", 'Запишите расстояние от точки E(3; −4) до оси x.', 4, 'x o‘qigacha masofa ordinata moduliga teng: |−4| = 4.', 'Расстояние до оси x равно модулю ординаты: |−4| = 4.'),
    match("Siljishlarni yangi nuqtalar bilan moslashtiring.", 'Соедините перемещения с новыми точками.', ['(1;2) dan 3 o‘ngga', '(−2;4) dan 5 pastga', '(3;−1) dan 2 chapga'], ['(4;2)', '(−2;−1)', '(1;−1)'], [0, 1, 2], 'Gorizontal siljish x ni, vertikal siljish y ni o‘zgartiradi.', 'Горизонтальное перемещение меняет x, вертикальное — y.'),
    choice("A(−1; 2) va B(−1; −5) nuqtalar orasidagi vertikal masofani toping.", 'Найдите вертикальное расстояние между точками A(−1; 2) и B(−1; −5).', ['3', '5', '7', '8'], '7', 'x lar teng; masofa ordinatalar ayirmasining moduli: |2 − (−5)| = 7.', 'Координаты x равны; расстояние равно |2 − (−5)| = 7.'),
  ]),
};

// 31–46-darslar quyida ixcham generatorlar orqali bir xil interaktiv tuzilishda beriladi.
const remaining = [
  [31, 'Harfli ifodalar', 'Буквенные выражения',
    ['x = 4 bo‘lganda 3x + 7 ifodaning qiymatini toping.', 'При x = 4 найдите значение 3x + 7.', ['12','19','21','28'], '19'],
    ['a = −3 bo‘lganda 5a − 2 qiymatini yozing.', 'При a = −3 запишите значение 5a − 2.', -17],
    [['2x + 5','4a − 1','3m'],['x=3 → 11','a=2 → 7','m=5 → 15']],
    ['Bir daftar narxi p so‘m. 6 ta daftar narxini ifodalovchi yozuvni tanlang.', 'Одна тетрадь стоит p сумов. Выберите выражение стоимости 6 тетрадей.', ['p+6','p−6','6p','p:6'], '6p'],
    ['7y ifodada 7 soni koeffitsiyent hisoblanadi.', 'В выражении 7y число 7 является коэффициентом.', true],
    [['5x','a+9','2(m−1)'],['5·x','a ga 9 qo‘shish','m−1 ni 2 ga ko‘paytirish']],
    ['To‘g‘ri to‘rtburchak tomonlari a va b. Perimetr formulasini tanlang.', 'Стороны прямоугольника a и b. Выберите формулу периметра.', ['ab','2a+b','2(a+b)','a+b'], '2(a+b)'],
    ['n = 6 bo‘lganda n² − 10 qiymatini yozing.', 'При n = 6 запишите значение n² − 10.', 26],
    [['4x+3 dagi koeffitsiyent','9−y dagi ozod had','ab dagi ko‘paytuvchilar soni'],['4','9','2']],
    ['x = 5, y = 2 bo‘lganda 2x + 3y ni toping.', 'При x = 5 и y = 2 найдите 2x + 3y.', ['11','13','16','20'], '16']],
  [32, 'Qavslarni ochish', 'Раскрытие скобок',
    ['4(x + 3) ifodani qavslarni ochib yozing.', 'Раскройте скобки в выражении 4(x + 3).', ['4x+3','4x+7','4x+12','x+12'], '4x+12'],
    ['x = 5 bo‘lganda 3(x − 2) qiymatini yozing.', 'При x = 5 вычислите 3(x − 2).', 9],
    [['2(a+4)','5(y−1)','−3(m+2)'],['2a+8','5y−5','−3m−6']],
    ['−(x − 7) ifodaning qavssiz ko‘rinishini tanlang.', 'Выберите выражение без скобок, равное −(x − 7).', ['−x−7','−x+7','x−7','x+7'], '−x+7'],
    ['6(a − 2) = 6a − 12 tenglik to‘g‘ri.', 'Равенство 6(a − 2) = 6a − 12 верно.', true],
    [['−(a+5)','3(2x−1)','−2(4−y)'],['−a−5','6x−3','−8+2y']],
    ['2(3x + 4) − x ifodani soddalashtiring.', 'Упростите выражение 2(3x + 4) − x.', ['5x+8','6x+3','7x+8','5x+4'], '5x+8'],
    ['x = −2 bo‘lganda −2(x + 5) qiymatini yozing.', 'При x = −2 вычислите −2(x + 5).', -6],
    [['3(a−2)+1','−(2x−5)','4−2(y+1)'],['3a−5','−2x+5','2−2y']],
    ['5(2x − 3) − 2(x + 4) ni soddalashtiring.', 'Упростите 5(2x − 3) − 2(x + 4).', ['8x−23','8x−7','12x−23','12x−7'], '8x−23']],
  [33, "O'xshash hadlarni ixchamlash", 'Приведение подобных слагаемых',
    ['3x + 5x ifodani ixchamlang.', 'Приведите подобные слагаемые в выражении 3x + 5x.', ['8','8x','15x','2x'], '8x'],
    ['7a − 12a ifodadagi koeffitsiyentni yozing.', 'Запишите коэффициент выражения 7a − 12a.', -5],
    [['2x+6x','9a−4a','3m+m'],['8x','5a','4m']],
    ['4x + 3y − x ifodani soddalashtiring.', 'Упростите выражение 4x + 3y − x.', ['3x+3y','6xy','3x','4x+2y'], '3x+3y'],
    ['5a va −2a o‘xshash hadlar hisoblanadi.', 'Слагаемые 5a и −2a являются подобными.', true],
    [['6x−9x','2a+7−a','4m+3m−2m'],['−3x','a+7','5m']],
    ['2x + 5 + 7x − 3 ifodani ixchamlang.', 'Упростите выражение 2x + 5 + 7x − 3.', ['9x+2','9x+8','5x+2','14x+2'], '9x+2'],
    ['4y − 3 + 2y + 8 ifodada ozod hadni yozing.', 'Запишите свободный член после упрощения 4y − 3 + 2y + 8.', 5],
    [['3a+2b−a','8x−x+4','5m−2+2m−6'],['2a+2b','7x+4','7m−8']],
    ['3(2x + 1) − 4x + 5 ni ixchamlang.', 'Упростите 3(2x + 1) − 4x + 5.', ['2x+8','10x+8','2x−2','6x+4'], '2x+8']],
  [34, 'Chiziqli tenglamalar', 'Линейные уравнения',
    ['x + 9 = 17 tenglamaning ildizini toping.', 'Найдите корень уравнения x + 9 = 17.', ['6','8','9','26'], '8'],
    ['3x = 27 tenglamaning yechimini yozing.', 'Запишите решение уравнения 3x = 27.', 9],
    [['x−4=11','2x=24','x+7=3'],['15','12','−4']],
    ['5x − 6 = 19 tenglamani yeching.', 'Решите уравнение 5x − 6 = 19.', ['3','4','5','6'], '5'],
    ['x = 4 soni 2x + 1 = 9 tenglamaning ildizi.', 'Число x = 4 является корнем уравнения 2x + 1 = 9.', true],
    [['4x+3=19','7−x=10','3x−8=13'],['4','−3','7']],
    ['2(x + 3) = 18 tenglamaning ildizini toping.', 'Найдите корень уравнения 2(x + 3) = 18.', ['3','6','9','12'], '6'],
    ['6x − 5 = 2x + 15 tenglamaning yechimini yozing.', 'Запишите решение уравнения 6x − 5 = 2x + 15.', 5],
    [['5x−2=3x+12','3(x−1)=15','8−2x=14'],['7','6','−3']],
    ['4(2x − 1) = 3x + 16 tenglamani yeching.', 'Решите уравнение 4(2x − 1) = 3x + 16.', ['2','3','4','5'], '4']],
  [35, 'Tenglama yordamida masalalar yechish', 'Решение задач с помощью уравнений',
    ['Bir songa 12 qo‘shilganda 31 hosil bo‘ldi. Shu sonni toping.', 'К числу прибавили 12 и получили 31. Найдите число.', ['17','19','21','43'], '19'],
    ['Sonning 4 baravari 52 ga teng. Sonni yozing.', 'Четырёхкратное число равно 52. Запишите число.', 13],
    [['x+8=25','3x=42','x−9=16'],['17','14','25']],
    ['Ikki ketma-ket natural son yig‘indisi 41. Kichik sonni toping.', 'Сумма двух последовательных натуральных чисел равна 41. Найдите меньшее.', ['18','19','20','21'], '20'],
    ['Bir sonning yarmi 18 bo‘lsa, bu son 36 ga teng.', 'Если половина числа равна 18, то число равно 36.', true],
    [['x+(x+4)=30','2x+7=25','5x−6=34'],['13','9','8']],
    ['Ota o‘g‘lidan 24 yosh katta. Ularning yoshlari yig‘indisi 54. O‘g‘il yoshini toping.', 'Отец старше сына на 24 года, сумма их возрастов 54. Найдите возраст сына.', ['12','15','18','30'], '15'],
    ['Uchta teng qutida jami 81 ta qalam bor. Bitta qutidagi qalamlar sonini yozing.', 'В трёх одинаковых коробках 81 карандаш. Запишите число карандашей в одной коробке.', 27],
    [['x+x+6=40','4x−5=47','x/3+7=12'],['17','13','15']],
    ['To‘g‘ri to‘rtburchak eni x, bo‘yi x+5, perimetri 46. Enini toping.', 'Ширина прямоугольника x, длина x+5, периметр 46. Найдите ширину.', ['8','9','11','14'], '9']],
  [36, 'Iqtisodiy va ishga oid masalalar', 'Экономические задачи и задачи на работу',
    ['Bir dona ruchka 4 500 so‘m. 8 ta ruchkaning narxini toping.', 'Одна ручка стоит 4 500 сумов. Найдите стоимость 8 ручек.', ['32 000','34 000','36 000','40 000'], '36 000'],
    ['5 ta bir xil daftar 60 ming so‘m turadi. Bitta daftar narxini ming so‘mda yozing.', '5 одинаковых тетрадей стоят 60 тысяч сумов. Запишите цену одной в тысячах.', 12],
    [['6·7000','48000:8','90000−65000'],['42 000','6 000','25 000']],
    ['Usta soatiga 15 ta detal tayyorlaydi. 7 soatda nechta detal tayyorlaydi?', 'Мастер изготавливает 15 деталей в час. Сколько деталей он сделает за 7 часов?', ['90','100','105','120'], '105'],
    ['Foyda daromaddan xarajatni ayirish orqali topiladi.', 'Прибыль находят вычитанием расходов из дохода.', true],
    [['A=12·8','t=144:18','r=175:7'],['96','8','25']],
    ['Mahsulot 250 mingga olinib, 290 mingga sotildi. Foydani toping.', 'Товар купили за 250 тысяч и продали за 290 тысяч. Найдите прибыль.', ['30 ming','40 ming','50 ming','540 ming'], '40 ming'],
    ['Bir ishchi 6 soatda 54 detal tayyorladi. Soatlik unumdorligini yozing.', 'Рабочий изготовил 54 детали за 6 часов. Запишите производительность в час.', 9],
    [['C=p·n','A=r·t','F=D−X'],['qiymat','ish hajmi','foyda']],
    ['Ikki usta soatiga 12 va 15 tadan detal tayyorlaydi. 8 soatda jami nechta detal tayyorlanadi?', 'Два мастера делают 12 и 15 деталей в час. Сколько деталей они сделают за 8 часов?', ['196','206','216','226'], '216']],
  [37, 'Aylana va doira', 'Окружность и круг',
    ['Markazdan aylananing istalgan nuqtasigacha bo‘lgan kesma nima deyiladi?', 'Как называется отрезок от центра до любой точки окружности?', ['radius','diametr','vatar','yoy'], 'radius'],
    ['Radiusi 7 cm bo‘lgan aylananing diametrini yozing.', 'Запишите диаметр окружности радиуса 7 см.', 14],
    [['radius','diametr','vatar'],['r','2r','ikki nuqtani tutashtiradi']],
    ['Aylana va uning ichki qismi birgalikda nima deyiladi?', 'Как называется окружность вместе с внутренней областью?', ['yoy','doira','vatar','radius'], 'doira'],
    ['Diametr markazdan o‘tadigan vatardir.', 'Диаметр — хорда, проходящая через центр.', true],
    [['r=5','d=18','r=12'],['d=10','r=9','d=24']],
    ['Qaysi kesma aylananing eng uzun vatari hisoblanadi?', 'Какой отрезок является самой длинной хордой окружности?', ['radius','diametr','yoy','urinma'], 'diametr'],
    ['Diametri 26 cm bo‘lgan doiraning radiusini yozing.', 'Запишите радиус круга диаметром 26 см.', 13],
    [['faqat chegara','chegara va ichki qism','aylana bo‘lagi'],['aylana','doira','yoy']],
    ['O nuqta markaz, OA=9 cm. AB diametr bo‘lsa, AB uzunligini toping.', 'O — центр, OA=9 см. Если AB — диаметр, найдите AB.', ['9 cm','18 cm','27 cm','81 cm'], '18 cm']],
  [38, 'Aylana uzunligi', 'Длина окружности',
    ['Radiusi 5 cm bo‘lgan aylana uzunligini π=3,14 da toping.', 'Найдите длину окружности радиуса 5 см при π=3,14.', ['15,7 cm','31,4 cm','62,8 cm','78,5 cm'], '31,4 cm'],
    ['Diametri 12 cm bo‘lgan aylana uzunligini π=3 deb hisoblab yozing.', 'Вычислите длину окружности диаметра 12 см при π=3.', 36],
    [['r=4, π=3','d=10, π=3,14','r=7, π=22/7'],['24','31,4','44']],
    ['Aylana uzunligi 62,8 cm, π=3,14. Diametrni toping.', 'Длина окружности 62,8 см, π=3,14. Найдите диаметр.', ['10 cm','20 cm','30 cm','40 cm'], '20 cm'],
    ['Aylana uzunligi kvadrat santimetrda o‘lchanadi.', 'Длина окружности измеряется в квадратных сантиметрах.', false],
    [['C=2πr','C=πd','yarim yoy'],['radius orqali','diametr orqali','πr']],
    ['Radiusi 6 cm bo‘lgan yarim doiraning perimetrini π=3 da toping.', 'Найдите периметр полукруга радиуса 6 см при π=3.', ['18 cm','24 cm','30 cm','36 cm'], '30 cm'],
    ['G‘ildirak diametri 0,7 m. π=22/7 da bir aylanish yo‘lini santimetrda yozing.', 'Диаметр колеса 0,7 м. При π=22/7 запишите путь за оборот в сантиметрах.', 220],
    [['d=8,π=3','r=10,π=3,14','d=14,π=22/7'],['24','62,8','44']],
    ['Aylana radiusi 3 marta oshsa, uning uzunligi qanday o‘zgaradi?', 'Как изменится длина окружности, если радиус увеличить в 3 раза?', ['o‘zgarmaydi','2 marta oshadi','3 marta oshadi','9 marta oshadi'], '3 marta oshadi']],
  [39, 'Doira yuzi', 'Площадь круга',
    ['Radiusi 4 cm bo‘lgan doira yuzini π=3,14 da toping.', 'Найдите площадь круга радиуса 4 см при π=3,14.', ['12,56 cm²','25,12 cm²','50,24 cm²','100,48 cm²'], '50,24 cm²'],
    ['Radiusi 6 cm bo‘lgan doira yuzini π=3 deb hisoblab yozing.', 'Вычислите площадь круга радиуса 6 см при π=3.', 108],
    [['r=2,π=3','r=5,π=3,14','d=8,π=3'],['12','78,5','48']],
    ['Doira yuzi 75 cm², π=3. Radiusini toping.', 'Площадь круга 75 см², π=3. Найдите радиус.', ['3 cm','4 cm','5 cm','25 cm'], '5 cm'],
    ['Doira yuzi S=πr² formula bilan topiladi.', 'Площадь круга вычисляется по формуле S=πr².', true],
    [['chegara uzunligi','ichki qism yuzi','radius kvadrati'],['2πr','πr²','r²']],
    ['Radiusi 3 cm bo‘lgan doira bilan radiusi 6 cm doira yuzlari nisbatini toping.', 'Найдите отношение площадей кругов радиусов 3 см и 6 см.', ['1:2','1:3','1:4','1:6'], '1:4'],
    ['Diametri 10 cm bo‘lgan doira yuzini π=3,14 da yozing.', 'Запишите площадь круга диаметром 10 см при π=3,14.', '78,5'],
    [['r=7,π=22/7','r=10,π=3','r=1,5,π=3'],['154','300','6,75']],
    ['Halqaning tashqi radiusi 5 cm, ichki radiusi 3 cm. π=3 da yuzini toping.', 'Внешний радиус кольца 5 см, внутренний 3 см. Найдите площадь при π=3.', ['24 cm²','36 cm²','48 cm²','75 cm²'], '48 cm²']],
  [40, "O'q simmetriyasi", 'Осевая симметрия',
    ['Kvadrat nechta simmetriya o‘qiga ega?', 'Сколько осей симметрии у квадрата?', ['1','2','3','4'], '4'],
    ['Teng yonli uchburchakning simmetriya o‘qlari sonini yozing.', 'Запишите число осей симметрии равнобедренного треугольника.', 1],
    [['kvadrat','to‘g‘ri to‘rtburchak','turli tomonli uchburchak'],['4','2','0']],
    ['A(3; −2) nuqtaning y o‘qiga nisbatan aksini toping.', 'Найдите отражение точки A(3; −2) относительно оси y.', ['(−3;−2)','(3;2)','(−3;2)','(3;−2)'], '(−3;−2)'],
    ['O‘q simmetriyasida nuqta va uning aksi o‘qdan teng masofada bo‘ladi.', 'При осевой симметрии точка и её образ равноудалены от оси.', true],
    [['(2;5) x o‘qiga','(−4;3) y o‘qiga','(1;−6) y o‘qiga'],['(2;−5)','(4;3)','(−1;−6)']],
    ['Qaysi bosh lotin harfi vertikal simmetriya o‘qiga ega?', 'Какая заглавная латинская буква имеет вертикальную ось симметрии?', ['A','F','G','R'], 'A'],
    ['B(−7; 4) nuqtaning x o‘qiga nisbatan aksi ordinatasini yozing.', 'Запишите ординату отражения B(−7; 4) относительно оси x.', -4],
    [['y o‘qiga aks','x o‘qiga aks','x=y ga aks'],['(x;y)→(−x;y)','(x;y)→(x;−y)','(x;y)→(y;x)']],
    ['A(−2; 6) avval y o‘qiga, keyin x o‘qiga akslantirildi. Natijani toping.', 'A(−2; 6) отразили сначала относительно y, затем относительно x. Найдите результат.', ['(2;−6)','(−2;−6)','(2;6)','(−6;2)'], '(2;−6)']],
  [41, 'Markaziy simmetriya', 'Центральная симметрия',
    ['A(4; −3) nuqtaning koordinatalar boshiga nisbatan simmetrigini toping.', 'Найдите точку, симметричную A(4; −3) относительно начала координат.', ['(−4;3)','(4;3)','(−4;−3)','(3;−4)'], '(−4;3)'],
    ['B(−6; 8) nuqtaning O markazga nisbatan aksi abssissasini yozing.', 'Запишите абсциссу образа B(−6; 8) при симметрии относительно O.', 6],
    [['(2;3)','(−5;1)','(4;−7)'],['(−2;−3)','(5;−1)','(−4;7)']],
    ['Markaziy simmetriya qanday burilishga teng?', 'Какому повороту соответствует центральная симметрия?', ['90°','120°','180°','360°'], '180°'],
    ['Oddiy uchburchak markaziy simmetriyaga ega.', 'Обычный треугольник имеет центральную симметрию.', false],
    [['parallelogramm','aylana','uchburchak'],['bor — diagonallar kesishgan nuqta','bor — aylana markazi','yo‘q']],
    ['A(1; 5) va A′(−1; −5) kesmasining o‘rta nuqtasini toping.', 'Найдите середину отрезка AA′ для A(1; 5), A′(−1; −5).', ['(0;0)','(1;0)','(0;5)','(−1;0)'], '(0;0)'],
    ['C(9; −2) nuqtaning markaziy simmetrigidagi ordinatani yozing.', 'Запишите ординату точки, центрально-симметричной C(9; −2).', 2],
    [['180° burilish','O ga nisbatan aks','ikki marta markaziy aks'],['(x;y)→(−x;−y)','qarama-qarshi nuqta','boshlang‘ich nuqta']],
    ['P(−3; 4) nuqta ikki marta O markazga nisbatan akslantirildi. Natijani toping.', 'Точку P(−3; 4) дважды отразили относительно O. Найдите результат.', ['(3;−4)','(−3;4)','(3;4)','(−4;3)'], '(−3;4)']],
  [42, 'Uchburchak elementlari, turlari va perimetri', 'Элементы, виды и периметр треугольника',
    ['Tomonlari 5 cm, 7 cm va 8 cm bo‘lgan uchburchak perimetrini toping.', 'Найдите периметр треугольника со сторонами 5, 7 и 8 см.', ['18 cm','20 cm','21 cm','28 cm'], '20 cm'],
    ['Teng tomonli uchburchak perimetri 36 cm. Bir tomoni uzunligini yozing.', 'Периметр равностороннего треугольника 36 см. Запишите длину стороны.', 12],
    [['3,3,5','4,5,6','5,5,5'],['teng yonli','turli tomonli','teng tomonli']],
    ['Bitta burchagi 90° bo‘lgan uchburchak turini tanlang.', 'Выберите вид треугольника с одним углом 90°.', ['o‘tkir','to‘g‘ri burchakli','o‘tmas','teng tomonli'], 'to‘g‘ri burchakli'],
    ['2 cm, 4 cm va 7 cm kesmalardan uchburchak yasash mumkin.', 'Из отрезков 2, 4 и 7 см можно построить треугольник.', false],
    [['60°,60°,60°','30°,60°,90°','40°,40°,100°'],['o‘tkir','to‘g‘ri burchakli','o‘tmas']],
    ['Ikki tomoni 9 cm va 13 cm. Uchinchi tomon uchun qaysi uzunlik mumkin?', 'Две стороны равны 9 и 13 см. Какая длина третьей стороны возможна?', ['3 cm','4 cm','10 cm','23 cm'], '10 cm'],
    ['Teng yonli uchburchak yon tomonlari 11 cm, asosi 8 cm. Perimetrini yozing.', 'Боковые стороны равнобедренного треугольника 11 см, основание 8 см. Запишите периметр.', 30],
    [['uch','tomon','burchak'],['A,B,C','AB,BC,CA','∠A,∠B,∠C']],
    ['Perimetri 42 cm bo‘lgan teng yonli uchburchakning asosi 12 cm. Yon tomonini toping.', 'Периметр равнобедренного треугольника 42 см, основание 12 см. Найдите боковую сторону.', ['12 cm','15 cm','18 cm','30 cm'], '15 cm']],
  [43, 'Uchburchak va murakkab shakllar yuzi', 'Площадь треугольника и сложных фигур',
    ['Asosi 10 cm, balandligi 6 cm bo‘lgan uchburchak yuzini toping.', 'Найдите площадь треугольника с основанием 10 см и высотой 6 см.', ['16 cm²','30 cm²','60 cm²','80 cm²'], '30 cm²'],
    ['Asosi 14 cm, balandligi 5 cm bo‘lgan uchburchak yuzini yozing.', 'Запишите площадь треугольника с основанием 14 см и высотой 5 см.', 35],
    [['a=8,h=4','a=9,h=6','a=12,h=5'],['16','27','30']],
    ['Uchburchak yuzi 48 cm², asosi 12 cm. Balandligini toping.', 'Площадь треугольника 48 см², основание 12 см. Найдите высоту.', ['4 cm','6 cm','8 cm','12 cm'], '8 cm'],
    ['Uchburchak yuzi asos bilan balandlik ko‘paytmasining yarmiga teng.', 'Площадь треугольника равна половине произведения основания и высоты.', true],
    [['to‘rtburchak 8·5','uchburchak 10·4:2','kvadrat 7²'],['40','20','49']],
    ['12×9 to‘rtburchakdan yuzi 24 bo‘lgan uchburchak kesildi. Qolgan yuzni toping.', 'Из прямоугольника 12×9 вырезали треугольник площадью 24. Найдите остаток.', ['72','80','84','108'], '84'],
    ['Yuzi 54 cm², balandligi 9 cm bo‘lgan uchburchak asosini yozing.', 'Запишите основание треугольника площадью 54 см² и высотой 9 см.', 12],
    [['katakli 6×4 to‘rtburchak','uning yarmi','undan 5 katak ayirildi'],['24','12','19']],
    ['Trapetsiyasimon shakl 8×6 to‘rtburchak va asosi 8, balandligi 3 uchburchakdan tuzilgan. Jami yuzni toping.', 'Фигура состоит из прямоугольника 8×6 и треугольника с основанием 8 и высотой 3. Найдите площадь.', ['54','60','72','96'], '60']],
  [44, "Fazoviy shakllar hajmi va o'lchov birliklari", 'Объём пространственных фигур и единицы',
    ['O‘lchamlari 3 cm, 4 cm va 5 cm bo‘lgan parallelepiped hajmini toping.', 'Найдите объём параллелепипеда размером 3, 4 и 5 см.', ['12 cm³','20 cm³','47 cm³','60 cm³'], '60 cm³'],
    ['Qirrasi 6 cm bo‘lgan kub hajmini yozing.', 'Запишите объём куба с ребром 6 см.', 216],
    [['2·3·7','4³','10·5·2'],['42','64','100']],
    ['1 dm³ necha cm³ ga teng?', 'Сколько кубических сантиметров в 1 дм³?', ['10','100','1000','10000'], '1000'],
    ['Hajm kub birliklarda o‘lchanadi.', 'Объём измеряется в кубических единицах.', true],
    [['2 dm³','3500 cm³','0,5 m³'],['2000 cm³','3,5 dm³','500 dm³']],
    ['Hajmi 120 cm³, asos yuzi 30 cm² bo‘lgan prizma balandligini toping.', 'Объём призмы 120 см³, площадь основания 30 см². Найдите высоту.', ['3 cm','4 cm','5 cm','6 cm'], '4 cm'],
    ['Uzunligi 8 cm, eni 5 cm, hajmi 240 cm³ bo‘lgan qutining balandligini yozing.', 'Длина коробки 8 см, ширина 5 см, объём 240 см³. Запишите высоту.', 6],
    [['1 m³','1 dm³','1 cm³'],['1 000 000 cm³','1000 cm³','1 cm³']],
    ['Akvarium 50×30×40 cm. Uning sig‘imini litrlarda toping.', 'Аквариум имеет размеры 50×30×40 см. Найдите вместимость в литрах.', ['6 l','60 l','600 l','6000 l'], '60 l']],
  [45, "Ma'lumotlar bilan ishlash", 'Работа с данными',
    ['2, 4, 4, 5, 7 qatorining modasini toping.', 'Найдите моду ряда 2, 4, 4, 5, 7.', ['2','4','5','7'], '4'],
    ['3, 6, 8, 10, 12 qatorining medianasini yozing.', 'Запишите медиану ряда 3, 6, 8, 10, 12.', 8],
    [['2,2,3,5','1,4,7','6,8,10,12'],['moda=2','mediana=4','o‘rtacha=9']],
    ['5, 7, 9, 11 qatorining o‘rtacha arifmetigini toping.', 'Найдите среднее арифметическое ряда 5, 7, 9, 11.', ['7','8','9','10'], '8'],
    ['Ma’lumotlar qatorining kengligi eng katta va eng kichik qiymatlar ayirmasiga teng.', 'Размах ряда данных равен разности наибольшего и наименьшего значений.', true],
    [['3,7,8,12','4,4,6,9','2,5,8,11,14'],['kenglik=9','moda=4','mediana=8']],
    ['6, 8, 8, 10, 13 qatorining o‘rtacha qiymatini toping.', 'Найдите среднее ряда 6, 8, 8, 10, 13.', ['8','9','10','11'], '9'],
    ['14, 9, 17, 11, 20 qatorining o‘zgarish kengligini yozing.', 'Запишите размах ряда 14, 9, 17, 11, 20.', 11],
    [['1,3,3,7,9','2,4,6,8','5,5,5'],['moda=3','mediana=5','o‘rtacha=5']],
    ['4, 6, 7, 9, 10, 14 qatorining medianasini toping.', 'Найдите медиану ряда 4, 6, 7, 9, 10, 14.', ['7','8','9','10'], '8']],
  [46, "Geometriya va ma'lumotlar bo'limi yakuni", 'Итог раздела геометрии и данных',
    ['Radiusi 7 cm aylana uzunligini π=22/7 da toping.', 'Найдите длину окружности радиуса 7 см при π=22/7.', ['22 cm','44 cm','49 cm','154 cm'], '44 cm'],
    ['Asosi 16 cm, balandligi 9 cm uchburchak yuzini yozing.', 'Запишите площадь треугольника с основанием 16 см и высотой 9 см.', 72],
    [['kub qirrasi 4','doira r=3,π=3','qator 2,5,5,8'],['V=64','S=27','moda=5']],
    ['A(5; −2) nuqtaning markaziy simmetrigini toping.', 'Найдите точку, центрально-симметричную A(5; −2).', ['(−5;2)','(5;2)','(−5;−2)','(2;−5)'], '(−5;2)'],
    ['Kvadrat 4 ta simmetriya o‘qiga ega.', 'Квадрат имеет 4 оси симметрии.', true],
    [['C=2πr','S=ah/2','V=abc'],['aylana uzunligi','uchburchak yuzi','parallelepiped hajmi']],
    ['Tomonlari 7, 10 va 12 cm uchburchak perimetrini toping.', 'Найдите периметр треугольника со сторонами 7, 10 и 12 см.', ['27 cm','29 cm','32 cm','34 cm'], '29 cm'],
    ['1, 4, 6, 8, 11 qatorining o‘rtacha qiymatini yozing.', 'Запишите среднее ряда 1, 4, 6, 8, 11.', 6],
    [['(3;4) y o‘qiga aks','r=5,π=3 doira yuzi','2 dm³'],['(−3;4)','75 cm²','2000 cm³']],
    ['10×8 to‘rtburchakdan asosi 6, balandligi 4 uchburchak kesildi. Qolgan yuzni toping.', 'Из прямоугольника 10×8 вырезали треугольник с основанием 6 и высотой 4. Найдите остаток.', ['56 cm²','62 cm²','68 cm²','74 cm²'], '68 cm²']],
];

remaining.forEach(([number, topic, topicRu, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10]) => {
  const makeChoice = q => choice(
    q[0], q[1], q[2], q[3],
    `Shartdagi qiymatlarga mavzu qoidasini ketma-ket qo‘llasak, ${q[3]} hosil bo‘ladi.`,
    `После последовательного применения правила темы к данным условия получается ${q[3]}.`,
  );
  const makeInput = q => input(
    q[0], q[1], q[2],
    `Hisoblashdagi amallarni to‘g‘ri tartibda bajarsak, javob ${q[2]} bo‘ladi.`,
    `Если выполнить действия в правильном порядке, получится ответ ${q[2]}.`,
  );
  const makeMatch = q => match(
    'Har bir yozuvni unga mos javob yoki tavsif bilan bog‘lang.',
    'Соедините каждую запись с подходящим ответом или описанием.',
    q[0], q[1], [0, 1, 2],
    `Har bir chap kartani alohida tekshirish orqali mosliklar topiladi: ${q[0].map((value, index) => `${value} ↔ ${q[1][index]}`).join('; ')}.`,
    'Каждая пара найдена по определению или вычислению, указанному в условии темы.',
  );
  const makeBool = q => bool(
    q[0], q[1], q[2],
    q[2] ? 'Berilgan fikr mavzuning asosiy qoidasiga to‘liq mos keladi.' : 'Berilgan fikr mavzuning asosiy qoidasiga zid, shuning uchun u noto‘g‘ri.',
    q[2] ? 'Утверждение полностью соответствует основному правилу темы.' : 'Утверждение противоречит основному правилу темы, поэтому оно неверно.',
  );
  lessons[number] = L(number, topicRu, topic, [
    makeChoice(q1), makeInput(q2), makeMatch(q3), makeChoice(q4), makeBool(q5),
    makeMatch(q6), makeChoice(q7), makeInput(q8), makeMatch(q9), makeChoice(q10),
  ]);
});

export const GRADE6_PRACTICE_27_46 = {
  lessons,
  topics: Object.fromEntries(Object.entries(lessons).map(([number, lesson]) => [
    number,
    lesson.items.map(() => lesson.topic),
  ])),
  explanations: Object.fromEntries(Object.entries(lessons).map(([number, lesson]) => [
    number,
    lesson.items.map(item => item.explanation),
  ])),
};

const RU_VALUES = {
  'I chorak': 'I четверть', 'II chorak': 'II четверть', 'III chorak': 'III четверть', 'IV chorak': 'IV четверть',
  radius: 'радиус', diametr: 'диаметр', vatar: 'хорда', yoy: 'дуга', doira: 'круг', urinma: 'касательная',
  'teng yonli': 'равнобедренный', 'turli tomonli': 'разносторонний', 'teng tomonli': 'равносторонний',
  "to‘g‘ri burchakli": 'прямоугольный', "o‘tkir": 'остроугольный', "o‘tmas": 'тупоугольный',
  'aylana': 'окружность', 'faqat chegara': 'только граница', 'chegara va ichki qism': 'граница и внутренняя область',
  'aylana bo‘lagi': 'часть окружности', 'radius orqali': 'через радиус', 'diametr orqali': 'через диаметр',
  'o‘zgarmaydi': 'не изменится', '2 marta oshadi': 'увеличится в 2 раза', '3 marta oshadi': 'увеличится в 3 раза',
  '9 marta oshadi': 'увеличится в 9 раз', 'chegara uzunligi': 'длина границы', 'ichki qism yuzi': 'площадь внутри',
  'radius kvadrati': 'квадрат радиуса', 'bor': 'есть', "yo‘q": 'нет',
  'bor — diagonallar kesishgan nuqta': 'есть — точка пересечения диагоналей',
  'bor — aylana markazi': 'есть — центр окружности',
  '(1;2) dan 3 o‘ngga': 'из (1;2) на 3 вправо',
  '(−2;4) dan 5 pastga': 'из (−2;4) на 5 вниз',
  '(3;−1) dan 2 chapga': 'из (3;−1) на 2 влево',
  'ab dagi ko‘paytuvchilar soni': 'число множителей в ab',
  '(2;5) x o‘qiga': '(2;5) относительно оси x',
  '(−4;3) y o‘qiga': '(−4;3) относительно оси y',
  '(1;−6) y o‘qiga': '(1;−6) относительно оси y',
  'x=y ga aks': 'отражение относительно x=y',
  'kub qirrasi 4': 'ребро куба 4',
  'doira r=3,π=3': 'круг r=3, π=3',
  'qator 2,5,5,8': 'ряд 2, 5, 5, 8',
  'r=5,π=3 doira yuzi': 'площадь круга r=5, π=3',
  'qarama-qarshi nuqta': 'противоположная точка', 'boshlang‘ich nuqta': 'исходная точка',
  uch: 'вершина', tomon: 'сторона', burchak: 'угол', 'aylana uzunligi': 'длина окружности',
  'uchburchak yuzi': 'площадь треугольника', 'parallelepiped hajmi': 'объём параллелепипеда',
  qiymat: 'стоимость', 'ish hajmi': 'объём работы', foyda: 'прибыль',
};

const REPLACEMENTS = [
  [' ga nisbatan aks', ' относительно оси'], [' dagi koeffitsiyent', ': коэффициент'], [' dagi ozod had', ': свободный член'],
  ['ko‘paytuvchilar soni', 'число множителей'], ['ni 2 ga ko‘paytirish', 'умножить на 2'], [' ga 9 qo‘shish', ' прибавить 9'],
  ['to‘rtburchak', 'прямоугольник'], ['uchburchak', 'треугольник'], ['kvadrat', 'квадрат'],
  ['katakli', 'клетчатый'], ['uning yarmi', 'его половина'], ['undan 5 katak ayirildi', 'из него вычли 5 клеток'],
  ['o‘rtacha', 'среднее'], ['mediana', 'медиана'], ['moda', 'мода'], ['kenglik', 'размах'],
  ['y o‘qiga aks', 'отражение относительно y'], ['x o‘qiga aks', 'отражение относительно x'],
  ['O ga nisbatan aks', 'отражение относительно O'], ['180° burilish', 'поворот на 180°'],
  ['ikki marta markaziy aks', 'двойная центральная симметрия'], ['aylana', 'окружность'],
];

export function ruPracticeValue27(value) {
  const source = String(value);
  if (RU_VALUES[source]) return RU_VALUES[source];
  return REPLACEMENTS
    .reduce((text, [uz, ru]) => text.replaceAll(uz, ru), source)
    .replace(/\bming\b/g, 'тыс.')
    .replace(/\bcm\b/g, 'см')
    .replace(/\bdm\b/g, 'дм')
    .replace(/\bl\b/g, 'л');
}
