/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars19.jsx';

const T = (uz, ru) => ({ uz, ru });
const q = (type, uzTitle, ruTitle, uzText, ruText, visual, uzAsk, ruAsk, options, correct, uzHint, ruHint) => ({
  type, title: T(uzTitle, ruTitle), text: T(uzText, ruText), visual,
  ask: T(uzAsk, ruAsk), options, correct, hint: T(uzHint, ruHint),
});

export const SCREENS = [
  q('hook', "Terminal javobga ishonmayapti", "Терминал не доверяет ответу",
    "Bit 23 × 4 = 92 ni hisoblagan, ammo nazorat terminali natijani isbotlashni so'radi.",
    "Бит вычислил 23 × 4 = 92, но контрольный терминал просит доказать результат.",
    '23 × 4 = 92  →  ?', "Ko'paytirishni qaysi amal tekshiradi?", "Каким действием проверяют умножение?",
    [T("Bo'lish", "Делением"), T("Qo'shish", "Сложением"), T("Ayirish", "Вычитанием")], 0,
    "Ko'paytirish va bo'lish teskari amallar.", "Умножение и деление — обратные действия."),
  q('exploration', "Teskari yo'l", "Обратный путь",
    "23 ni 4 marta olsak 92 bo'ladi. 92 ni 4 ta teng guruhga ajratsak yana 23 chiqadi.",
    "Если взять 23 четыре раза, получится 92. Если 92 разделить на 4 равные группы, снова получим 23.",
    '23 × 4 = 92   ↔   92 : 4 = 23', "Tekshiruv natijasi nechaga teng?", "Чему равен результат проверки?",
    ['4', '23', '92'], 1, "Ko'paytmani ikkinchi ko'paytuvchiga bo'ling.", "Раздели произведение на второй множитель."),
  q('exploration', "Bo'lishni qaytaramiz", "Возвращаем деление",
    "96 : 4 = 24 bo'lsa, bo'linma bilan bo'luvchini ko'paytirib bo'linuvchini qaytaramiz.",
    "Если 96 : 4 = 24, умножаем частное на делитель и возвращаем делимое.",
    '96 : 4 = 24   →   24 × 4 = 96', "Bo'lish qaysi amal bilan tekshirildi?", "Каким действием проверили деление?",
    [T("Ko'paytirish", "Умножением"), T("Ayirish", "Вычитанием"), T("Bo'lish", "Делением")], 0,
    "24 va 4 ko'paytirildi.", "Умножили 24 и 4."),
  q('exploration', "Qo'shishni tekshirish", "Проверка сложения",
    "347 + 128 = 475. Yig'indidan bir qo'shiluvchini ayirsak, ikkinchisi qaytadi.",
    "347 + 128 = 475. Если из суммы вычесть одно слагаемое, вернётся другое.",
    '475 − 128 = 347', "475 − 347 nechaga teng?", "Чему равно 475 − 347?",
    ['118', '128', '138'], 1, "Yig'indidan birinchi qo'shiluvchini ayiring.", "Вычти из суммы первое слагаемое."),
  q('rule', "Tekshiruv qoidasi", "Правило проверки",
    "Natijani teskari amal bilan tekshiramiz: + ↔ − va × ↔ :. Tekshiruv boshlang'ich songa qaytarishi kerak.",
    "Результат проверяем обратным действием: + ↔ − и × ↔ :. Проверка должна вернуть исходное число.",
    '+ ↔ −      × ↔ :', "Ayirishning teskari amali qaysi?", "Какое действие обратно вычитанию?",
    [T("Qo'shish", "Сложение"), T("Bo'lish", "Деление"), T("Ko'paytirish", "Умножение")], 0,
    "Ayirma va ayriluvchini qo'shsak kamayuvchi qaytadi.", "Сложи разность и вычитаемое, чтобы вернуть уменьшаемое."),
  q('test', "Ko'paytirishni tekshiring", "Проверь умножение",
    "32 × 3 = 96 natijasini teskari amal bilan tekshiramiz.", "Проверим 32 × 3 = 96 обратным действием.",
    '96 : 3 = ?', "Natijani tanlang.", "Выбери результат.", ['29', '32', '33'], 1,
    "96 ni 3 ta teng guruhga ajrating.", "Раздели 96 на 3 равные группы."),
  q('test', "Bo'lishni tekshiring", "Проверь деление",
    "84 : 4 = 21 yozuvini tekshirish kerak.", "Нужно проверить запись 84 : 4 = 21.",
    '21 × 4 = ?', "Tekshiruv nimani berishi kerak?", "Что должна дать проверка?", ['80', '84', '88'], 1,
    "Bo'linma × bo'luvchi = bo'linuvchi.", "Частное × делитель = делимое."),
  q('test', "Qo'shishni tekshiring", "Проверь сложение",
    "526 + 247 = 773 hisoblandi.", "Вычислено 526 + 247 = 773.",
    '773 − 247 = ?', "Qaysi son qaytadi?", "Какое число вернётся?", ['526', '536', '1020'], 0,
    "Yig'indidan ikkinchi qo'shiluvchini ayiring.", "Вычти из суммы второе слагаемое."),
  q('test', "Ayirishni tekshiring", "Проверь вычитание",
    "700 − 286 = 414 natijasini tekshiramiz.", "Проверим результат 700 − 286 = 414.",
    '414 + 286 = ?', "Tekshiruv natijasi qaysi?", "Каков результат проверки?", ['600', '690', '700'], 2,
    "Ayirma va ayriluvchini qo'shing.", "Сложи разность и вычитаемое."),
  q('test', "Noto'g'ri javobni aniqlang", "Обнаружь неверный ответ",
    "Jasur 27 × 4 = 98 deb yozdi.", "Жасур записал 27 × 4 = 98.",
    '98 : 4 = 24 qoldiq 2', "Tekshiruv nimani ko'rsatdi?", "Что показала проверка?",
    [T("Javob to'g'ri", "Ответ верный"), T("98 ko'paytma emas", "98 не является произведением"), T("27 soni xato", "Число 27 неверно")], 1,
    "To'g'ri ko'paytma 4 ga qoldiqsiz bo'linib 27 ni qaytaradi.", "Верное произведение делится на 4 без остатка и возвращает 27."),
  q('test', "Qoldiqli natijani tekshirish", "Проверка результата с остатком",
    "31 : 6 = 5, qoldiq 1. Qoldiqli bo'lishda qoldiqni ham qo'shamiz.",
    "31 : 6 = 5, остаток 1. При проверке прибавляем остаток.",
    '6 × 5 + 1 = ?', "Tekshiruv natijasi?", "Результат проверки?", ['30', '31', '36'], 1,
    "Avval ko'paytiring, keyin qoldiqni qo'shing.", "Сначала умножь, затем прибавь остаток."),
  q('case', "Ustaxona hisobi", "Расчёт мастерской",
    "Har birida 18 tadan detal bo'lgan 5 quti uchun terminal 80 ta detal deb ko'rsatdi.",
    "Для 5 коробок по 18 деталей терминал показал 80 деталей.",
    '18 × 5 = 80 ?', "Qaysi tekshiruv xatoni ochadi?", "Какая проверка обнаружит ошибку?",
    ['80 : 5 = 16', '80 − 5 = 75', '18 + 5 = 23'], 0,
    "Ko'paytmani ko'paytuvchiga bo'ling: 18 qaytishi kerak edi.", "Раздели произведение на множитель: должно было вернуться 18."),
  q('test', "Mustaqil tekshiruv", "Самостоятельная проверка",
    "936 − 458 = 478 hisoblandi.", "Вычислено 936 − 458 = 478.",
    '478 + 458 = 936', "Natija to'g'rimi?", "Верно ли решение?",
    [T("Ha", "Да"), T("Yo'q", "Нет"), T("Tekshirib bo'lmaydi", "Нельзя проверить")], 0,
    "Tekshiruv kamayuvchini aynan qaytardi.", "Проверка точно вернула уменьшаемое."),
  q('test', "Yakuniy diagnostika", "Итоговая диагностика",
    "48 × 6 = 288 natijasi berilgan. Boshqa ko'rinishda tekshiring.", "Дан результат 48 × 6 = 288. Проверь его другим способом.",
    '288 : □ = 48', "Katakka qaysi son tushadi?", "Какое число нужно поставить?", ['4', '6', '8'], 1,
    "Ko'paytmani noma'lum ko'paytuvchiga bo'lganda 48 chiqishi kerak.", "При делении произведения на неизвестный множитель должно получиться 48."),
  q('summary', "Nazorat terminali ochildi", "Контрольный терминал открыт",
    "Siz to'rt amal natijasini teskari amal bilan isbotladingiz. Bit endi ustaxona hisoblarini ishonchli tekshira oladi.",
    "Ты доказал результаты четырёх действий обратными действиями. Теперь Бит надёжно проверяет расчёты мастерской.",
    '+ ↔ −      × ↔ :', "Tekshiruvning maqsadi nima?", "Какова цель проверки?",
    [T("Boshlang'ich sonni qaytarish", "Вернуть исходное число"), T("Natijani kattalashtirish", "Увеличить результат"), T("Amalni takrorlash", "Повторить действие")], 0,
    "Teskari amal oldingi qadamni bekor qiladi.", "Обратное действие отменяет предыдущий шаг."),
];

export default function Dars20() {
  return <Grade3LessonShell screens={SCREENS} titleUz="20-dars. Amallarni tekshirish" titleRu="Урок 20. Проверка действий" />;
}
