/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars19.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type, title: T(...title), text: T(...text), visual, ask: T(...ask),
  options: options.map(([uz, ru = uz]) => T(uz, ru)), correct, hint: T(...hint),
});

export const SCREENS = [
  S('hook', ["Ulushga aniq manzil kerak", "Доле нужен точный адрес"],
    ["Bit patirning bir bo'lagini saqladi. «Bir bo'lak» deyish yetarli emas: butun nechta teng qismga bo'linganini ham bilish kerak.", "Бит сохранил одну часть лепёшки. Сказать «одна часть» недостаточно: нужно знать, на сколько равных частей разделили целое."],
    '◔  =  ? / ?', ["Bo'lakni aniq yozish uchun nima kerak?", "Что нужно для точной записи части?"],
    [["Olingan va jami teng bo'laklar soni", "Число взятых и всех равных частей"], ["Faqat bo'lak rangi", "Только цвет части"], ["Faqat butun nomi", "Только название целого"]], 0,
    ["Nechta teng qismdan nechtasi olinganini ayting.", "Укажи, сколько частей взяли из общего числа равных частей."]),
  S('exploration', ["Kasr yozuvi", "Запись дроби"],
    ["Butun 4 ta teng bo'lakka bo'lindi va 1 bo'lak olindi. Bu «to'rtdan bir» bo'lib, 1/4 yoziladi.", "Целое разделили на 4 равные части и взяли 1 часть. Это «одна четверть», записывается 1/4."],
    '1\n―\n4', ["Pastdagi 4 nimani bildiradi?", "Что означает нижняя цифра 4?"],
    [["Butun 4 teng qismga bo'lingan", "Целое разделено на 4 равные части"], ["4 qism olingan", "Взяли 4 части"], ["4 ta butun bor", "Есть 4 целых"]], 0,
    ["Pastdagi son barcha teng bo'laklar sonini ko'rsatadi.", "Нижнее число показывает общее число равных частей."]),
  S('exploration', ["Maxraj", "Знаменатель"],
    ["Kasr chizig'ining pastidagi son maxraj deyiladi. U butun nechta teng bo'lakka ajratilganini ko'rsatadi.", "Число под дробной чертой называется знаменателем. Оно показывает, на сколько равных частей разделено целое."],
    'surat\n────\nMAXRAJ', ["3/8 kasrining maxraji qaysi?", "Каков знаменатель дроби 3/8?"],
    [['3'], ['8'], ['11']], 1,
    ["Kasr chizig'ining pastiga qarang.", "Посмотри под дробную черту."]),
  S('exploration', ["Surat", "Числитель"],
    ["Kasr chizig'ining yuqorisidagi son surat deyiladi. U nechta teng bo'lak olinganini ko'rsatadi.", "Число над дробной чертой называется числителем. Оно показывает, сколько равных частей взяли."],
    'SURAT\n────\nmaxraj', ["3/8 kasrining surati qaysi?", "Каков числитель дроби 3/8?"],
    [['3'], ['8'], ['5']], 0,
    ["Kasr chizig'ining yuqorisiga qarang.", "Посмотри над дробную черту."]),
  S('exploration', ["Modeldan kasrga", "От модели к дроби"],
    ["Tasma 5 ta teng katakka bo'lindi, 2 tasi bo'yaldi. Jami qismlar maxrajga, bo'yalgan qismlar suratga yoziladi.", "Полоску разделили на 5 равных клеток, 2 закрасили. Все части записывают в знаменатель, закрашенные — в числитель."],
    '■■□□□  =  2/5', ["Model qaysi kasrni ko'rsatadi?", "Какую дробь показывает модель?"],
    [['2/3'], ['2/5'], ['5/2']], 1,
    ["2 ta olingan, jami 5 ta teng qism.", "Взяли 2 части, всего 5 равных частей."]),
  S('rule', ["Kasrning ma'nosi", "Смысл дроби"],
    ["a/b yozuvida b — butundagi barcha teng bo'laklar soni, a — olingan bo'laklar soni. Kasr chizig'i butunni teng bo'lishni bildiradi.", "В записи a/b число b — общее число равных частей, a — число взятых частей. Дробная черта означает деление целого на равные части."],
    'surat / maxraj = olingan / jami teng bo‘lak', ["Qaysi son avval aniqlanadi?", "Какое число определяют сначала?"],
    [["Jami teng bo'laklar — maxraj", "Все равные части — знаменатель"], ["Faqat surat", "Только числитель"], ["Ikkalasi taxminan", "Оба наугад"]], 0,
    ["Avval butun nechta teng qismga bo'linganini sanang.", "Сначала сосчитай все равные части целого."]),
  S('test', ["Kasrni o'qiymiz", "Читаем дробь"],
    ["2/3 kasrida maxraj 3, surat 2.", "В дроби 2/3 знаменатель 3, числитель 2."],
    '2/3', ["Kasr qanday o'qiladi?", "Как читается дробь?"],
    [["Uchdan ikki", "Две трети"], ["Ikkidan uch", "Три вторых"], ["Uch yarim", "Три половины"]], 0,
    ["Avval maxraj nomi, so'ng olingan qismlar soni aytiladi.", "Название доли задаёт знаменатель, затем учитывают число взятых частей."]),
  S('test', ["Rasmga mos yozuv", "Запись по рисунку"],
    ["Doira 6 ta teng bo'lakka bo'lingan, 4 tasi yoritilgan.", "Круг разделён на 6 равных частей, 4 освещены."],
    'jami 6 · olingan 4', ["To'g'ri kasrni tanlang.", "Выбери верную дробь."],
    [['4/6'], ['6/4'], ['2/6']], 0,
    ["Olingan qismlar suratga, jami qismlar maxrajga.", "Взятые части — в числитель, все части — в знаменатель."]),
  S('test', ["Yozuvdan modelga", "От записи к модели"],
    ["5/7 kasri butun 7 ta teng bo'lakdan iboratligini va 5 qismi olinganini bildiradi.", "Дробь 5/7 означает, что целое состоит из 7 равных частей и взяли 5."],
    '5/7', ["Qaysi model mos?", "Какая модель подходит?"],
    [['■■■■■□□'], ['■■■■■'], ['■■□□□□□']], 0,
    ["Jami 7 belgi, ulardan 5 tasi bo'yalgan bo'lishi kerak.", "Должно быть 7 частей, из них 5 закрашены."]),
  S('test', ["Yarimni kasr bilan yozamiz", "Записываем половину дробью"],
    ["Yarim — butunning ikki teng qismidan bittasi.", "Половина — одна из двух равных частей целого."],
    '1 qism / 2 teng qism', ["Yarimning yozuvi qaysi?", "Как записывается половина?"],
    [['1/2'], ['2/1'], ['1/4']], 0,
    ["Bitta qism olingan, jami ikkita.", "Взяли одну часть из двух."]),
  S('test', ["Butunni kasr bilan yozish", "Запись целого дробью"],
    ["To'rt teng bo'lakning barchasi olingan. Surat va maxraj teng bo'lsa, bitta butun hosil bo'ladi.", "Взяты все четыре равные части. Если числитель равен знаменателю, получается одно целое."],
    '■■■■ = 4/4', ["Qaysi kasr bir butunga teng?", "Какая дробь равна одному целому?"],
    [['3/4'], ['4/4'], ['1/4']], 1,
    ["Barcha qismlar olingan yozuvni tanlang.", "Выбери запись, где взяты все части."]),
  S('test', ["Nol qism olinganda", "Если ничего не взяли"],
    ["Butun 5 ta teng bo'lakka bo'lindi, lekin hech biri olinmadi. Surat nol bo'ladi.", "Целое разделили на 5 равных частей, но ни одной не взяли. Числитель равен нулю."],
    '□□□□□ = 0/5', ["Qaysi son nol?", "Какое число равно нулю?"],
    [["Surat", "Числитель"], ["Maxraj", "Знаменатель"], ["Jami bo'laklar", "Все части"]], 0,
    ["Olingan bo'laklar soni yuqorida yoziladi.", "Число взятых частей записывают сверху."]),
  S('test', ["Teskari topshiriq", "Обратное задание"],
    ["Kasrning surati 3, maxraji 8. Yozuvni tiklang.", "Числитель дроби 3, знаменатель 8. Восстанови запись."],
    'surat 3 · maxraj 8', ["Qaysi yozuv to'g'ri?", "Какая запись верна?"],
    [['3/8'], ['8/3'], ['3/5']], 0,
    ["Surat yuqorida, maxraj pastda.", "Числитель сверху, знаменатель снизу."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Ra'no 8 teng bo'lakdan 3 tasi bo'yalgan modelni 8/3 deb yozdi.", "Рано записала модель с 3 закрашенными частями из 8 как 8/3."],
    '■■■□□□□□ = 8/3 ✗', ["Xato nimada?", "В чём ошибка?"],
    [["Surat va maxraj almashgan", "Числитель и знаменатель поменяны местами"], ["Bo'laklar teng", "Части равны"], ["3 ta qism bo'yalgan", "Закрашены 3 части"]], 0,
    ["Olingan 3 yuqorida, jami 8 pastda turishi kerak.", "Взятые 3 должны быть сверху, все 8 — снизу."]),
  S('case', ["Ziyofatdagi kasr", "Дробь на празднике"],
    ["Patir 8 ta teng bo'lakka bo'lindi. Do'stlar 5 bo'lagini yedi.", "Лепёшку разделили на 8 равных частей. Друзья съели 5 частей."],
    '■■■■■□□□', ["Patirning qanday qismi yeyildi?", "Какая часть лепёшки съедена?"],
    [['3/8'], ['5/8'], ['5/3']], 1,
    ["Yeyilgan qismlar 5, jami qismlar 8.", "Съели 5 частей, всего было 8."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["Yangi modelda tasma 10 ta teng qismga bo'lingan va 7 qismi belgilangan.", "В новой модели полоска разделена на 10 равных частей, 7 отмечены."],
    '■■■■■■■□□□', ["Model va atamalar mos kelgan javobni tanlang.", "Выбери ответ, где модель и термины совпадают."],
    [["7/10; surat 7, maxraj 10", "7/10; числитель 7, знаменатель 10"], ["10/7; surat 10, maxraj 7", "10/7; числитель 10, знаменатель 7"], ["3/10; surat 3, maxraj 10", "3/10; числитель 3, знаменатель 10"]], 0,
    ["Belgilangan va jami qismlarni alohida sanang.", "Отдельно сосчитай отмеченные и все части."]),
  S('summary', ["Kasr belgisi ochildi", "Знак дроби открыт"],
    ["Siz teng ulush modelini kasr bilan yozdingiz, surat va maxrajning vazifasini tushuntirdingiz hamda modelni ikki yo'nalishda o'zgartirdingiz.", "Ты записал модель равных долей дробью, объяснил роль числителя и знаменателя и преобразовал модель в обе стороны."],
    'model ↔ surat/maxraj', ["Maxraj nimani ko'rsatadi?", "Что показывает знаменатель?"],
    [["Butundagi jami teng bo'laklarni", "Все равные части целого"], ["Faqat olingan bo'laklarni", "Только взятые части"], ["Butunlar sonini", "Число целых"]], 0,
    ["Maxraj kasr chizig'ining pastida va butunning bo'linishini ko'rsatadi.", "Знаменатель находится снизу и показывает деление целого."]),
];

export default function Dars25() {
  return (
    <Grade3LessonShell
      screens={SCREENS}
      titleUz="25-dars. Kasrlarning hosil bo'lishi"
      titleRu="Урок 25. Образование дробей"
    />
  );
}
