/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars19.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type, title: T(...title), text: T(...text), visual, ask: T(...ask),
  options: options.map(([uz, ru = uz]) => T(uz, ru)), correct, hint: T(...hint),
});

export const SCREENS = [
  S('hook', ["Bo'laklar bir butundan oshdi", "Частей стало больше целого"],
    ["Har bir patir 4 ta teng bo'lakka bo'lingan. Dasturxonda 5 ta chorak bo'lak bor — bu bitta patirdan ko'p.", "Каждую лепёшку разделили на 4 равные части. На столе 5 четвертей — это больше одной лепёшки."],
    '■■■■ + ■ = 5/4', ["5 ta chorak nechta butundan ko'p?", "Больше скольких целых составляют 5 четвертей?"],
    [["1 butundan", "Одного целого"], ["2 butundan", "Двух целых"], ["4 butundan", "Четырёх целых"]], 0,
    ["4 ta chorak bitta butun, yana 1 ta chorak ortadi.", "4 четверти составляют целое, остаётся ещё 1 четверть."]),
  S('exploration', ["Bir butun chegarasi", "Граница одного целого"],
    ["Maxraj 4 bo'lsa, 4/4 bitta butunga teng. Surat 4 dan kichik bo'lsa kasr butundan kichik, katta bo'lsa butundan katta.", "При знаменателе 4 дробь 4/4 равна одному целому. Если числитель меньше 4, дробь меньше целого; если больше — больше целого."],
    '3/4 < 4/4 = 1 < 5/4', ["Bitta butunga teng kasr qaysi?", "Какая дробь равна одному целому?"],
    [['3/4'], ['4/4'], ['5/4']], 1,
    ["Barcha to'rtta qism olingan yozuvni tanlang.", "Выбери запись, где взяты все четыре части."]),
  S('exploration', ["To'g'ri kasr", "Правильная дробь"],
    ["Surat maxrajdan kichik bo'lsa, kasr to'g'ri kasr deyiladi. U bitta butundan kichik.", "Если числитель меньше знаменателя, дробь называется правильной. Она меньше единицы."],
    '3/5: 3 < 5', ["Qaysi kasr to'g'ri?", "Какая дробь правильная?"],
    [['4/7'], ['7/4'], ['5/5']], 0,
    ["Surati maxrajidan kichik kasrni toping.", "Найди дробь, у которой числитель меньше знаменателя."]),
  S('exploration', ["Noto'g'ri kasr", "Неправильная дробь"],
    ["Surat maxrajga teng yoki undan katta bo'lsa, kasr noto'g'ri kasr deyiladi. U bir butunga teng yoki undan katta.", "Если числитель равен знаменателю или больше него, дробь называется неправильной. Она равна единице или больше неё."],
    '7/4: 7 > 4', ["Qaysi kasr noto'g'ri?", "Какая дробь неправильная?"],
    [['2/9'], ['5/8'], ['9/5']], 2,
    ["Surati maxrajidan katta yozuvga qarang.", "Посмотри на дробь с числителем больше знаменателя."]),
  S('exploration', ["Butun va qolgan ulush", "Целое и оставшаяся доля"],
    ["5/4 da to'rtta chorak bitta butunni hosil qiladi, yana bitta chorak qoladi.", "В дроби 5/4 четыре четверти составляют целое, остаётся ещё одна четверть."],
    '5/4 = 4/4 + 1/4 = 1 1/4', ["5/4 ning aralash yozuvi qaysi?", "Какова смешанная запись 5/4?"],
    [['1 1/4'], ['1 4/5'], ['2 1/4']], 0,
    ["Bitta butun va qolgan bitta chorakni yozing.", "Запиши одно целое и оставшуюся четверть."]),
  S('rule', ["Kasr turlari", "Виды дробей"],
    ["Surat < maxraj — to'g'ri kasr; surat ≥ maxraj — noto'g'ri kasr. Noto'g'ri kasr ichidagi to'liq butunlar ajratilsa, aralash son hosil bo'ladi.", "Числитель < знаменателя — правильная дробь; числитель ≥ знаменателя — неправильная. Если выделить целые из неправильной дроби, получится смешанное число."],
    '7/3 = 2 1/3', ["Aralash son nimalardan iborat?", "Из чего состоит смешанное число?"],
    [["Butun qism va to'g'ri kasrdan", "Из целой части и правильной дроби"], ["Ikki maxrajdan", "Из двух знаменателей"], ["Faqat noto'g'ri kasrdan", "Только из неправильной дроби"]], 0,
    ["2 1/3 yozuvidagi ikki turdagi qismga qarang.", "Посмотри на две части записи 2 1/3."]),
  S('test', ["Kasr turini aniqlang", "Определи вид дроби"],
    ["6/11 da surat 6, maxraj 11.", "В дроби 6/11 числитель 6, знаменатель 11."],
    '6 < 11', ["6/11 qaysi tur?", "Какого вида дробь 6/11?"],
    [["To'g'ri kasr", "Правильная дробь"], ["Noto'g'ri kasr", "Неправильная дробь"], ["Aralash son", "Смешанное число"]], 0,
    ["Surat maxrajdan kichik.", "Числитель меньше знаменателя."]),
  S('test', ["Chegara holati", "Граничный случай"],
    ["8/8 da surat va maxraj teng. Barcha sakkiz ulush olingan.", "В дроби 8/8 числитель и знаменатель равны. Взяты все восемь долей."],
    '8/8 = 1', ["8/8 qaysi turga kiradi?", "К какому виду относится 8/8?"],
    [["Noto'g'ri kasr", "Неправильная дробь"], ["To'g'ri kasr", "Правильная дробь"], ["Nol", "Ноль"]], 0,
    ["Surat maxrajga teng bo'lsa ham noto'g'ri kasr deyiladi.", "Если числитель равен знаменателю, дробь тоже неправильная."]),
  S('test', ["Butunlarni ajrating", "Выдели целые"],
    ["9/4 ichida ikkita to'liq 4/4 va yana 1/4 bor.", "В 9/4 содержатся два полных 4/4 и ещё 1/4."],
    '9/4 = 4/4 + 4/4 + 1/4', ["Aralash sonni tanlang.", "Выбери смешанное число."],
    [['1 1/4'], ['2 1/4'], ['2 4/1']], 1,
    ["Ikki butun va bitta chorakni yozing.", "Запиши два целых и одну четверть."]),
  S('exploration', ["Bo'lish orqali ajratish", "Выделение делением"],
    ["Suratni maxrajga bo'lamiz: bo'linma — butun qism, qoldiq — yangi surat, maxraj o'zgarmaydi.", "Делим числитель на знаменатель: частное — целая часть, остаток — новый числитель, знаменатель не меняется."],
    '11 : 3 = 3, qoldiq 2 → 11/3 = 3 2/3', ["11/3 ning butun qismi?", "Какова целая часть 11/3?"],
    [['2'], ['3'], ['11']], 1,
    ["11 ichida nechta to'liq 3 borligini toping.", "Найди, сколько полных троек в 11."]),
  S('test', ["Aralash songa aylantiring", "Преобразуй в смешанное число"],
    ["14/5 uchun 14 ni 5 ga bo'lamiz.", "Для 14/5 делим 14 на 5."],
    '14 : 5 = 2, qoldiq 4', ["To'g'ri natija qaysi?", "Каков верный результат?"],
    [['2 4/5'], ['4 2/5'], ['2 5/4']], 0,
    ["Bo'linma 2 — butun qism; qoldiq 4 — surat.", "Частное 2 — целая часть; остаток 4 — числитель."]),
  S('test', ["Aralash sondan kasrga", "Из смешанного числа в дробь"],
    ["2 1/3 da ikki butunning har birida 3 tadan uchdan bir bor, ustiga yana 1 ulush.", "В 2 1/3 в каждом из двух целых по три трети, плюс ещё одна доля."],
    '2 × 3 + 1 = 7', ["2 1/3 qaysi kasrga teng?", "Какой дроби равно 2 1/3?"],
    [['5/3'], ['7/3'], ['7/2']], 1,
    ["Butun qismni maxrajga ko'paytirib suratni qo'shing.", "Умножь целую часть на знаменатель и прибавь числитель."]),
  S('test', ["Son o'qidagi o'rin", "Место на числовом луче"],
    ["1 1/2 soni bir butundan katta, ikki butundan kichik va ularning aynan o'rtasida.", "Число 1 1/2 больше единицы, меньше двух и находится ровно посередине."],
    '1 ─── 1 1/2 ─── 2', ["1 1/2 qaysi ikki son orasida?", "Между какими числами находится 1 1/2?"],
    [["0 va 1", "0 и 1"], ["1 va 2", "1 и 2"], ["2 va 3", "2 и 3"]], 1,
    ["Aralash sonning butun qismiga qarang.", "Посмотри на целую часть смешанного числа."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Jasur 7/4 ni to'g'ri kasr dedi, chunki «4 kichik son».", "Жасур назвал 7/4 правильной дробью, потому что «4 — маленькое число»."],
    '7/4 → to‘g‘ri? ✗', ["Xato nimada?", "В чём ошибка?"],
    [["Surat va maxraj o'zaro solishtirilmagan", "Не сравнили числитель и знаменатель"], ["Maxraj 4 bo'lgan", "Знаменатель равен 4"], ["Kasr chizig'i bor", "Есть дробная черта"]], 0,
    ["7 surat 4 maxrajdan katta.", "Числитель 7 больше знаменателя 4."]),
  S('case', ["Ziyofatdagi patirlar", "Лепёшки на празднике"],
    ["Har biri 6 bo'lakka bo'lingan patirlardan 15 ta bo'lak qoldi.", "От лепёшек, разделённых на 6 частей каждая, осталось 15 частей."],
    '15/6 = ?', ["Qancha patir qoldi?", "Сколько лепёшек осталось?"],
    [['1 3/6'], ['2 3/6'], ['3 2/6']], 1,
    ["15 : 6 = 2, qoldiq 3.", "15 : 6 = 2, остаток 3."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["Yangi kasr 17/5 ni turga ajrating va aralash songa aylantiring.", "Определи вид дроби 17/5 и преобразуй её в смешанное число."],
    '17 : 5 = 3, qoldiq 2', ["To'g'ri javob qaysi?", "Какой ответ верный?"],
    [["Noto'g'ri kasr; 3 2/5", "Неправильная дробь; 3 2/5"], ["To'g'ri kasr; 2 3/5", "Правильная дробь; 2 3/5"], ["Noto'g'ri kasr; 5 2/3", "Неправильная дробь; 5 2/3"]], 0,
    ["17 > 5 va bo'lish natijasi 3 qoldiq 2.", "17 > 5, а результат деления — 3, остаток 2."]),
  S('summary', ["Butunlar ajratildi", "Целые выделены"],
    ["Siz to'g'ri va noto'g'ri kasrlarni surat–maxraj munosabati bilan ajratdingiz, noto'g'ri kasrni aralash songa va orqaga aylantirdingiz.", "Ты различил правильные и неправильные дроби по отношению числителя и знаменателя, преобразовал неправильную дробь в смешанное число и обратно."],
    'noto‘g‘ri kasr ↔ aralash son', ["Noto'g'ri kasrdan butun qism qanday topiladi?", "Как найти целую часть неправильной дроби?"],
    [["Suratni maxrajga bo'lish bilan", "Делением числителя на знаменатель"], ["Maxrajni suratga qo'shish bilan", "Сложением знаменателя и числителя"], ["Suratni ayirish bilan", "Вычитанием числителя"]], 0,
    ["Bo'linma butun qismni beradi.", "Частное даёт целую часть."]),
];

export default function Dars28() {
  return (
    <Grade3LessonShell
      screens={SCREENS}
      titleUz="28-dars. To'g'ri va noto'g'ri kasrlar. Aralash son"
      titleRu="Урок 28. Правильные и неправильные дроби. Смешанное число"
    />
  );
}
