/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars19.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type, title: T(...title), text: T(...text), visual, ask: T(...ask),
  options: options.map(([uz, ru = uz]) => T(uz, ru)), correct, hint: T(...hint),
});

export const SCREENS = [
  S('hook', ["Ziyofat zaxirasi", "Запас для праздника"],
    ["Bitda 36 ta nurli meva bor. Ularning 2/3 qismi ziyofatga ajratiladi, qolganlari zaxirada qoladi.", "У Бита 36 светящихся плодов. 2/3 выделяют на праздник, остальные оставляют в запасе."],
    '36 ning 2/3 qismi → ziyofat; qolgani → zaxira', ["Masalada avval nimani topish kerak?", "Что сначала нужно найти?"],
    [["Ziyofatga ajratilgan qismini", "Часть для праздника"], ["Barcha mevalarni yana sanash", "Пересчитать все плоды"], ["Kasr maxrajini", "Знаменатель дроби"]], 0,
    ["Qolganini topishdan oldin ishlatilgan qismni biling.", "До нахождения остатка узнай использованную часть."]),
  S('exploration', ["Ma'lum va so'ralgan", "Дано и вопрос"],
    ["Ma'lum: jami 36 ta, ziyofat ulushi 2/3. So'ralgan: zaxirada qolgan mevalar.", "Известно: всего 36, доля для праздника 2/3. Требуется: число плодов в запасе."],
    'jami 36 | ishlatilgan 2/3 | qolgan ?', ["Qaysi miqdor noma'lum?", "Какая величина неизвестна?"],
    [["Qolgan mevalar", "Оставшиеся плоды"], ["Jami mevalar", "Все плоды"], ["Ulush maxraji", "Знаменатель доли"]], 0,
    ["Savoldagi miqdorni ajrating.", "Выдели величину из вопроса."]),
  S('exploration', ["Ulush qismini topamiz", "Находим дробную часть"],
    ["36 ning 2/3 qismini topish uchun avval uchdan birini, keyin ikkita shunday ulushni olamiz.", "Чтобы найти 2/3 от 36, сначала находим одну треть, затем берём две такие доли."],
    '36 : 3 × 2 = 24', ["Ziyofatga nechta meva?", "Сколько плодов для праздника?"],
    [['12'], ['24'], ['27']], 1,
    ["36 : 3 = 12; 12 × 2 = 24.", "36 : 3 = 12; 12 × 2 = 24."]),
  S('exploration', ["Qolgan qismini topamiz", "Находим остаток"],
    ["Butun miqdordan ziyofatga ajratilgan miqdorni ayiramiz.", "Вычитаем из общего количества число плодов для праздника."],
    '36 − 24 = 12', ["Zaxirada nechta meva?", "Сколько плодов в запасе?"],
    [['12'], ['24'], ['60']], 0,
    ["Jami 36 dan ishlatilgan 24 ni ayiring.", "Вычти использованные 24 из 36."]),
  S('rule', ["Kasrli masala yo'li", "Путь решения задачи с дробью"],
    ["Ma'lum va so'ralganni ajratamiz; ulushni topish uchun sonni maxrajga bo'lib suratga ko'paytiramiz; kerak bo'lsa natijani butundan ayiramiz va birlik bilan tekshiramiz.", "Выделяем данные и вопрос; для нахождения части делим число на знаменатель и умножаем на числитель; при необходимости вычитаем результат из целого и проверяем единицу."],
    'butun : maxraj × surat → kerakli qism', ["Qolgan qism qaysi amal bilan topiladi?", "Каким действием находят оставшуюся часть?"],
    [["Butundan ma'lum qismni ayirish", "Вычесть известную часть из целого"], ["Butunni suratga qo'shish", "Прибавить числитель к целому"], ["Maxrajni ikki marta olish", "Удвоить знаменатель"]], 0,
    ["Qolgan = jami − ishlatilgan.", "Остаток = всего − использовано."]),
  S('test', ["Uzunlik masalasi", "Задача о длине"],
    ["28 metr kabelning 3/4 qismi ustaxonada ishlatildi.", "В мастерской использовали 3/4 кабеля длиной 28 метров."],
    '28 : 4 × 3', ["Necha metr ishlatildi?", "Сколько метров использовали?"],
    [['7 m'], ['21 m'], ['24 m']], 1,
    ["28 : 4 = 7; 7 × 3 = 21.", "28 : 4 = 7; 7 × 3 = 21."]),
  S('test', ["Qolgan uzunlik", "Оставшаяся длина"],
    ["28 metr kabelning 21 metri ishlatildi.", "Из 28 метров кабеля использовали 21 метр."],
    '28 − 21', ["Necha metr qoldi?", "Сколько метров осталось?"],
    [['7 m'], ['21 m'], ['49 m']], 0,
    ["Butun uzunlikdan ishlatilganini ayiring.", "Вычти использованную длину из общей."]),
  S('test', ["Vaqt masalasi", "Задача о времени"],
    ["60 daqiqalik ishning 1/5 qismi tekshiruvga sarflandi.", "На проверку ушла 1/5 от 60 минут работы."],
    '60 min : 5', ["Tekshiruv necha daqiqa?", "Сколько минут заняла проверка?"],
    [['5 min'], ['12 min'], ['20 min']], 1,
    ["Bir beshdan uchun 5 ga bo'ling.", "Для одной пятой раздели на 5."]),
  S('exploration', ["Butunni tiklash", "Восстанавливаем целое"],
    ["Agar sonning 1/4 qismi 8 bo'lsa, butun to'rtta shunday teng ulushdan iborat.", "Если 1/4 числа равна 8, целое состоит из четырёх таких равных долей."],
    '8 × 4 = 32', ["Butun miqdor qaysi?", "Каково целое количество?"],
    [['12'], ['24'], ['32']], 2,
    ["Bitta chorakni to'rt marta oling.", "Возьми одну четверть четыре раза."]),
  S('test', ["Ko'p ulushdan butun", "Целое по нескольким долям"],
    ["Bir miqdorning 3/5 qismi 18 ga teng. Avval bitta beshdan qismini topamiz: 18 : 3.", "3/5 некоторого количества равны 18. Сначала находим одну пятую: 18 : 3."],
    '18 : 3 = 6; 6 × 5 = ?', ["Butun miqdor nechta?", "Каково целое количество?"],
    [['24'], ['30'], ['36']], 1,
    ["Bitta beshdan 6; beshta ulush 30.", "Одна пятая равна 6; пять долей равны 30."]),
  S('test', ["Kasrlarni qo'shish masalasi", "Задача на сложение дробей"],
    ["Idish ertalab 2/10, tushda yana 5/10 qismga to'ldirildi.", "Утром сосуд заполнили на 2/10, днём ещё на 5/10."],
    '2/10 + 5/10', ["Idishning qancha qismi to'ldi?", "Какая часть сосуда заполнена?"],
    [['7/10'], ['7/20'], ['3/10']], 0,
    ["Bir xil maxraj saqlanadi, suratlar qo'shiladi.", "Одинаковый знаменатель сохраняется, числители складываются."]),
  S('test', ["O'nli kasrli vaziyat", "Ситуация с десятичной дробью"],
    ["Bir butun metr tasmaning 0,35 m qismi ishlatildi. 1,00 m dan ishlatilgan qismini ayiramiz.", "Из метровой ленты использовали 0,35 м. Вычитаем использованную часть из 1,00 м."],
    '1,00 − 0,35 = 0,65', ["Necha metr qoldi?", "Сколько метров осталось?"],
    [['0,35 m'], ['0,65 m'], ['1,35 m']], 1,
    ["Butun metr 1,00 ko'rinishida yoziladi.", "Целый метр записывается как 1,00."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Jasur 40 ning 3/8 qismini 40 : 3 × 8 deb hisobladi. U surat va maxraj vazifasini almashtirdi.", "Жасур вычислил 3/8 от 40 как 40 : 3 × 8. Он перепутал роли числителя и знаменателя."],
    '40 : 3 × 8 ✗', ["To'g'ri yozuv qaysi?", "Какая запись верна?"],
    [['40 : 8 × 3'], ['40 × 8 : 3'], ['40 − 8 × 3']], 0,
    ["Avval maxraj 8 ga bo'ling, keyin surat 3 ga ko'paytiring.", "Сначала раздели на знаменатель 8, затем умножь на числитель 3."]),
  S('case', ["Ziyofat va zaxira", "Праздник и запас"],
    ["48 ta mevadan 1/4 qismi ichimlikka, 3/8 qismi dasturxonga ishlatildi.", "Из 48 плодов 1/4 использовали для напитка, 3/8 — для стола."],
    '48 : 4 = 12; 48 : 8 × 3 = 18; 48 − 12 − 18', ["Zaxirada nechta meva?", "Сколько плодов осталось?"],
    [['16'], ['18'], ['30']], 1,
    ["Jami ishlatilgan 12 + 18 = 30; 48 − 30.", "Всего использовали 12 + 18 = 30; 48 − 30."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["72 ta kristallning 5/8 qismi panelga joylandi. Qolgan kristallar 3 ta teng qutiga bo'lindi.", "5/8 от 72 кристаллов поместили в панель. Остальные разделили поровну на 3 коробки."],
    '72 : 8 × 5 = 45; (72 − 45) : 3', ["Har qutida nechta kristall?", "Сколько кристаллов в каждой коробке?"],
    [['9'], ['15'], ['27']], 0,
    ["Qolgan 27 kristallni 3 ga bo'ling.", "Раздели оставшиеся 27 кристаллов на 3."]),
  S('summary', ["Ziyofat hisobi yakunlandi", "Расчёт праздника завершён"],
    ["Siz sonning kasr qismini topdingiz, qolganini hisoblab birlik bilan yozdingiz, ma'lum ulushdan butunni tikladingiz va ko'p qadamli vaziyatni tekshirdingiz.", "Ты нашёл дробную часть числа, вычислил остаток и записал единицу, восстановил целое по известной доле и проверил многошаговую ситуацию."],
    'model → ulush → qolgan/butun → tekshiruv', ["Javob qanday tekshiriladi?", "Как проверить ответ?"],
    [["Qismlar butunni qayta berishi bilan", "Части должны снова дать целое"], ["Suratni maxrajga qo'shish bilan", "Сложением числителя и знаменателя"], ["Faqat son kattaligiga qarab", "Только по размеру числа"]], 0,
    ["Ishlatilgan va qolgan qismlar jami miqdorga teng bo'lishi kerak.", "Использованная и оставшаяся части должны дать общее количество."]),
];

export default function Dars32() {
  return (
    <Grade3LessonShell
      screens={SCREENS}
      titleUz="32-dars. Ulush va kasrlarga oid masalalar"
      titleRu="Урок 32. Задачи на доли и дроби"
    />
  );
}
