/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars21.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type, title: T(...title), text: T(...text), visual, ask: T(...ask),
  options: options.map(([uz, ru = uz]) => T(uz, ru)), correct, hint: T(...hint),
});

export const SCREENS = [
  S('hook', ["Hosilni teng ulash", "Равное распределение урожая"],
    ["Bit 18 ta nurli mevadan uchdan birini dasturxonga qo'ymoqchi. Kasr bu safar shaklni emas, sonning bir qismini bildiradi.", "Бит хочет положить на стол треть от 18 светящихся плодов. Теперь дробь обозначает часть числа, а не фигуры."],
    '18 ning 1/3 qismi = ?', ["18 ta mevani avval nechta teng guruhga ajratamiz?", "На сколько равных групп сначала делим 18 плодов?"],
    [['2'], ['3'], ['18']], 1,
    ["Maxraj 3 teng guruh kerakligini ko'rsatadi.", "Знаменатель 3 показывает, что нужны три равные группы."]),
  S('exploration', ["Maxraj yo'l ko'rsatadi", "Знаменатель указывает путь"],
    ["1/3 da maxraj 3. Demak 18 ni 3 ta teng guruhga bo'lamiz.", "В дроби 1/3 знаменатель равен 3. Значит, делим 18 на 3 равные группы."],
    '18 : 3 = 6', ["Bitta guruhda nechta meva?", "Сколько плодов в одной группе?"],
    [['3'], ['6'], ['9']], 1,
    ["18 ni 3 ga bo'ling.", "Раздели 18 на 3."]),
  S('exploration', ["Surat nechta ulush olinishini aytadi", "Числитель показывает число долей"],
    ["1/3 da surat 1. Uch teng guruhdan bittasini olamiz: 6 ta meva.", "В дроби 1/3 числитель равен 1. Берём одну из трёх равных групп: 6 плодов."],
    '18 ning 1/3 qismi = 6', ["Nechta guruh olindi?", "Сколько групп взяли?"],
    [['1'], ['3'], ['6']], 0,
    ["Suratga qarang.", "Посмотри на числитель."]),
  S('exploration', ["Chorakni topamiz", "Находим четверть"],
    ["20 ning choragini topish uchun 20 ni 4 ta teng guruhga ajratamiz.", "Чтобы найти четверть от 20, делим 20 на 4 равные группы."],
    '20 : 4 = 5', ["20 ning 1/4 qismi nechta?", "Чему равна 1/4 от 20?"],
    [['4'], ['5'], ['10']], 1,
    ["Chorak — to'rtta teng qismdan bittasi.", "Четверть — одна из четырёх равных частей."]),
  S('rule', ["Sonning birlik ulushi", "Единичная доля числа"],
    ["Sonning 1/b qismini topish uchun sonni maxraj b ga bo'lamiz. Javob boshlang'ich kattalikning birligini saqlaydi.", "Чтобы найти 1/b числа, делим число на знаменатель b. Ответ сохраняет единицу исходной величины."],
    'N ning 1/b qismi = N : b', ["36 ning 1/6 qismini qaysi amal topadi?", "Какое действие найдёт 1/6 от 36?"],
    [['36 : 6'], ['36 × 6'], ['36 − 6']], 0,
    ["Maxrajga bo'ling.", "Раздели на знаменатель."]),
  S('test', ["Yarmini toping", "Найди половину"],
    ["42 ta kristallning yarmini topamiz.", "Найдём половину 42 кристаллов."],
    '42 : 2 = ?', ["42 ning 1/2 qismi nechta?", "Чему равна 1/2 от 42?"],
    [['20'], ['21'], ['22']], 1,
    ["Yarim uchun 2 ga bo'ling.", "Для половины раздели на 2."]),
  S('test', ["Uchdan birni toping", "Найди треть"],
    ["27 metr tasmaning uchdan birini topamiz.", "Найдём треть ленты длиной 27 метров."],
    '27 m : 3', ["Natijani birlik bilan tanlang.", "Выбери ответ с единицей."],
    [['9 m'], ['9 ta'], ['24 m']], 0,
    ["27 ni 3 ga bo'ling va metr birligini saqlang.", "Раздели 27 на 3 и сохрани единицу «метр»."]),
  S('test', ["Oltidan bir", "Одна шестая"],
    ["48 daqiqaning oltidan biri bitta teng vaqt ulushidir.", "Одна шестая от 48 минут — одна равная доля времени."],
    '48 min : 6', ["Necha daqiqa?", "Сколько минут?"],
    [['6'], ['8'], ['12']], 1,
    ["6 × 8 = 48 tengligini ishlating.", "Используй равенство 6 × 8 = 48."]),
  S('exploration', ["Bir nechta ulush", "Несколько долей"],
    ["24 ning 3/4 qismini topishda avval bitta chorakni topamiz, keyin uchta shunday ulushni olamiz.", "Чтобы найти 3/4 от 24, сначала находим одну четверть, затем берём три такие доли."],
    '24 : 4 = 6; 6 × 3 = 18', ["24 ning 3/4 qismi nechta?", "Чему равны 3/4 от 24?"],
    [['6'], ['18'], ['32']], 1,
    ["Bitta ulush 6; surat 3 bo'lgani uchun uni 3 marta oling.", "Одна доля равна 6; числитель 3, поэтому возьми её 3 раза."]),
  S('rule', ["Ko'p ulush qoidasi", "Правило нескольких долей"],
    ["Sonning a/b qismini topish uchun sonni b ga bo'lib, natijani a ga ko'paytiramiz.", "Чтобы найти a/b числа, делим число на b и умножаем результат на a."],
    'N : maxraj × surat', ["35 ning 2/5 qismi uchun qaysi yozuv?", "Какая запись найдёт 2/5 от 35?"],
    [['35 : 5 × 2'], ['35 : 2 × 5'], ['35 − 5 × 2']], 0,
    ["Avval maxrajga bo'ling, keyin suratga ko'paytiring.", "Сначала раздели на знаменатель, затем умножь на числитель."]),
  S('test', ["Ikki beshdan", "Две пятых"],
    ["35 ning beshdan biri 7. Ikki beshdan — ikkita shunday ulush.", "Одна пятая от 35 равна 7. Две пятых — две такие доли."],
    '35 : 5 × 2', ["Natijani toping.", "Найди результат."],
    [['7'], ['14'], ['17']], 1,
    ["7 ni 2 ga ko'paytiring.", "Умножь 7 на 2."]),
  S('test', ["Teskari masala", "Обратная задача"],
    ["Bir sonning 1/4 qismi 9 ga teng. To'rtta teng ulush butun sonni tiklaydi.", "Четверть числа равна 9. Четыре равные доли восстанавливают целое число."],
    '9 × 4 = ?', ["Butun son qaysi?", "Каково целое число?"],
    [['13'], ['27'], ['36']], 2,
    ["Bitta chorakni 4 marta oling.", "Возьми одну четверть четыре раза."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Anvar 32 ning 1/4 qismini topishda 32 − 4 = 28 deb yozdi.", "Анвар, находя 1/4 от 32, записал 32 − 4 = 28."],
    '32 ning 1/4 qismi = 28 ✗', ["Qaysi amal kerak edi?", "Какое действие было нужно?"],
    [["32 : 4"], ["32 × 4"], ["32 + 4"]], 0,
    ["Ulush teng guruhlarga bo'lish bilan topiladi.", "Долю находят делением на равные группы."]),
  S('case', ["Hosil masalasi", "Задача об урожае"],
    ["Bog'da 45 ta nurli meva pishdi. Hosilning 2/5 qismi ziyofatga, qolgani zaxiraga ajratildi.", "В саду созрело 45 светящихся плодов. 2/5 урожая выделили на праздник, остальное — в запас."],
    '45 : 5 × 2 = 18; 45 − 18 = ?', ["Zaxirada nechta meva?", "Сколько плодов осталось в запасе?"],
    [['18'], ['27'], ['36']], 1,
    ["Ziyofat ulushini butun hosildan ayiring.", "Вычти праздничную долю из всего урожая."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["Yangi vaziyat: 56 metr kabelning 3/7 qismi ishlatildi.", "Новая ситуация: использовали 3/7 кабеля длиной 56 метров."],
    '56 : 7 × 3', ["Necha metr kabel ishlatildi?", "Сколько метров кабеля использовали?"],
    [['8 m'], ['21 m'], ['24 m']], 2,
    ["56 : 7 = 8, so'ng 8 × 3.", "56 : 7 = 8, затем 8 × 3."]),
  S('summary', ["Ulush hisoblandi", "Доля вычислена"],
    ["Siz maxraj orqali bitta ulushni, surat orqali kerakli ulushlar sonini topdingiz; teskari va ikki qadamli masalalarda natijani tekshirdingiz.", "Ты нашёл одну долю по знаменателю и нужное число долей по числителю, проверил результат в обратной и двухшаговой задачах."],
    'son : maxraj × surat', ["Amallar tartibi qaysi?", "Каков порядок действий?"],
    [["Avval bo'lish, keyin ko'paytirish", "Сначала деление, затем умножение"], ["Avval ko'paytirish, keyin ayirish", "Сначала умножение, затем вычитание"], ["Faqat qo'shish", "Только сложение"]], 0,
    ["Bitta ulushni topmasdan bir necha ulushni ola olmaysiz.", "Нельзя взять несколько долей, не найдя сначала одну."]),
];

export default function Dars30() {
  return (
    <Grade3LessonShell
      screens={SCREENS}
      titleUz="30-dars. Sonning ulushini topish"
      titleRu="Урок 30. Нахождение доли числа"
    />
  );
}
