/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars21.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type, title: T(...title), text: T(...text), visual, ask: T(...ask),
  options: options.map(([uz, ru = uz]) => T(uz, ru)), correct, hint: T(...hint),
});

export const SCREENS = [
  S('hook', ["O'nli shkala", "Десятичная шкала"],
    ["Bit bir metrli tasmani 10 ta teng qismga bo'ldi. Uchta qism 3/10 metr, lekin terminal buni qisqaroq 0,3 m deb yozadi.", "Бит разделил метровую ленту на 10 равных частей. Три части — это 3/10 метра, но терминал записывает короче: 0,3 м."],
    '3/10 = 0,3', ["0,3 dagi 3 qaysi ulushlarni sanaydi?", "Какие доли считает цифра 3 в числе 0,3?"],
    [["O'ndan birlarni", "Десятые"], ["Butunlarni", "Целые"], ["Yuzliklarni", "Сотни"]], 0,
    ["Verguldan keyingi birinchi xona o'ndan birlar xonasi.", "Первый разряд после запятой — десятые."]),
  S('exploration', ["Vergul chegarasi", "Граница запятой"],
    ["O'nli vergul butun qismni kasr qismidan ajratadi. 2,4 da 2 ta butun va 4 ta o'ndan bir bor.", "Десятичная запятая отделяет целую часть от дробной. В числе 2,4 — 2 целых и 4 десятых."],
    '2 | , | 4\nbutun   o‘ndan bir', ["2,4 ning butun qismi qaysi?", "Какова целая часть числа 2,4?"],
    [['2'], ['4'], ['24']], 0,
    ["Vergulning chap tomoniga qarang.", "Посмотри слева от запятой."]),
  S('exploration', ["O'ndan birlar", "Десятые"],
    ["Bir butun 10 ta teng qismga bo'linsa, har qism 1/10 = 0,1. Yetti shunday qism 0,7.", "Если целое разделить на 10 равных частей, каждая часть — 1/10 = 0,1. Семь таких частей — 0,7."],
    '■■■■■■■□□□ = 7/10 = 0,7', ["7/10 ning o'nli yozuvi?", "Десятичная запись 7/10?"],
    [['0,07'], ['0,7'], ['7,0']], 1,
    ["Maxraj 10 bo'lsa, verguldan keyin bitta xona kerak.", "При знаменателе 10 после запятой нужен один разряд."]),
  S('exploration', ["Yuzdan birlar", "Сотые"],
    ["Bir butun 100 ta teng katakka bo'linsa, har katak 1/100 = 0,01. 25 ta katak 0,25.", "Если целое разделить на 100 равных клеток, каждая клетка — 1/100 = 0,01. 25 клеток — 0,25."],
    '25/100 = 0,25', ["0,25 da yuzdan birlar raqami qaysi?", "Какая цифра стоит в разряде сотых числа 0,25?"],
    [['0'], ['2'], ['5']], 2,
    ["Verguldan keyingi ikkinchi xona yuzdan birlar.", "Второй разряд после запятой — сотые."]),
  S('exploration', ["Razryad jadvali", "Таблица разрядов"],
    ["Har raqamning qiymati o'rniga bog'liq: birlik, o'ndan bir, yuzdan bir.", "Значение каждой цифры зависит от места: единицы, десятые, сотые."],
    'birlik | , | o‘ndan bir | yuzdan bir\n   3       ,       4              7', ["3,47 da 4 ning qiymati?", "Каково значение цифры 4 в числе 3,47?"],
    [["4 o'ndan bir", "4 десятых"], ["4 yuzdan bir", "4 сотых"], ["4 birlik", "4 единицы"]], 0,
    ["4 verguldan keyingi birinchi xonada.", "4 стоит в первом разряде после запятой."]),
  S('rule', ["O'nli yozuv qoidasi", "Правило десятичной записи"],
    ["Vergul chapda butunlarni, o'ngda o'ndan va yuzdan birlarni ajratadi. Maxraj 10 bo'lsa bir, 100 bo'lsa ikki kasr xonasi yoziladi.", "Запятая отделяет целые слева от десятых и сотых справа. При знаменателе 10 записывают один дробный разряд, при 100 — два."],
    'a/10 → 0,a     ab/100 → 0,ab', ["9/100 qanday yoziladi?", "Как записать 9/100?"],
    [['0,9'], ['0,09'], ['9,00']], 1,
    ["Yuzdan birlar uchun ikki xona kerak; o'ndan birlar xonasini nol saqlaydi.", "Для сотых нужны два разряда; место десятых сохраняет ноль."]),
  S('test', ["O'nli kasrni o'qing", "Прочитай десятичную дробь"],
    ["1,6 sonida bitta butun va oltita o'ndan bir bor.", "В числе 1,6 одна целая и шесть десятых."],
    '1,6', ["To'g'ri o'qilishi qaysi?", "Как прочитать верно?"],
    [["Bir butun o'ndan olti", "Одна целая шесть десятых"], ["O'n olti", "Шестнадцать"], ["Bir yuzdan olti", "Одна целая шесть сотых"]], 0,
    ["Vergulning ikki tomonidagi razryadlarni nomlang.", "Назови разряды по обе стороны запятой."]),
  S('test', ["So'zdan yozuvga", "От слов к записи"],
    ["«Ikki butun yuzdan besh»da yuzdan birlar xonasida 5, o'ndan birlar xonasida nol turadi.", "В числе «две целых пять сотых» в разряде сотых стоит 5, а в разряде десятых — ноль."],
    'ikki butun yuzdan besh', ["Raqamli yozuvni tanlang.", "Выбери запись цифрами."],
    [['2,5'], ['2,05'], ['2,50']], 1,
    ["Yuzdan besh — 0,05.", "Пять сотых — это 0,05."]),
  S('test', ["Oddiy kasrdan o'nliga", "Из обыкновенной дроби в десятичную"],
    ["43/100 da 4 ta o'ndan bir va 3 ta yuzdan bir bor.", "В 43/100 — 4 десятых и 3 сотых."],
    '43/100', ["O'nli yozuv qaysi?", "Какая десятичная запись верна?"],
    [['0,43'], ['4,3'], ['0,043']], 0,
    ["Maxraj 100 — verguldan keyin ikki raqam.", "Знаменатель 100 — две цифры после запятой."]),
  S('test', ["Nol o'rinni saqlaydi", "Ноль сохраняет место"],
    ["0,4 va 0,04 bir xil emas. Birinchisi 4 ta o'ndan bir, ikkinchisi 4 ta yuzdan bir.", "0,4 и 0,04 не равны. Первое — 4 десятых, второе — 4 сотых."],
    '0,4 = 40/100      0,04 = 4/100', ["Qaysi son katta?", "Какое число больше?"],
    [['0,4'], ['0,04'], ["Teng", "Равны"]], 0,
    ["40 ta yuzdan bir 4 ta yuzdan birdan katta.", "40 сотых больше 4 сотых."]),
  S('exploration', ["Taqqoslash: butun qism", "Сравнение: целая часть"],
    ["O'nli kasrlarni chapdan o'ngga taqqoslaymiz. Avval butun qismlar ko'riladi.", "Десятичные дроби сравнивают слева направо. Сначала сравнивают целые части."],
    '3,12  ?  2,98', ["Qaysi son katta?", "Какое число больше?"],
    [['3,12'], ['2,98'], ["Teng", "Равны"]], 0,
    ["3 ta butun 2 ta butundan katta.", "3 целых больше 2 целых."]),
  S('test', ["Taqqoslash: kasr qismi", "Сравнение: дробная часть"],
    ["Butun qismlar teng bo'lsa, avval o'ndan birlar, keyin yuzdan birlar taqqoslanadi.", "Если целые части равны, сравнивают сначала десятые, затем сотые."],
    '1,37  ?  1,42', ["Belgini tanlang.", "Выбери знак."],
    [['>'], ['<'], ['=']], 1,
    ["O'ndan birlar xonasida 3 < 4.", "В разряде десятых 3 < 4."]),
  S('test', ["Oxirgi nol", "Конечный ноль"],
    ["0,5 va 0,50 bir xil miqdorni bildiradi. Oxiriga yozilgan nol qiymatni o'zgartirmaydi.", "0,5 и 0,50 обозначают одну величину. Ноль в конце дробной части не меняет значение."],
    '0,5 = 5/10 = 50/100 = 0,50', ["Qaysi belgi kerak: 0,5 □ 0,50?", "Какой знак нужен: 0,5 □ 0,50?"],
    [['>'], ['<'], ['=']], 2,
    ["Ikkalasini yuzdan birlarda yozing.", "Запиши оба числа в сотых."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Jasur 0,08 > 0,7 dedi, chunki 8 > 7. U raqamlarning razryadini hisobga olmadi.", "Жасур сказал, что 0,08 > 0,7, потому что 8 > 7. Он не учёл разряды цифр."],
    '0,08 > 0,7 ✗', ["To'g'ri taqqoslash qaysi?", "Какое сравнение верно?"],
    [['0,08 < 0,7'], ['0,08 > 0,7'], ['0,08 = 0,7']], 0,
    ["0,7 = 0,70; endi 8 yuzdan birni 70 yuzdan bir bilan solishtiring.", "0,7 = 0,70; сравни 8 сотых и 70 сотых."]),
  S('case', ["O'nli shkala masalasi", "Задача с десятичной шкалой"],
    ["Ra'no 1,25 m, Zuhra 1,4 m tasma ishlatdi.", "Рано использовала 1,25 м ленты, Зухра — 1,4 м."],
    '1,25 m  ?  1,40 m', ["Kim ko'proq tasma ishlatdi?", "Кто использовал больше ленты?"],
    [["Zuhra", "Зухра"], ["Ra'no", "Рано"], ["Teng", "Поровну"]], 0,
    ["1,4 ni 1,40 qilib yozib yuzdan birlargacha taqqoslang.", "Запиши 1,4 как 1,40 и сравни до сотых."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["Model 2 ta butun, 3 ta o'ndan bir va 6 ta yuzdan birni ko'rsatadi.", "Модель показывает 2 целых, 3 десятых и 6 сотых."],
    '2 + 0,3 + 0,06', ["Yozuv va taqqoslash to'g'ri bo'lgan javobni tanlang.", "Выбери верную запись и сравнение."],
    [['2,36 > 2,29'], ['2,36 < 2,4'], ['Har ikkala xulosa to\'g\'ri', 'Оба вывода верны']], 2,
    ["2,36 ni 2,29 va 2,40 bilan razryadma-razryad solishtiring.", "Сравни 2,36 с 2,29 и 2,40 по разрядам."]),
  S('summary', ["O'nli shkala o'qildi", "Десятичная шкала прочитана"],
    ["Siz oddiy kasr modelini o'nli yozuvga o'tkazdingiz, vergul va nolning vazifasini tushuntirdingiz hamda sonlarni razryadma-razryad taqqosladingiz.", "Ты преобразовал модель обыкновенной дроби в десятичную запись, объяснил роль запятой и нуля и сравнил числа по разрядам."],
    'butun | , | o‘ndan bir | yuzdan bir', ["Taqqoslash qayerdan boshlanadi?", "С чего начинается сравнение?"],
    [["Eng katta chap razryaddan", "С самого старшего левого разряда"], ["Yuzdan birlardan", "С сотых"], ["Raqamlar yig'indisidan", "С суммы цифр"]], 0,
    ["Sonlar chapdan o'ngga, birinchi farqli razryadgacha taqqoslanadi.", "Числа сравнивают слева направо до первого различающегося разряда."]),
];

export default function Dars34() {
  return (
    <Grade3LessonShell
      screens={SCREENS}
      titleUz="34-dars. O'nli kasrlarni o'qish, yozish va taqqoslash"
      titleRu="Урок 34. Чтение, запись и сравнение десятичных дробей"
    />
  );
}
