/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars19.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type, title: T(...title), text: T(...text), visual, ask: T(...ask),
  options: options.map(([uz, ru = uz]) => T(uz, ru)), correct, hint: T(...hint),
});

export const SCREENS = [
  S('hook', ["Ziyofatdagi teng taqsim", "Равное деление на празднике"],
    ["Bit bitta patirni Ra'no va Zuhraga adolatli bo'lib bermoqchi. Bo'laklar teng bo'lmasa, ulushlar ham teng bo'lmaydi.", "Бит хочет справедливо разделить одну лепёшку между Рано и Зухрой. Если части не равны, доли тоже не равны."],
    '●  →  ◐ + ◑', ["Adolatli taqsimda bo'laklar qanday?", "Какими должны быть части при справедливом делении?"],
    [["Teng", "Равными"], ["Har xil", "Разными"], ["Faqat katta", "Только большими"]], 0,
    ["Har bir bola butunning bir xil qismini olishi kerak.", "Каждый ребёнок должен получить одинаковую часть целого."]),
  S('exploration', ["Butun va bo'lak", "Целое и часть"],
    ["Bo'linishdan oldingi patir — butun. Uni hosil qilgan teng qismlarning har biri butunning ulushi.", "Лепёшка до деления — целое. Каждая равная часть, из которых оно состоит, — доля целого."],
    'BUTUN = teng bo‘laklar yig‘indisi', ["Qaysi so'z to'liq predmetni bildiradi?", "Какое слово обозначает полный предмет?"],
    [["Butun", "Целое"], ["Ulush", "Доля"], ["Chorak", "Четверть"]], 0,
    ["Predmet hali bo'linmagan holatni eslang.", "Вспомни предмет до деления."]),
  S('exploration', ["Yarim", "Половина"],
    ["Butunni ikkita teng bo'lakka bo'lsak, har bir bo'lak yarim deyiladi.", "Если разделить целое на две равные части, каждая часть называется половиной."],
    '1 butun → 2 ta teng yarim', ["Bitta butunda nechta yarim bor?", "Сколько половин в одном целом?"],
    [['1'], ['2'], ['4']], 1,
    ["Ikki yarim bir butunni tiklaydi.", "Две половины составляют одно целое."]),
  S('exploration', ["Uchdan bir", "Одна треть"],
    ["Butunni uchta teng bo'lakka bo'lsak, har bir bo'lak uchdan bir ulush bo'ladi.", "Если разделить целое на три равные части, каждая часть будет одной третью."],
    '1 butun → 3 ta teng bo‘lak', ["Har bir bo'lak qanday ataladi?", "Как называется каждая часть?"],
    [["Uchdan bir", "Одна треть"], ["Yarim", "Половина"], ["Chorak", "Четверть"]], 0,
    ["Bo'lak nomi teng qismlar soniga bog'liq.", "Название доли зависит от числа равных частей."]),
  S('exploration', ["Chorak", "Четверть"],
    ["Butunni to'rtta teng bo'lakka bo'lsak, har bir bo'lak chorak deyiladi.", "Если разделить целое на четыре равные части, каждая часть называется четвертью."],
    '1 butun → 4 ta chorak', ["Bir butunni nechta chorak tiklaydi?", "Сколько четвертей составляют целое?"],
    [['2'], ['3'], ['4']], 2,
    ["Barcha to'rtta teng bo'lakni birlashtiring.", "Соедини все четыре равные части."]),
  S('rule', ["Ulush qoidasi", "Правило доли"],
    ["Ulush hosil qilish uchun butun teng bo'laklarga ajratiladi. Bo'laklar soni ulush nomini belgilaydi: 2 — yarim, 3 — uchdan bir, 4 — chorak.", "Чтобы получить долю, целое делят на равные части. Число частей задаёт название: 2 — половина, 3 — треть, 4 — четверть."],
    'butun : teng bo‘laklar soni = bitta ulush', ["Tenglik nega muhim?", "Почему важно равенство частей?"],
    [["Ulushlar bir xil bo'lishi uchun", "Чтобы доли были одинаковыми"], ["Bo'laklar chiroyli bo'lishi uchun", "Чтобы части были красивыми"], ["Son kattalashishi uchun", "Чтобы число увеличилось"]], 0,
    ["Ulushlar faqat teng qismlardan hosil bo'ladi.", "Доли получают только из равных частей."]),
  S('test', ["Shaklning yarmini toping", "Найди половину фигуры"],
    ["Sakkizta teng katakdan iborat tasmaning yarmini ajratamiz.", "Выделим половину полоски из восьми равных клеток."],
    '■■■■□□□□', ["8 katakning yarmi nechta?", "Сколько клеток составляет половина от 8?"],
    [['2'], ['4'], ['6']], 1,
    ["8 ni 2 ta teng qismga bo'ling.", "Раздели 8 на 2 равные части."]),
  S('test', ["Uchdan birni toping", "Найди одну треть"],
    ["12 ta nurli meva 3 ta teng savatga taqsimlanadi. Bitta savat jami miqdorning uchdan birini oladi.", "12 светящихся плодов делят поровну на 3 корзины. Одна корзина получает треть общего количества."],
    '12 : 3 = ?', ["12 ning uchdan biri nechta?", "Чему равна треть от 12?"],
    [['3'], ['4'], ['6']], 1,
    ["Jami miqdorni 3 ga bo'ling.", "Раздели общее количество на 3."]),
  S('test', ["Chorakni toping", "Найди четверть"],
    ["20 ta kristall 4 ta teng tokchaga joylandi. Bir tokchadagi miqdor 20 ning choragi.", "20 кристаллов поровну разложили на 4 полки. Количество на одной полке — четверть от 20."],
    '20 : 4 = ?', ["20 ning choragi nechta?", "Чему равна четверть от 20?"],
    [['4'], ['5'], ['10']], 1,
    ["Chorak uchun 4 ta teng qism kerak.", "Для четверти нужны 4 равные части."]),
  S('exploration', ["Ulush va kattalik", "Доля величины"],
    ["Faqat predmetlar emas, uzunlik va vaqt ham teng ulushlarga ajraladi. 18 metrning yarmi 9 metr.", "На равные доли делятся не только предметы, но и длина и время. Половина 18 метров — 9 метров."],
    '18 m : 2 = 9 m', ["Javob birligi qaysi?", "Какая единица в ответе?"],
    [["Metr", "Метр"], ["Daqiqa", "Минута"], ["Kilogramm", "Килограмм"]], 0,
    ["Boshlang'ich kattalik uzunlik edi.", "Исходная величина была длиной."]),
  S('test', ["Vaqtning ulushi", "Доля времени"],
    ["Bir soat 60 daqiqa. Yarim soat — 60 daqiqaning yarmi.", "Один час — 60 минут. Полчаса — половина 60 минут."],
    '60 min : 2', ["Yarim soat necha daqiqa?", "Сколько минут в половине часа?"],
    [['20'], ['30'], ['40']], 1,
    ["60 ni ikki teng qismga bo'ling.", "Раздели 60 на две равные части."]),
  S('test', ["Teskari topshiriq", "Обратное задание"],
    ["Bir sonning choragi 6 ga teng. To'rtta shunday ulush butun sonni hosil qiladi.", "Четверть числа равна 6. Четыре такие доли составляют целое число."],
    '6 × 4 = ?', ["Butun sonni toping.", "Найди целое число."],
    [['10'], ['18'], ['24']], 2,
    ["Bitta chorakni 4 marta oling.", "Возьми одну четверть 4 раза."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Jasur to'rt teng bo'lmagan bo'lakdan birini chorak deb atadi.", "Жасур назвал четвертью одну из четырёх неравных частей."],
    '▰ | ▱ | ▱ | ▱', ["Xato nimada?", "В чём ошибка?"],
    [["Bo'laklar teng emas", "Части не равны"], ["Bo'laklar soni 4", "Частей четыре"], ["Butun mavjud", "Есть целое"]], 0,
    ["Chorak faqat to'rtta teng qismdan biri.", "Четверть — одна из четырёх равных частей."]),
  S('case', ["Ziyofat masalasi", "Задача о празднике"],
    ["24 ta mevaning uchdan biri dasturxonga qo'yildi, qolganlari zaxirada qoldi.", "Треть из 24 плодов положили на стол, остальные оставили в запасе."],
    '24 : 3 = 8; 24 − 8 = ?', ["Zaxirada nechta meva qoldi?", "Сколько плодов осталось в запасе?"],
    [['8'], ['16'], ['21']], 1,
    ["Avval uchdan birini topib, butundan ayiring.", "Сначала найди треть, затем вычти её из целого."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["Yangi vaziyat: 28 metr tasmaning choragi ishlatildi.", "Новая ситуация: использовали четверть ленты длиной 28 метров."],
    '28 m : 4', ["Necha metr tasma ishlatildi?", "Сколько метров ленты использовали?"],
    [['6 m'], ['7 m'], ['14 m']], 1,
    ["Chorak uchun 28 ni 4 ga bo'ling.", "Для четверти раздели 28 на 4."]),
  S('summary', ["Teng taqsim yakunlandi", "Равное деление завершено"],
    ["Siz butun va ulushni farqladingiz, yarim, uchdan bir va chorakni modelda ko'rsatdingiz hamda kattalikning ulushini bo'lish orqali topdingiz.", "Ты различил целое и долю, показал половину, треть и четверть на модели и нашёл долю величины делением."],
    'butun → teng qismlar → ulush', ["Ulushning asosiy belgisi nima?", "Главный признак доли?"],
    [["Teng bo'lakdan hosil bo'lishi", "Получена из равных частей"], ["Doim dumaloq bo'lishi", "Всегда круглая"], ["Doim kichik son bo'lishi", "Всегда маленькое число"]], 0,
    ["Bo'laklar teng bo'lmasa, ulush aniqlanmaydi.", "Если части не равны, доля не определена."]),
];

export default function Dars24() {
  return (
    <Grade3LessonShell
      screens={SCREENS}
      titleUz="24-dars. Kattalik ulushi"
      titleRu="Урок 24. Доля величины"
    />
  );
}
