/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars19.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type,
  title: T(title[0], title[1]),
  text: T(text[0], text[1]),
  visual,
  ask: T(ask[0], ask[1]),
  options: options.map(([uz, ru = uz]) => T(uz, ru)),
  correct,
  hint: T(hint[0], hint[1]),
});

export const SCREENS = [
  S('hook', ["Ustun terminali", "Терминал столбиком"],
    ["Ustaxonada katta hisoblar ko'paydi. Bit 34 × 6 ni tez va ishonchli yozish usulini izlayapti.", "В мастерской стало больше вычислений. Бит ищет быстрый и надёжный способ записать 34 × 6."],
    '34 × 6 = ?', ["34 ni avval qanday joylaymiz?", "Как сначала записать 34?"],
    [["O'nlik va birlik xonalariga", "По разрядам десятков и единиц"], ["Raqamlarni aralashtirib", "В случайном порядке"], ["Faqat 3 ni yozib", "Записать только 3"]], 0,
    ["Har raqam o'z razryadida turadi.", "Каждая цифра стоит в своём разряде."]),
  S('exploration', ["Razryadlarni tekislaymiz", "Выравниваем разряды"],
    ["Ko'paytiruvchi 6 birliklar ostiga yoziladi. Hisob birliklardan boshlanadi.", "Множитель 6 записывают под единицами. Вычисление начинают с единиц."],
    '  34\n×  6\n────', ["6 qaysi raqam ostida turadi?", "Под какой цифрой стоит 6?"],
    [["4 ostida", "Под 4"], ["3 ostida", "Под 3"], ["Ikkalasining orasida", "Между ними"]], 0,
    ["6 — birlik, shuning uchun birlik ostida.", "6 — единицы, поэтому стоит под единицами."]),
  S('exploration', ["Birliklarni ko'paytiramiz", "Умножаем единицы"],
    ["6 × 4 = 24. 4 birlikni yozamiz, 2 o'nlikni keyingi xonaga o'tkazamiz.", "6 × 4 = 24. Пишем 4 единицы, 2 десятка переносим в следующий разряд."],
    "6 × 4 = 24  →  4 yoz, 2 o'tkaz", ["Natijaning birlik raqami qaysi?", "Какая цифра единиц в результате?"],
    [['4'], ['2'], ['6']], 0, ["24 ning birlik raqamiga qarang.", "Посмотри на цифру единиц числа 24."]),
  S('exploration', ["O'nliklarni hisoblaymiz", "Считаем десятки"],
    ["6 × 3 o'nlik = 18 o'nlik. O'tgan 2 o'nlikni qo'shsak 20 o'nlik bo'ladi.", "6 × 3 десятка = 18 десятков. Прибавляем 2 перенесённых десятка и получаем 20 десятков."],
    '18 + 2 = 20 o‘nlik', ["34 × 6 natijasi?", "Результат 34 × 6?"],
    [['184'], ['204'], ['224']], 1, ["4 birlik va 20 o'nlikni birlashtiring.", "Соедини 4 единицы и 20 десятков."]),
  S('rule', ["Yozma ko'paytirish qoidasi", "Правило письменного умножения"],
    ["Xonalarni tekislaymiz, o'ngdan boshlaymiz, hosil bo'lgan o'nlikni keyingi xonaga o'tkazamiz.", "Выравниваем разряды, начинаем справа и переносим получившийся десяток в следующий разряд."],
    'birlik → o‘nlik → yuzlik', ["Hisob qayerdan boshlanadi?", "С какого разряда начинают?"],
    [["Birlikdan", "С единиц"], ["Yuzlikdan", "С сотен"], ["Istalgan joydan", "С любого"]], 0,
    ["Eng o'ngdagi razryad birinchi.", "Первым идёт крайний правый разряд."]),
  S('test', ["O'tkazishsiz ko'paytirish", "Умножение без переноса"],
    ["21 × 3 da birliklar 3, o'nliklar 6 bo'ladi.", "В 21 × 3 получаем 3 единицы и 6 десятков."],
    ' 21 × 3', ["Natijani toping.", "Найди результат."], [['63'], ['33'], ['61']], 0,
    ["3 × 1 va 3 × 2 ni xonalar bo'yicha hisoblang.", "Вычисли 3 × 1 и 3 × 2 по разрядам."]),
  S('test', ["Bitta o'tkazish", "Один перенос"],
    ["27 × 4 da 4 × 7 = 28: 8 yoziladi, 2 o'tkaziladi.", "В 27 × 4: 4 × 7 = 28, пишем 8 и переносим 2."],
    ' 27 × 4', ["Natija qaysi?", "Каков результат?"], [['88'], ['108'], ['118']], 1,
    ["4 × 2 o'nlikka o'tgan 2 o'nlikni qo'shing.", "К 4 × 2 десяткам прибавь 2 перенесённых десятка."]),
  S('exploration', ["Yozma bo'lish", "Письменное деление"],
    ["96 : 4 da avval 9 o'nlik ichida nechta to'liq 4 borligini topamiz.", "В 96 : 4 сначала выясняем, сколько полных четвёрок в 9 десятках."],
    '96 : 4', ["9 ichida nechta to'liq 4 bor?", "Сколько полных четвёрок в 9?"],
    [['1'], ['2'], ['3']], 1, ["4 × 2 = 8, 4 × 3 esa 9 dan katta.", "4 × 2 = 8, а 4 × 3 больше 9."]),
  S('exploration', ["Qoldiqni birlikka aylantiramiz", "Переводим остаток в единицы"],
    ["9 o'nlikdan 8 o'nlik ajratildi, 1 o'nlik qoldi. Uni 6 birlik bilan 16 birlik qilamiz.", "Из 9 десятков убрали 8, остался 1 десяток. Вместе с 6 единицами получаем 16 единиц."],
    '1 o‘nlik + 6 birlik = 16 birlik', ["16 : 4 nechaga teng?", "Чему равно 16 : 4?"],
    [['2'], ['4'], ['6']], 1, ["4 × 4 = 16.", "4 × 4 = 16."]),
  S('rule', ["Yozma bo'lish qoidasi", "Правило письменного деления"],
    ["Chapdagi katta razryaddan boshlaymiz; bo'lamiz, ko'paytiramiz, ayiramiz va keyingi raqamni tushiramiz.", "Начинаем со старшего разряда: делим, умножаем, вычитаем и сносим следующую цифру."],
    'bo‘l → ko‘paytir → ayir → tushir', ["96 : 4 bo'linmasi?", "Частное 96 : 4?"],
    [['22'], ['24'], ['26']], 1, ["Birinchi raqam 2, ikkinchisi 4.", "Первая цифра 2, вторая 4."]),
  S('test', ["Bo'lishni mashq qilamiz", "Тренируем деление"],
    ["84 ni 4 ga yozma usulda bo'ling.", "Раздели 84 на 4 письменным способом."],
    '84 : 4', ["Natijani tanlang.", "Выбери результат."], [['20'], ['21'], ['24']], 1,
    ["8 o'nlik : 4 = 2 o'nlik; 4 birlik : 4 = 1.", "8 десятков : 4 = 2 десятка; 4 единицы : 4 = 1."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Anvar 36 × 4 da 4 × 6 = 24 dan hosil bo'lgan 2 o'nlikni unutdi va 124 yozdi.", "Анвар в 36 × 4 забыл перенести 2 десятка из 4 × 6 = 24 и записал 124."],
    '36 × 4 = 124 ✗', ["Xato qaysi qadamda?", "На каком шаге ошибка?"],
    [["O'tkazilgan 2 qo'shilmagan", "Не прибавили перенесённые 2"], ["6 noto'g'ri yozilgan", "Неверно записана 6"], ["Amal bo'lish bo'lishi kerak", "Нужно было делить"]], 0,
    ["4 × 3 ga o'tgan 2 ni qo'shish kerak.", "К 4 × 3 нужно прибавить перенесённые 2."]),
  S('case', ["Ustaxona masalasi", "Задача мастерской"],
    ["Har bir qurilmaga 24 tadan detal kerak. 4 ta qurilma uchun detallar sonini yozma usulda toping.", "На каждое устройство нужно 24 детали. Найди письменно число деталей для 4 устройств."],
    '24 × 4', ["Jami nechta detal?", "Сколько всего деталей?"], [['86'], ['96'], ['106']], 1,
    ["4 × 4 = 16; 4 × 2 + 1 = 9 o'nlik.", "4 × 4 = 16; 4 × 2 + 1 = 9 десятков."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["156 ta modul 3 ta rafga teng taqsimlanadi.", "156 модулей поровну распределяют на 3 полки."],
    '156 : 3', ["Har rafda nechta modul?", "Сколько модулей на каждой полке?"], [['42'], ['52'], ['62']], 1,
    ["15 o'nlik : 3 = 5 o'nlik, so'ng 6 : 3 = 2.", "15 десятков : 3 = 5 десятков, затем 6 : 3 = 2."]),
  S('summary', ["Ustun terminali ishga tushdi", "Терминал запущен"],
    ["Siz razryadlarni tekislab yozma ko'paytirish va bo'lishni bajardingiz, natijani teskari amal bilan tekshirdingiz.", "Ты выровнял разряды, выполнил письменное умножение и деление и проверил результат обратным действием."],
    '× ↔ :', ["Yozma usulning asosiy tayanchi nima?", "Главная опора письменного способа?"],
    [["Razryadlarni tekislash", "Выравнивание разрядов"], ["Raqamlarni bezash", "Украшение цифр"], ["Chapdan taxmin qilish", "Догадка слева"]], 0,
    ["Bir xil razryadlar bir ustunda turadi.", "Одинаковые разряды стоят в одном столбце."]),
];

export default function Dars21() {
  return <Grade3LessonShell screens={SCREENS} titleUz="21-dars. Yozma ko'paytirish va bo'lish" titleRu="Урок 21. Письменное умножение и деление" />;
}
