/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars21.jsx';

const T = (uz, ru) => ({ uz, ru });
const S = (type, title, text, visual, ask, options, correct, hint) => ({
  type,
  title: T(title[0], title[1]),
  text: T(text[0], text[1]),
  visual,
  ask: T(ask[0], ask[1]),
  options: options.map(([uz, ru = uz]) => T(uz, ru)),
  correct,
  hint: T(hint[0], hint[1]),
});

export const SCREENS = [
  S('hook', ["Katta modul uchun hisob", "Расчёт большого модуля"],
    ["Bit 13 ta qatordan iborat panel yasaydi. Har qatorda 24 tadan kristall bor. Bittalab sanash juda uzoq.", "Бит строит панель из 13 рядов. В каждом ряду по 24 кристалла. Считать по одному слишком долго."],
    '13 qator × 24 tadan', ["Jami miqdorni qaysi ifoda topadi?", "Какое выражение найдёт общее количество?"],
    [['24 × 13'], ['24 + 13'], ['24 : 13']], 0,
    ["Teng qatorlar soni har qatordagi miqdorga ko'paytiriladi.", "Число равных рядов умножают на количество в каждом ряду."]),
  S('exploration', ["13 ni qulay ajratamiz", "Удобно раскладываем 13"],
    ["13 qatorni 10 qator va 3 qatorga ajratamiz. Shunda tanish ko'paytmalar hosil bo'ladi.", "Разделим 13 рядов на 10 рядов и 3 ряда. Получатся знакомые произведения."],
    '24 × 13 = 24 × (10 + 3)', ["13 ning to'g'ri yoyilmasi qaysi?", "Какое разложение числа 13 верно?"],
    [['10 + 3'], ['10 × 3'], ['20 − 3']], 0,
    ["O'nlik va birlikni ajrating.", "Отдели десяток и единицы."]),
  S('exploration', ["O'n qatorni topamiz", "Находим десять рядов"],
    ["24 ta kristallni 10 marta olsak, razryadlar bir xona chapga siljiydi.", "Если взять 24 кристалла 10 раз, разряды сдвинутся на одну позицию влево."],
    '24 × 10 = 240', ["Birinchi qismning qiymati?", "Значение первой части?"],
    [['24'], ['240'], ['2400']], 1,
    ["10 ga ko'paytirishda 24 o'n marta kattalashadi.", "При умножении на 10 число 24 увеличивается в десять раз."]),
  S('exploration', ["Uch qatorni topamiz", "Находим три ряда"],
    ["Qolgan 3 qator uchun 24 × 3 ni hisoblaymiz: 20 × 3 + 4 × 3.", "Для оставшихся 3 рядов вычисляем 24 × 3: 20 × 3 + 4 × 3."],
    '24 × 3 = 60 + 12 = 72', ["Ikkinchi qismning qiymati?", "Значение второй части?"],
    [['62'], ['72'], ['82']], 1,
    ["60 va 12 ni qo'shing.", "Сложи 60 и 12."]),
  S('exploration', ["Qismlarni birlashtiramiz", "Объединяем части"],
    ["O'n qator va uch qator natijalarini qo'shamiz. Shu bilan barcha 13 qator hisoblandi.", "Складываем результаты для десяти и трёх рядов. Так учтены все 13 рядов."],
    '240 + 72 = 312', ["24 × 13 nechaga teng?", "Чему равно 24 × 13?"],
    [['292'], ['302'], ['312']], 2,
    ["Ikkala qismning natijasini qo'shing.", "Сложи результаты обеих частей."]),
  S('rule', ["Taqsimot qoidasi", "Распределительное правило"],
    ["Ikkinchi ko'paytuvchini o'nlik va birlikka ajratamiz, birinchi sonni har qismga ko'paytirib, natijalarni qo'shamiz.", "Раскладываем второй множитель на десятки и единицы, умножаем первый на каждую часть и складываем результаты."],
    'a × (b + c) = a × b + a × c', ["Har ikki qismga nima bo'ladi?", "Что происходит с каждой частью?"],
    [["Bir xil son ko'paytiriladi", "Умножается на одно и то же число"], ["Faqat biri ko'paytiriladi", "Умножается только одна"], ["Ikkalasi ayiriladi", "Обе вычитаются"]], 0,
    ["Qavs tashqarisidagi ko'paytuvchi har bir qo'shiluvchiga ta'sir qiladi.", "Множитель за скобками действует на каждое слагаемое."]),
  S('test', ["Birga hisoblaymiz", "Вычисляем вместе"],
    ["12 × 14 ni 12 × 10 + 12 × 4 ko'rinishida hisoblang.", "Вычисли 12 × 14 как 12 × 10 + 12 × 4."],
    '120 + 48 = ?', ["Natijani tanlang.", "Выбери результат."],
    [['158'], ['168'], ['178']], 1,
    ["120 ga 48 ni qo'shing.", "Прибавь 48 к 120."]),
  S('test', ["Boshqa ko'rinish", "Другая модель"],
    ["32 × 15 uchun 15 ni 10 + 5 ga ajratamiz.", "Для 32 × 15 раскладываем 15 как 10 + 5."],
    '32 × 10 + 32 × 5', ["Qaysi oraliq natijalar to'g'ri?", "Какие промежуточные результаты верны?"],
    [['320 va 160', '320 и 160'], ['32 va 160', '32 и 160'], ['320 va 150', '320 и 150']], 0,
    ["32 × 10 va 32 × 5 ni alohida hisoblang.", "Отдельно вычисли 32 × 10 и 32 × 5."]),
  S('exploration', ["Yozma usul", "Письменный способ"],
    ["Yozma usul ham ayni ikki qismni hisoblaydi: avval birliklar 3 ga, keyin o'nlik 10 ga ko'payadi.", "Письменный способ считает те же две части: сначала умножение на 3 единицы, затем на 10."],
    '  24\n× 13\n────\n  72\n 240\n────\n 312', ["Ikkinchi qator nega 240?", "Почему вторая строка равна 240?"],
    [["24 × 10 hisoblangan", "Вычислено 24 × 10"], ["24 × 1 hisoblangan", "Вычислено 24 × 1"], ["72 ga nol qo'shilgan", "К 72 приписан ноль"]], 0,
    ["13 dagi 1 raqami bir o'nlikni bildiradi.", "Цифра 1 в числе 13 означает один десяток."]),
  S('rule', ["Razryad siljishi", "Сдвиг разряда"],
    ["O'nlikka ko'paytirish qatori birliklar ustunidan bir xona chapdan boshlanadi. Chunki u birlik emas, o'nlik natijasidir.", "Строка умножения на десятки начинается на одну позицию левее, потому что это результат в десятках."],
    '72 birlik\n24 o‘nlik = 240', ["Ikkinchi qator qayerdan boshlanadi?", "Где начинается вторая строка?"],
    [["Bir xona chapdan", "На одну позицию левее"], ["Bir xona o'ngdan", "На одну позицию правее"], ["Aynan bir joydan", "На том же месте"]], 0,
    ["O'nlik natijasi o'nliklar ustunidan boshlanadi.", "Результат в десятках начинается со столбца десятков."]),
  S('test', ["Mustaqil hisob", "Самостоятельное вычисление"],
    ["21 × 16 ni 21 × 10 + 21 × 6 orqali hisoblang.", "Вычисли 21 × 16 как 21 × 10 + 21 × 6."],
    '210 + 126 = ?', ["Natija qaysi?", "Каков результат?"],
    [['326'], ['336'], ['346']], 1,
    ["210 va 126 ni razryadlar bo'yicha qo'shing.", "Сложи 210 и 126 по разрядам."]),
  S('test', ["Nol birlik holati", "Случай с нулём в единицах"],
    ["35 × 20 da ikkinchi ko'paytuvchi 2 o'nlik va 0 birlikdan iborat.", "В 35 × 20 второй множитель состоит из 2 десятков и 0 единиц."],
    '35 × 2 × 10', ["Natijani toping.", "Найди результат."],
    [['70'], ['700'], ['7000']], 1,
    ["35 × 2 = 70, so'ng 10 marta kattalashtiring.", "35 × 2 = 70, затем увеличь в 10 раз."]),
  S('test', ["Xatoni toping", "Найди ошибку"],
    ["Anvar 23 × 14 = 23 × 10 + 4 deb yozdi. U birliklar qismini to'liq ko'paytirmadi.", "Анвар записал 23 × 14 = 23 × 10 + 4. Он не умножил полностью часть с единицами."],
    '23 × 10 + 4 ✗', ["To'g'ri ikkinchi qism qaysi?", "Какая вторая часть верна?"],
    [['23 × 4'], ['14 × 4'], ['23 + 4']], 0,
    ["Qavs tashqarisidagi 23 ikkala qismga ko'payadi.", "Число 23 за скобками умножается на обе части."]),
  S('case', ["Qurilish masalasi", "Строительная задача"],
    ["12 ta modulning har biriga 26 tadan mahkamlovchi kerak. Ustaxona nechta mahkamlovchi tayyorlaydi?", "Для каждого из 12 модулей нужно по 26 креплений. Сколько креплений подготовит мастерская?"],
    '26 × 12 = 26 × 10 + 26 × 2', ["Jami miqdor?", "Общее количество?"],
    [['292'], ['302'], ['312']], 2,
    ["260 + 52 ni hisoblang.", "Вычисли 260 + 52."]),
  S('test', ["Yakuniy diagnostika", "Итоговая диагностика"],
    ["Yangi sonlar bilan usulni qo'llang: 34 × 21.", "Примени способ к новым числам: 34 × 21."],
    '34 × 20 + 34 × 1', ["Natijani tanlang.", "Выбери результат."],
    [['684'], ['714'], ['724']], 1,
    ["680 ga yana 34 ni qo'shing.", "К 680 прибавь ещё 34."]),
  S('summary', ["Katta modul yig'ildi", "Большой модуль собран"],
    ["Siz panjara modeli, taqsimot qoidasi va yozma usulning bir xil hisobni ifodalashini ko'rsatdingiz.", "Ты показал, что модель решётки, распределительное правило и письменный способ выражают одно вычисление."],
    '24 × 13 = 312', ["Usulning asosiy qadamlari qaysi?", "Каковы главные шаги способа?"],
    [["Ajratish, ko'paytirish, qo'shish", "Разложить, умножить, сложить"], ["Qo'shish, bo'lish, ayirish", "Сложить, разделить, вычесть"], ["Faqat nol qo'shish", "Только приписать ноль"]], 0,
    ["O'nlik va birlik qismlar alohida hisoblanib birlashtiriladi.", "Части десятков и единиц считают отдельно и объединяют."]),
];

export default function Dars24() {
  return (
    <Grade3LessonShell
      screens={SCREENS}
      titleUz="24-dars. Ikki xonali sonni ikki xonali songa ko'paytirish"
      titleRu="Урок 24. Умножение двузначного числа на двузначное"
    />
  );
}
