/* eslint-disable react-refresh/only-export-components */
import { Grade3LessonShell } from './Dars19.jsx';

const T = (uz, ru) => ({ uz, ru });
const O = (value) => Array.isArray(value) ? T(value[0], value[1]) : value;
const q = (visual, uz, ru, options, correct, hintUz, hintRu) => ({
  visual,
  ask: T(uz, ru),
  options: options.map(O),
  correct,
  hint: T(hintUz, hintRu),
});

const STAGES = [
  ['hook', 'Kirish diagnostikasi', 'Входная диагностика'],
  ['exploration', 'Tayanch bilim', 'Опорные знания'],
  ['case', 'Lumo markazidagi muammo', 'Задача в центре Лумо'],
  ['exploration', 'Konkret model', 'Предметная модель'],
  ['exploration', 'Ikkinchi model', 'Вторая модель'],
  ['exploration', 'Qonuniyatni kashf etamiz', 'Открываем закономерность'],
  ['rule', 'Yangi qoida', 'Новое правило'],
  ['test', 'Birga bajaramiz', 'Решаем вместе'],
  ['test', "Yo'naltirilgan mashq", 'Задание с подсказкой'],
  ['test', 'Mustaqil mashq', 'Самостоятельная работа'],
  ['test', 'Teskari topshiriq', 'Обратное задание'],
  ['test', 'Xatoni toping', 'Найди ошибку'],
  ['case', 'Hayotiy masala', 'Практическая задача'],
  ['test', 'Yakuniy diagnostika', 'Итоговая диагностика'],
  ['summary', 'Markaz vazifasi bajarildi', 'Задача центра выполнена'],
];

const GUIDANCE = [
  T("Avvalgi bilimingizni yangi qoidasiz tekshiring.", 'Проверь прежние знания без нового правила.'),
  T("Yangi mavzu tayangan bilimni eslang.", 'Вспомни знание, на котором строится новая тема.'),
  T("Bit va do'stlariga haqiqiy muammoni yechishda yordam bering.", 'Помоги Биту и друзьям решить настоящую задачу.'),
  T("Miqdorni ko'rinadigan modelda tekshiring.", 'Исследуй величину на наглядной модели.'),
  T("Xuddi shu fikrni boshqa ko'rinishda kuzating.", 'Рассмотри ту же идею в другой форме.'),
  T("Misollardan qonuniyatni o'zingiz toping.", 'Сам найди закономерность в примерах.'),
  T("Kashf qilgan bog'lanishni qoida bilan mustahkamlang.", 'Закрепи найденную связь правилом.'),
  T("Vizual tayanch bilan bir qadamni bajaring.", 'Выполни один шаг с визуальной опорой.'),
  T("Tayanchni kamaytirib, mos amalni tanlang.", 'С меньшей опорой выбери нужное действие.'),
  T("Yangi misolni mustaqil yeching.", 'Реши новый пример самостоятельно.'),
  T("Natijadan noma'lum miqdorni tiklang.", 'Восстанови неизвестную величину по результату.'),
  T("Noto'g'ri fikrni aniqlab tuzating.", 'Найди и исправь неверное рассуждение.'),
  T("Usulni hayotiy vaziyatda qo'llang.", 'Примени способ в жизненной ситуации.'),
  T("Usulni yangi vaziyatga ko'chiring.", 'Перенеси способ в новую ситуацию.'),
  T("Eng muhim xulosani belgilang.", 'Отметь самый важный вывод.'),
];

function buildScreens(config) {
  return STAGES.map(([type, uz, ru], index) => ({
    type,
    title: T(uz, ru),
    text: index === 2 ? config.story : index === 6 ? config.rule : index === 14 ? config.finish : GUIDANCE[index],
    ...config.checks[index],
  }));
}

export const FINAL_LESSONS = {
  42: {
    titleUz: '42-dars. Massa',
    titleRu: 'Урок 42. Масса',
    story: T("Lumo yuk markazida kristall qutilarni tarozida o'lchab, transportga xavfsiz taqsimlash kerak.", 'В грузовом центре Лумо нужно взвесить кристальные ящики и безопасно распределить их по транспорту.'),
    rule: T("Massa gramm, kilogramm va tonnada o'lchanadi. 1 kg = 1000 g, 1 t = 1000 kg. Birliklarni tenglashtirgandan keyin amal bajaring.", 'Массу измеряют в граммах, килограммах и тоннах. 1 кг = 1000 г, 1 т = 1000 кг. Перед вычислением приведи единицы к одинаковым.'),
    finish: T("Yuklar massasi aniqlandi. Keyingi darsda jo'nash vaqtini hisoblash kerak bo'ladi.", 'Масса грузов определена. На следующем уроке нужно будет рассчитать время отправления.'),
    checks: [
      q('1 kg va 1 g', "Qaysi massa katta?", 'Какая масса больше?', ['1 kg', '1 g', 'Teng'], 0, "Bir kilogrammda ming gramm bor.", 'В одном килограмме тысяча граммов.'),
      q('500 g + 500 g', "Jami necha gramm?", 'Сколько граммов всего?', ['100 g', '1000 g', '5000 g'], 1, "Ikki teng yarim kilogrammni qo'shing.", 'Сложи две половины килограмма.'),
      q('Quti: 3 kg; limit: 5 kg', "Quti limitdan oshadimi?", 'Превышает ли ящик предел?', [["Yo'q", "Нет"], ["Ha", "Да"], ["Aniqlab bo'lmaydi", "Нельзя определить"]], 0, "3 ni 5 bilan solishtiring.", 'Сравни 3 и 5.'),
      q('⚖ 1 kg = 1000 g', "2 kg necha gramm?", 'Сколько граммов в 2 кг?', ['200 g', '2000 g', '20 000 g'], 1, "Mingni ikki marta oling.", 'Возьми тысячу два раза.'),
      q('2500 g', "Bu necha kg va g?", 'Сколько это кг и г?', ['2 kg 500 g', '25 kg', '2 kg 50 g'], 0, "Ikki ming gramm — ikki kilogramm.", 'Две тысячи граммов — два килограмма.'),
      q('3 kg = 3000 g', "Qanday qonuniyat ishladi?", 'Какая закономерность использована?', [["kg dan g ga ×1000", "Из кг в г умножаем на 1000"], ["kg dan g ga :1000", "Из кг в г делим на 1000"], ["Birlik o'zgarmaydi", "Единица не меняется"]], 0, "Katta birlikdan kichikka o'tildi.", 'Переход от крупной единицы к мелкой.'),
      q('1 t = 1000 kg', "To'g'ri tenglikni tanlang.", 'Выбери верное равенство.', ['2 t = 200 kg', '2 t = 2000 kg', '2 t = 20 000 kg'], 1, "Har tonnada ming kilogramm.", 'В каждой тонне тысяча килограммов.'),
      q('4 kg + 600 g', "Grammda jami qancha?", 'Сколько всего в граммах?', ['1000 g', '4060 g', '4600 g'], 2, "4 kg ni 4000 g ga aylantiring.", 'Преобразуй 4 кг в 4000 г.'),
      q('7 kg − 2500 g', "Qancha massa qoldi?", 'Какая масса осталась?', ['4 kg 500 g', '5 kg 500 g', '4 kg 50 g'], 0, "7000 g dan 2500 g ni ayiring.", 'Вычти 2500 г из 7000 г.'),
      q('1 t 300 kg + 700 kg', "Jami massa qancha?", 'Какова общая масса?', ['1 t', '2 t', '2 t 700 kg'], 1, "300 kg va 700 kg yana bir tonna.", '300 кг и 700 кг дают ещё тонну.'),
      q('? + 750 g = 2 kg', "Noma'lum massani toping.", 'Найди неизвестную массу.', ['250 g', '1250 g', '1750 g'], 1, "2000 g dan 750 g ni ayiring.", 'Вычти 750 г из 2000 г.'),
      q('3 kg = 300 g', "Xatoni toping.", 'Найди ошибку.', [["3 kg = 3000 g", "3 кг = 3000 г"], ["3 kg = 30 g", "3 кг = 30 г"], ["Tenglik to'g'ri", "Равенство верно"]], 0, "Bir kilogrammda uchta emas, ming gramm.", 'В килограмме не сто, а тысяча граммов.'),
      q('6 quti × 4 kg', "Yukning jami massasi qancha?", 'Какова общая масса груза?', ['10 kg', '20 kg', '24 kg'], 2, "Oltita qutining har biri to'rt kilogramm.", 'Шесть ящиков по четыре килограмма.'),
      q('2 t − 650 kg', "Yangi vaziyatda qoldiqni toping.", 'Найди остаток в новой ситуации.', ['1 t 350 kg', '1 t 450 kg', '135 kg'], 0, "2000 kg dan 650 kg ni ayiring.", 'Вычти 650 кг из 2000 кг.'),
      q('kg ↔ g; t ↔ kg', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Amaldan oldin birliklarni tenglashtirish", "Перед действием привести единицы к одинаковым"], ["Har doim sonlarni qo'shish", "Всегда складывать числа"], ["Birlikni yozmaslik", "Не писать единицу"]], 0, "Turli birliklar bevosita qo'shilmaydi.", 'Разные единицы нельзя складывать напрямую.'),
    ],
  },
  43: {
    titleUz: '43-dars. Vaqt',
    titleRu: 'Урок 43. Время',
    story: T("Lumo transport markazida jo'nash, kelish va yo'lda bo'lish vaqtlarini aniq hisoblash kerak.", 'В транспортном центре Лумо нужно точно рассчитать время отправления, прибытия и продолжительность пути.'),
    rule: T("1 soat = 60 daqiqa, 1 daqiqa = 60 soniya, 1 sutka = 24 soat. Davomiylikni topishda vaqt chizig'idan foydalaning.", '1 час = 60 минут, 1 минута = 60 секунд, 1 сутки = 24 часа. Для длительности используй временную линию.'),
    finish: T("Transport jadvali tuzildi. Keyingi darsda masofa uchun uzunlik birliklarini moslashtirasiz.", 'Расписание транспорта составлено. На следующем уроке ты согласуешь единицы длины для расстояний.'),
    checks: [
      q('1 h va 30 min', "Qaysi vaqt uzoqroq?", 'Какое время дольше?', ['1 h', '30 min', 'Teng'], 0, "Bir soat oltmish daqiqa.", 'Один час — шестьдесят минут.'),
      q('20 min + 40 min', "Jami qancha?", 'Сколько всего?', ['60 min', '80 min', '1 h 20 min'], 0, "Yig'indi oltmish daqiqa.", 'Сумма равна шестидесяти минутам.'),
      q('Jo‘nash 09:00; yo‘l 2 h', "Kelish vaqti qaysi?", 'Когда прибытие?', ['10:00', '11:00', '12:00'], 1, "Soatga ikki qo'shing.", 'Прибавь два часа.'),
      q('1 h = 60 min', "3 h necha daqiqa?", 'Сколько минут в 3 часах?', ['180 min', '120 min', '360 min'], 0, "60 ni 3 ga ko'paytiring.", 'Умножь 60 на 3.'),
      q('90 min', "Bu necha soat va daqiqa?", 'Сколько это часов и минут?', ['1 h 30 min', '9 h', '1 h 90 min'], 0, "60 daqiqa bir soat bo'ladi.", '60 минут образуют один час.'),
      q('14:20 → 15:05', "Qancha vaqt o'tdi?", 'Сколько времени прошло?', ['35 min', '45 min', '55 min'], 1, "14:20 dan 15:00 gacha 40, yana 5.", 'До 15:00 — 40 минут, затем ещё 5.'),
      q('1 sutka = 24 h', "2 sutka necha soat?", 'Сколько часов в 2 сутках?', ['24 h', '36 h', '48 h'], 2, "24 ni ikki marta oling.", 'Возьми 24 два раза.'),
      q('08:45 + 30 min', "Natijani toping.", 'Найди результат.', ['09:05', '09:15', '09:30'], 1, "15 daqiqada 09:00, yana 15.", 'Через 15 минут 09:00, затем ещё 15.'),
      q('17:10 − 50 min', "Boshlanish vaqti qaysi?", 'Когда было начало?', ['16:20', '16:40', '17:40'], 0, "17:10 dan 10 daqiqa va yana 40 ayiring.", 'Вычти 10 минут, затем ещё 40.'),
      q('2 h 25 min + 45 min', "Jami davomiylik qancha?", 'Какова общая длительность?', ['2 h 70 min', '3 h 10 min', '3 h 25 min'], 1, "25+45=70 min = 1 h 10 min.", '25+45=70 мин = 1 ч 10 мин.'),
      q('? + 35 min = 1 h 20 min', "Noma'lum vaqtni toping.", 'Найди неизвестное время.', ['35 min', '45 min', '55 min'], 1, "80 min dan 35 min ni ayiring.", 'Вычти 35 минут из 80.'),
      q('1 h 30 min = 130 min', "Xatoni toping.", 'Найди ошибку.', [["1 h 30 min = 90 min", "1 ч 30 мин = 90 мин"], ["1 h 30 min = 60 min", "1 ч 30 мин = 60 мин"], ["Tenglik to'g'ri", "Равенство верно"]], 0, "Soat yuz emas, oltmish daqiqa.", 'В часе не сто, а шестьдесят минут.'),
      q('Mashg‘ulot 13:25–15:00', "Mashg'ulot qancha davom etdi?", 'Сколько длилось занятие?', ['1 h 25 min', '1 h 35 min', '2 h 35 min'], 1, "13:25 dan 14:25 gacha bir soat, keyin 35 min.", 'До 14:25 один час, затем 35 минут.'),
      q('23:30 + 2 h', "Yangi sutkadagi vaqt qaysi?", 'Какое время будет в новых сутках?', ['00:30', '01:30', '25:30'], 1, "Yarim soatda yarim tun, yana bir yarim soat.", 'Через полчаса полночь, затем ещё полтора часа.'),
      q('h ↔ min ↔ s', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Vaqtda 60 lik bog'lanishni hisobga olish", "Учитывать шестидесятеричную связь времени"], ["Har soatda 100 daqiqa", "В каждом часе 100 минут"], ["Vaqt birliksiz yoziladi", "Время пишут без единицы"]], 0, "Soat va daqiqa o'nlik tizim emas.", 'Часы и минуты не образуют десятичную систему.'),
    ],
  },
  44: {
    titleUz: '44-dars. Uzunlik birliklari va nisbatlari',
    titleRu: 'Урок 44. Единицы длины и их соотношения',
    story: T("Lumo yo'l xaritasidagi kesmalar turli birliklarda berilgan; ularni bitta o'lchovga keltirish kerak.", 'Отрезки на карте дорог Лумо даны в разных единицах; их нужно привести к одной мере.'),
    rule: T("1 m = 10 dm = 100 cm, 1 dm = 10 cm, 1 km = 1000 m. Taqqoslash va amal oldidan birliklarni tenglashtiring.", '1 м = 10 дм = 100 см, 1 дм = 10 см, 1 км = 1000 м. Перед сравнением и вычислением приведи единицы к одинаковым.'),
    finish: T("Yo'l xaritasi bitta o'lchovda qayta yozildi. Keyingi darsda sanalarni kalendar bo'yicha rejalashtirasiz.", 'Карта дорог переписана в единой мере. На следующем уроке ты будешь планировать даты по календарю.'),
    checks: [
      q('1 m va 90 cm', "Qaysi uzunlik katta?", 'Какая длина больше?', ['1 m', '90 cm', 'Teng'], 0, "1 m = 100 cm.", '1 м = 100 см.'),
      q('4 dm + 6 dm', "Jami necha metr?", 'Сколько метров всего?', ['1 m', '10 m', '100 m'], 0, "10 dm bir metr.", '10 дм — один метр.'),
      q('Yo‘l: 2 km; belgi: 500 m', "Belgi yo'lning yarmidami?", 'Знак находится на половине пути?', [["Yo'q", "Нет"], ["Ha", "Да"], ["Teng birlik yo'q", "Нет одинаковых единиц"]], 0, "2 km ning yarmi 1 km.", 'Половина 2 км — 1 км.'),
      q('1 m = 100 cm', "7 m necha santimetr?", 'Сколько сантиметров в 7 м?', ['70 cm', '700 cm', '7000 cm'], 1, "100 ni 7 ga ko'paytiring.", 'Умножь 100 на 7.'),
      q('345 cm', "Bu necha m va cm?", 'Сколько это м и см?', ['3 m 45 cm', '34 m 5 cm', '3 m 450 cm'], 0, "Uch yuz santimetr uch metr.", 'Триста сантиметров — три метра.'),
      q('5 dm = 50 cm', "Qanday amal bajarildi?", 'Какое действие выполнено?', [["×10", "×10"], [":10", ":10"], ["×100", "×100"]], 0, "Detsimetrdan santimetrga kichraydi birlik.", 'При переходе от дм к см единица мельче.'),
      q('1 km = 1000 m', "3 km 200 m necha metr?", 'Сколько метров в 3 км 200 м?', ['320 m', '3020 m', '3200 m'], 2, "3000 m ga 200 m qo'shing.", 'Сложи 3000 м и 200 м.'),
      q('2 m 40 cm + 80 cm', "Jami qancha?", 'Сколько всего?', ['2 m 120 cm', '3 m 20 cm', '3 m 40 cm'], 1, "40+80=120 cm = 1 m 20 cm.", '40+80=120 см = 1 м 20 см.'),
      q('5 km − 1750 m', "Qancha qoldi?", 'Сколько осталось?', ['3 km 250 m', '4 km 750 m', '325 m'], 0, "5000 m dan 1750 m ni ayiring.", 'Вычти 1750 м из 5000 м.'),
      q('8 dm 5 cm', "Santimetrda yozing.", 'Запиши в сантиметрах.', ['13 cm', '85 cm', '805 cm'], 1, "8 dm = 80 cm.", '8 дм = 80 см.'),
      q('? cm = 4 m 30 cm', "Noma'lum sonni toping.", 'Найди неизвестное число.', ['430', '4030', '43'], 0, "4 m = 400 cm.", '4 м = 400 см.'),
      q('6 dm = 600 cm', "Xatoni toping.", 'Найди ошибку.', [["6 dm = 60 cm", "6 дм = 60 см"], ["6 dm = 6 cm", "6 дм = 6 см"], ["Tenglik to'g'ri", "Равенство верно"]], 0, "Bir dm da o'n cm.", 'В одном дм десять см.'),
      q('Lenta: 3 m; kesildi 75 cm', "Qancha lenta qoldi?", 'Сколько ленты осталось?', ['2 m 25 cm', '2 m 75 cm', '225 m'], 0, "300 cm dan 75 cm ni ayiring.", 'Вычти 75 см из 300 см.'),
      q('1 km 80 m + 950 m', "Yangi masofani toping.", 'Найди новое расстояние.', ['1 km 30 m', '2 km 30 m', '2 km 130 m'], 1, "1080 m + 950 m = 2030 m.", '1080 м + 950 м = 2030 м.'),
      q('km ↔ m ↔ dm ↔ cm', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Amaldan oldin birliklarni bir xil qilish", "Перед действием сделать единицы одинаковыми"], ["Faqat sonlarni solishtirish", "Сравнивать только числа"], ["Katta birlik doim kichik son", "Крупная единица всегда меньшее число"]], 0, "Son bilan birga birlikni ham ko'ring.", 'Смотри не только на число, но и на единицу.'),
    ],
  },
  45: {
    titleUz: '45-dars. Kalendar',
    titleRu: 'Урок 45. Календарь',
    story: T("Lumo tadqiqot markazi safar, kuzatuv va dam olish kunlarini kalendarda aniq rejalashtirishi kerak.", 'Исследовательскому центру Лумо нужно точно запланировать дни поездок, наблюдений и отдыха по календарю.'),
    rule: T("Yil 12 oydan, hafta 7 kundan iborat. Oylar 28, 29, 30 yoki 31 kun bo'ladi. Sana oralig'ini sanashda boshlanish va tugash shartini aniqlang.", 'В году 12 месяцев, в неделе 7 дней. В месяце бывает 28, 29, 30 или 31 день. При подсчёте промежутка уточни, включаются ли начальная и конечная даты.'),
    finish: T("Markaz kalendari tuzildi. Keyingi darsda noma'lum sonlarni tenglama yordamida topasiz.", 'Календарь центра составлен. На следующем уроке ты будешь находить неизвестные числа с помощью уравнений.'),
    checks: [
      q('D S Ch P J Sh Y', "Haftada nechta kun bor?", 'Сколько дней в неделе?', ['5', '7', '10'], 1, "Hafta kunlarini sanang.", 'Посчитай дни недели.'),
      q('Yanvar → Fevral', "Yanvardan keyin qaysi oy?", 'Какой месяц после января?', [["Fevral", "Февраль"], ["Mart", "Март"], ["Dekabr", "Декабрь"]], 0, "Yil boshidagi oylar tartibini eslang.", 'Вспомни порядок месяцев в начале года.'),
      q('Safar: 12–15-may', "Safar qaysi oyda?", 'В каком месяце поездка?', [["May", "Май"], ["Mart", "Март"], ["Iyun", "Июнь"]], 0, "Sana nomidagi oyga qarang.", 'Смотри на название месяца.'),
      q('1 hafta = 7 kun', "3 hafta necha kun?", 'Сколько дней в 3 неделях?', ['10', '21', '30'], 1, "7 ni 3 ga ko'paytiring.", 'Умножь 7 на 3.'),
      q('Aprel: 30 kun', "Aprelning oxirgi sanasi qaysi?", 'Какая последняя дата апреля?', ['29', '30', '31'], 1, "Aprelda o'ttiz kun.", 'В апреле тридцать дней.'),
      q('Dushanba + 7 kun', "Qaysi hafta kuni bo'ladi?", 'Какой будет день недели?', [["Dushanba", "Понедельник"], ["Seshanba", "Вторник"], ["Yakshanba", "Воскресенье"]], 0, "Yetti kundan keyin hafta takrorlanadi.", 'Через семь дней неделя повторяется.'),
      q('12 oy = 1 yil', "2 yil necha oy?", 'Сколько месяцев в 2 годах?', ['12', '18', '24'], 2, "12 ni ikki marta oling.", 'Возьми 12 два раза.'),
      q('Bugun 18-iyun; 5 kundan keyin', "Sana qaysi?", 'Какая будет дата?', ['22-iyun', '23-iyun', '24-iyun'], 1, "19 — birinchi keyingi kun.", '19-е — первый следующий день.'),
      q('28-fevral + 1 kun', "Oddiy yilda keyingi sana qaysi?", 'Какая следующая дата в обычном году?', ['29-fevral', '1-mart', '2-mart'], 1, "Oddiy yilda fevral 28 kun.", 'В обычном году в феврале 28 дней.'),
      q('31-dekabr + 1 kun', "Keyingi sana qaysi?", 'Какая следующая дата?', ['32-dekabr', '1-yanvar', '2-yanvar'], 1, "Yangi yil boshlanadi.", 'Начинается новый год.'),
      q('? kun = 4 hafta', "Noma'lum sonni toping.", 'Найди неизвестное число.', ['11', '28', '40'], 1, "4 × 7.", 'Вычисли 4 × 7.'),
      q('Sentabrda 31 kun', "Xatoni toping.", 'Найди ошибку.', [["Sentabrda 30 kun", "В сентябре 30 дней"], ["Sentabrda 28 kun", "В сентябре 28 дней"], ["Fikr to'g'ri", "Утверждение верно"]], 0, "Aprel, iyun, sentabr, noyabr — o'ttiz.", 'Апрель, июнь, сентябрь, ноябрь — по тридцать.'),
      q('Kurs: 3–17-oktabr', "Boshlanishdan tugashgacha necha kun o'tadi?", 'Сколько дней проходит от начала до конца?', ['13', '14', '15'], 1, "17 dan 3 ni ayiring.", 'Вычти 3 из 17.'),
      q('Juma + 10 kun', "Qaysi hafta kuni?", 'Какой будет день недели?', [["Dushanba", "Понедельник"], ["Seshanba", "Вторник"], ["Yakshanba", "Воскресенье"]], 0, "7 kun yana juma, yana 3 kun dushanba.", 'Через 7 дней снова пятница, ещё через 3 — понедельник.'),
      q('yil → oy → hafta → kun', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Kalendar davriy tartibga ega", "Календарь имеет циклический порядок"], ["Har oy 30 kun", "В каждом месяце 30 дней"], ["Hafta 10 kun", "В неделе 10 дней"]], 0, "Oy va hafta tartibi qayta takrorlanadi.", 'Порядок месяцев и недель повторяется.'),
    ],
  },
  46: {
    titleUz: '46-dars. Tenglamalar',
    titleRu: 'Урок 46. Уравнения',
    story: T("Lumo boshqaruv panelidagi noma'lum kodni tenglikni saqlagan holda topish kerak.", 'На панели управления Лумо нужно найти неизвестный код, сохраняя равенство.'),
    rule: T("Tenglama — noma'lum son qatnashgan tenglik. Noma'lum qo'shiluvchi ayirish, kamayuvchi qo'shish, ayiriluvchi ayirish bilan topiladi.", 'Уравнение — равенство с неизвестным. Неизвестное слагаемое находят вычитанием, уменьшаемое — сложением, вычитаемое — вычитанием.'),
    finish: T("Noma'lum kod topildi. Keyingi darsda tenglama yechimini teskari amal bilan tekshirasiz.", 'Неизвестный код найден. На следующем уроке ты проверишь решение уравнения обратным действием.'),
    checks: [
      q('7 + ? = 12', "Noma'lum son qaysi?", 'Какое число неизвестно?', ['3', '5', '19'], 1, "12 dan 7 ni ayiring.", 'Вычти 7 из 12.'),
      q('x + 4 = 9', "x o'rniga qaysi son tenglikni rost qiladi?", 'Какое число вместо x делает равенство верным?', ['5', '9', '13'], 0, "5+4 ni tekshiring.", 'Проверь 5+4.'),
      q('x + 18 = 45', "Panel kodi x ni toping.", 'Найди код x.', ['27', '37', '63'], 0, "Noma'lum qo'shiluvchi yig'indidan ma'lum qo'shiluvchini ayirish bilan topiladi.", 'Из суммы вычти известное слагаемое.'),
      q('□ + 6 = 14', "Modeldagi bo'sh katak qancha?", 'Чему равна пустая клетка?', ['8', '20', '6'], 0, "14−6.", 'Вычисли 14−6.'),
      q('17 − x = 9', "Qaysi son olib tashlangan?", 'Какое число вычли?', ['8', '9', '26'], 0, "17 dan 9 qolishi uchun 8 ayiriladi.", 'Чтобы из 17 получить 9, вычитают 8.'),
      q('x − 11 = 20', "Qanday amal x ni topadi?", 'Какое действие находит x?', ['20−11', '20+11', '11−20'], 1, "Kamayuvchi ayirma va ayiriluvchi yig'indisi.", 'Уменьшаемое равно сумме разности и вычитаемого.'),
      q('x + a = b → x = b − a', "Qoida qaysi?", 'Какое правило верно?', [["Yig'indidan ma'lum qo'shiluvchini ayirish", "Из суммы вычесть известное слагаемое"], ["Sonlarni almashtirmaslik", "Не менять числа"], ["Har doim qo'shish", "Всегда складывать"]], 0, "Teskari amalni tanlang.", 'Выбери обратное действие.'),
      q('x + 26 = 70', "x ni toping.", 'Найди x.', ['44', '54', '96'], 0, "70−26.", 'Вычисли 70−26.'),
      q('x − 35 = 48', "x ni toping.", 'Найди x.', ['13', '73', '83'], 2, "48+35.", 'Вычисли 48+35.'),
      q('92 − x = 37', "Mustaqil yeching.", 'Реши самостоятельно.', ['55', '65', '129'], 0, "Ayiriluvchi = kamayuvchi − ayirma.", 'Вычитаемое = уменьшаемое − разность.'),
      q('x + 19 = 50', "Yechimdan x ni tiklang.", 'Восстанови x.', ['29', '31', '69'], 1, "50−19.", 'Вычисли 50−19.'),
      q('x−8=15 → x=7', "Xatoni toping.", 'Найди ошибку.', [["x=23", "x=23"], ["x=7 to'g'ri", "x=7 верно"], ["x=120", "x=120"]], 0, "Kamayuvchini topishda qo'shing.", 'Для нахождения уменьшаемого сложи.'),
      q('Ombor: x−24=36', "Avval nechta quti bo'lgan?", 'Сколько ящиков было сначала?', ['12', '60', '864'], 1, "Qolgan va chiqarilgan qutilarni qo'shing.", 'Сложи оставшиеся и вывезенные ящики.'),
      q('150−x=85', "Yangi tenglamani yeching.", 'Реши новое уравнение.', ['65', '75', '235'], 0, "150−85.", 'Вычисли 150−85.'),
      q('tenglik + noma’lum', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Tenglama teskari amal bilan yechiladi", "Уравнение решают обратным действием"], ["x doim nol", "x всегда ноль"], ["Tenglik tekshirilmaydi", "Равенство не проверяют"]], 0, "Amal komponentlari bog'lanishini eslang.", 'Вспомни связь компонентов действий.'),
    ],
  },
  47: {
    titleUz: '47-dars. Tenglamalarni yechish va tekshirish',
    titleRu: 'Урок 47. Решение и проверка уравнений',
    story: T("Boshqaruv tizimi faqat topilgan qiymat dastlabki tenglikka qo'yib tekshirilganda ochiladi.", 'Система управления откроется, только если найденное значение подставить и проверить в исходном равенстве.'),
    rule: T("Tenglamani yeching, topilgan qiymatni noma'lum o'rniga qo'ying va ikki tomon tengligini tekshiring. Ko'paytirish va bo'lish o'zaro teskari amallardir.", 'Реши уравнение, подставь значение вместо неизвестного и проверь равенство сторон. Умножение и деление — взаимно обратные действия.'),
    finish: T("Kod yechildi va tekshirildi. Keyingi darsda bir necha bog'langan amalli masalalarni rejalashtirasiz.", 'Код решён и проверен. На следующем уроке ты спланируешь задачи с несколькими связанными действиями.'),
    checks: [
      q('6 × ? = 24', "Noma'lum ko'paytuvchi qaysi?", 'Какой неизвестный множитель?', ['4', '18', '30'], 0, "24 ni 6 ga bo'ling.", 'Раздели 24 на 6.'),
      q('x : 5 = 7', "x ni toping.", 'Найди x.', ['12', '35', '2'], 1, "Bo'linuvchi bo'luvchi va bo'linma ko'paytmasi.", 'Делимое равно произведению делителя и частного.'),
      q('8 × x = 56', "Kod qiymati qaysi?", 'Каково значение кода?', ['6', '7', '8'], 1, "56:8.", 'Вычисли 56:8.'),
      q('x × 3 = 27', "Modeldagi teng guruh soni qaysi?", 'Сколько равных групп?', ['9', '24', '30'], 0, "27 ni 3 ga bo'ling.", 'Раздели 27 на 3.'),
      q('42 : x = 6', "Bo'luvchini toping.", 'Найди делитель.', ['6', '7', '36'], 1, "42:6.", 'Вычисли 42:6.'),
      q('x : 4 = 9 → x=36', "Tekshiruv qaysi?", 'Какая проверка верна?', ['36:4=9', '36−4=32', '9:4=36'], 0, "Topilgan x ni tenglamaga qo'ying.", 'Подставь найденный x.'),
      q('a×x=b → x=b:a', "Qoidani tanlang.", 'Выбери правило.', [["Noma'lum ko'paytuvchi bo'lish bilan topiladi", "Неизвестный множитель находят делением"], ["Har doim ayirish kerak", "Всегда нужно вычитать"], ["x=b×a", "x=b×a"]], 0, "Ko'paytirishga teskari amal bo'lish.", 'Обратное умножению действие — деление.'),
      q('9x=72', "x ni toping.", 'Найди x.', ['8', '9', '63'], 0, "72:9.", 'Вычисли 72:9.'),
      q('x:8=12', "x ni toping.", 'Найди x.', ['4', '20', '96'], 2, "12×8.", 'Вычисли 12×8.'),
      q('81:x=9', "Mustaqil yeching.", 'Реши самостоятельно.', ['8', '9', '72'], 1, "81:9.", 'Вычисли 81:9.'),
      q('x×7=63', "Yechim va tekshiruv juftligini toping.", 'Найди решение и проверку.', ['x=9; 9×7=63', 'x=8; 8×7=63', 'x=56; 56:7=63'], 0, "Avval 63:7.", 'Сначала 63:7.'),
      q('x:6=8 → x=2', "Xatoni toping.", 'Найди ошибку.', [["x=48", "x=48"], ["x=2 to'g'ri", "x=2 верно"], ["x=14", "x=14"]], 0, "Bo'linuvchini topishda ko'paytiring.", 'Чтобы найти делимое, умножь.'),
      q('Har qutida 5; x:5=14', "Jami detal qancha?", 'Сколько деталей всего?', ['9', '19', '70'], 2, "14 guruhning har birida 5 tadan.", 'В 14 группах по 5.'),
      q('144:x=12', "Yangi tenglamani yeching.", 'Реши новое уравнение.', ['12', '132', '1728'], 0, "144:12.", 'Вычисли 144:12.'),
      q('yechim → qo‘yish → tekshirish', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Har yechim dastlabki tenglikda tekshiriladi", "Каждое решение проверяют в исходном равенстве"], ["Tekshiruv shart emas", "Проверка не нужна"], ["x doim bir", "x всегда равен одному"]], 0, "Ikki tomon bir xil chiqishi kerak.", 'Обе стороны должны совпасть.'),
    ],
  },
  48: {
    titleUz: '48-dars. Murakkab masalalar',
    titleRu: 'Урок 48. Составные задачи',
    story: T("Lumo ekspeditsiyasi yuk, masofa va vaqt haqidagi bir necha bog'langan savolni ketma-ket yechishi kerak.", 'Экспедиции Лумо нужно последовательно решить несколько связанных вопросов о грузе, расстоянии и времени.'),
    rule: T("Murakkab masalada oxirgi savoldan orqaga qarab oraliq noma'lumni aniqlang. Reja tuzing, amallarni tartib bilan bajaring va birlikli javob yozing.", 'В составной задаче от последнего вопроса найди промежуточное неизвестное. Составь план, выполни действия по порядку и запиши ответ с единицей.'),
    finish: T("Ekspeditsiya rejasi hisoblandi. Keyingi darsda tengsizlik va rost-yolg'on fikrlarni tekshirasiz.", 'План экспедиции рассчитан. На следующем уроке ты проверишь неравенства и истинность высказываний.'),
    checks: [
      q('12 + 8 → ? × 3', "Avval qaysi amal bajariladi?", 'Какое действие выполняют первым?', ['12+8', '8×3', '12×3'], 0, "Ikkinchi qadam jami songa bog'liq.", 'Второй шаг зависит от общей суммы.'),
      q('ma’lum → oraliq → javob', "Oraliq natija nima uchun kerak?", 'Зачем нужен промежуточный результат?', [["Keyingi amal uchun", "Для следующего действия"], ["Faqat yozuv uchun", "Только для записи"], ["Kerak emas", "Не нужен"]], 0, "Savollar bir-biriga bog'langan.", 'Вопросы связаны друг с другом.'),
      q('4 quti × 6 kg; yana 8 kg', "Jami massa uchun reja qaysi?", 'Каков план нахождения общей массы?', ['4×6, so‘ng +8', '6+8, so‘ng ×4', '4+6+8'], 0, "Avval qutilar massasini toping.", 'Сначала найди массу ящиков.'),
      q('4×6=24; 24+8=?', "Jami massa qancha?", 'Какова общая масса?', ['32 kg', '38 kg', '96 kg'], 0, "24+8.", 'Вычисли 24+8.'),
      q('60 km − 15 km; qolgani 3 kunda', "Bir kunda qolganning qancha qismi?", 'Сколько оставшегося пути в день?', ['(60−15):3', '60−15:3', '60:3−15'], 0, "Avval qolgan masofani toping.", 'Сначала найди оставшееся расстояние.'),
      q('(60−15):3=15', "Qonuniyat qaysi?", 'Какая идея использована?', [["Bog'langan amallar tartibi", "Порядок связанных действий"], ["Faqat qo'shish", "Только сложение"], ["Birlikni almashtirish", "Замена единицы"]], 0, "Ikkinchi amal birinchi natijadan foydalanadi.", 'Второе действие использует первый результат.'),
      q('savol → reja → yechim → javob', "To'g'ri tartibni tanlang.", 'Выбери верный порядок.', ['savol–reja–yechim–javob', 'javob–savol–reja', 'yechim–javob–savol'], 0, "Masala savolini avval tushuning.", 'Сначала пойми вопрос задачи.'),
      q('5×7 + 13', "Natijani toping.", 'Найди результат.', ['48', '100', '25'], 0, "Avval 5×7.", 'Сначала 5×7.'),
      q('90−(6×8)', "Natijani toping.", 'Найди результат.', ['42', '672', '84'], 0, "Qavs ichini avval hisoblang.", 'Сначала вычисли в скобках.'),
      q('(72:8)×5', "Mustaqil hisoblang.", 'Вычисли самостоятельно.', ['45', '13', '360'], 0, "72:8=9.", '72:8=9.'),
      q('? + 18 = 6×7', "Noma'lumni toping.", 'Найди неизвестное.', ['24', '36', '60'], 0, "42−18.", 'Вычисли 42−18.'),
      q('3×9+5=42', "Xatoni toping.", 'Найди ошибку.', [["Natija 32", "Результат 32"], ["Natija 42", "Результат 42"], ["Avval 9+5", "Сначала 9+5"]], 0, "27+5 ni tekshiring.", 'Проверь 27+5.'),
      q('8 paket×4 detal; 7 tasi ishlatildi', "Nechta detal qoldi?", 'Сколько деталей осталось?', ['25', '32', '39'], 0, "8×4−7.", 'Вычисли 8×4−7.'),
      q('120 km; 2 h da 35 km dan', "Qancha masofa qoldi?", 'Сколько пути осталось?', ['50 km', '70 km', '85 km'], 0, "120−2×35.", 'Вычисли 120−2×35.'),
      q('ikki yoki ko‘p bog‘langan qadam', "Asosiy strategiya qaysi?", 'Какова главная стратегия?', [["Oraliq savollar bilan reja tuzish", "Составить план с промежуточными вопросами"], ["Barcha sonlarni qo'shish", "Сложить все числа"], ["Javobni taxmin qilish", "Угадать ответ"]], 0, "Har qadam keyingisiga xizmat qiladi.", 'Каждый шаг нужен следующему.'),
    ],
  },
  49: {
    titleUz: "49-dars. Tengsizliklar, rost va yolg'on fikrlar",
    titleRu: 'Урок 49. Неравенства, истинные и ложные высказывания',
    story: T("Lumo mantiq terminali sonli taqqoslashlar va fikrlarning rostligini tekshirishni talab qiladi.", 'Логический терминал Лумо требует проверить числовые сравнения и истинность высказываний.'),
    rule: T("Tengsizlikda <, >, ≤, ≥ belgilar ishlatiladi. Fikr misol yoki qarshi misol bilan tekshiriladi; rost fikr har berilgan shartga mos keladi.", 'В неравенствах используют <, >, ≤, ≥. Высказывание проверяют примером или контрпримером; истинное соответствует всем данным условиям.'),
    finish: T("Mantiq terminali ochildi. Keyingi darsda ma'lumotlarni doiraviy diagrammada o'qiysiz.", 'Логический терминал открыт. На следующем уроке ты прочитаешь данные на круговой диаграмме.'),
    checks: [
      q('8 ? 5', "Mos belgini tanlang.", 'Выбери знак.', ['>', '<', '='], 0, "8 soni 5 dan katta.", '8 больше 5.'),
      q('12 = 12', "Bu fikr rostmi?", 'Верно ли высказывание?', [["Rost", "Истина"], ["Yolg'on", "Ложь"], ["Aniq emas", "Неизвестно"]], 0, "Ikki tomon teng.", 'Обе стороны равны.'),
      q('Yuk ≤ 20 kg; yuk 18 kg', "Shart bajarildimi?", 'Выполнено ли условие?', [["Ha", "Да"], ["Yo'q", "Нет"], ["Faqat 20 da", "Только при 20"]], 0, "≤ kichik yoki teng degani.", '≤ означает меньше или равно.'),
      q('x > 4', "Qaysi son mos?", 'Какое число подходит?', ['3', '4', '5'], 2, "Son 4 dan qat'iy katta.", 'Число строго больше 4.'),
      q('x ≤ 7', "Qaysi son mos kelmaydi?", 'Какое число не подходит?', ['6', '7', '8'], 2, "8 yettidan katta.", '8 больше семи.'),
      q('5<9 va 9<12', "Qanday xulosa chiqadi?", 'Какой вывод следует?', ['5<12', '12<5', '5=12'], 0, "Sonlar o'sish tartibida.", 'Числа расположены по возрастанию.'),
      q('≤ — kichik yoki teng', "7 ≤ 7 rostmi?", 'Верно ли 7 ≤ 7?', [["Rost", "Истина"], ["Yolg'on", "Ложь"], ["Faqat 7<7", "Только 7<7"]], 0, "Belgi tenglikka ham ruxsat beradi.", 'Знак допускает равенство.'),
      q('36:6 ? 2×3', "Mos belgini toping.", 'Найди знак.', ['=', '>', '<'], 0, "Ikkala tomon ham 6.", 'Обе стороны равны 6.'),
      q('4×8 > 30', "Fikrni tekshiring.", 'Проверь высказывание.', [["Rost", "Истина"], ["Yolg'on", "Ложь"], ["Hisoblab bo'lmaydi", "Нельзя вычислить"]], 0, "4×8=32.", '4×8=32.'),
      q('100−45 < 50', "Mustaqil tekshiring.", 'Проверь самостоятельно.', [["Yolg'on", "Ложь"], ["Rost", "Истина"], ["Teng", "Равны"]], 0, "100−45=55.", '100−45=55.'),
      q('x+3=10', "Yechim qaysi tengsizlikka ham mos?", 'Какому неравенству подходит решение?', ['x>8', 'x≤7', 'x<5'], 1, "x=7.", 'x=7.'),
      q('6 ≥ 9', "Xatoni tuzating.", 'Исправь ошибку.', ['6<9', '6=9', '6>9'], 0, "Son o'qida 6 chapda.", 'На числовой прямой 6 левее.'),
      q('Lift limiti ≤500 kg; yuk 480 kg', "Lift ishlashi mumkinmi?", 'Можно ли использовать лифт?', [["Ha", "Да"], ["Yo'q", "Нет"], ["Faqat 500 kg da", "Только при 500 кг"]], 0, "480≤500.", '480≤500.'),
      q("Har bir juft son 2 ga bo'linadi", "Fikr qanday?", 'Каково высказывание?', [["Rost", "Истина"], ["Yolg'on", "Ложь"], ["Faqat 2 uchun", "Только для 2"]], 0, "Juft sonning ta'rifini eslang.", 'Вспомни определение чётного числа.'),
      q('belgi + tekshiruv + xulosa', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Fikr hisob yoki qarshi misol bilan tekshiriladi", "Высказывание проверяют вычислением или контрпримером"], ["Har fikr rost", "Каждое высказывание истинно"], ["≤ faqat kichik", "≤ означает только меньше"]], 0, "Bitta qarshi misol umumiy fikrni rad etadi.", 'Один контрпример опровергает общее высказывание.'),
    ],
  },
  50: {
    titleUz: "50-dars. Doiraviy diagramma va ma'lumotlar",
    titleRu: 'Урок 50. Круговая диаграмма и представление данных',
    story: T("Lumo tadqiqotchilari energiya manbalari haqidagi ma'lumotni doiraviy diagrammadan o'qishi kerak.", 'Исследователям Лумо нужно прочитать данные об источниках энергии с круговой диаграммы.'),
    rule: T("Doiraviy diagramma butunni qismlarga ajratib ko'rsatadi. Barcha sektorlar bir butun; kattaroq sektor kattaroq ulushni bildiradi.", 'Круговая диаграмма показывает части целого. Все секторы составляют одно целое; больший сектор означает большую долю.'),
    finish: T("Energiya ma'lumotlari tahlil qilindi. Keyingi darsda butun 3-sinf bilimlarini yakuniy takrorlaysiz.", 'Данные об энергии проанализированы. На следующем уроке ты повторишь все основные знания 3 класса.'),
    checks: [
      q('A=8, B=5, C=3', "Eng katta ma'lumot qaysi?", 'Какое значение наибольшее?', ['A', 'B', 'C'], 0, "8 eng katta.", '8 — наибольшее.'),
      q('jami = qismlar yig‘indisi', "4+6+10 jami qancha?", 'Какова сумма 4+6+10?', ['16', '20', '24'], 1, "Uch qismni qo'shing.", 'Сложи три части.'),
      q('Quyosh 1/2; shamol 1/4; suv 1/4', "Eng katta sektor qaysi?", 'Какой сектор наибольший?', [["Quyosh", "Солнце"], ["Shamol", "Ветер"], ["Suv", "Вода"]], 0, "Yarim chorakdan katta.", 'Половина больше четверти.'),
      q('◔ = 1/4', "Bo'yalgan qism nimani bildiradi?", 'Что означает закрашенная часть?', [["Butunning choragini", "Четверть целого"], ["Butunning yarmini", "Половину целого"], ["Ikki butunni", "Два целых"]], 0, "Doira to'rt teng qismga bo'lingan.", 'Круг разделён на четыре равные части.'),
      q('40 o‘quvchi; 1/2 futbol', "Futbolni nechta o'quvchi tanlagan?", 'Сколько учеников выбрали футбол?', ['10', '20', '40'], 1, "40 ning yarmini toping.", 'Найди половину 40.'),
      q('25% = 1/4', "Ikki chorak necha foiz?", 'Сколько процентов составляют две четверти?', ['25%', '50%', '75%'], 1, "Ikki chorak yarim.", 'Две четверти — половина.'),
      q('barcha sektorlar = 100%', "Yetishmagan 20%+30%+?=100%", 'Найди недостающую часть: 20%+30%+?=100%.', ['40%', '50%', '60%'], 1, "100 dan 50 ni ayiring.", 'Вычти 50 из 100.'),
      q('Jami 60; sektor 1/3', "Sektor qiymati qancha?", 'Каково значение сектора?', ['15', '20', '30'], 1, "60 ni 3 ga bo'ling.", 'Раздели 60 на 3.'),
      q('A=45%, B=35%, C=?', "C necha foiz?", 'Сколько процентов C?', ['10%', '20%', '30%'], 1, "45+35=80.", '45+35=80.'),
      q('72 ning 1/8 qismi', "Mustaqil toping.", 'Найди самостоятельно.', ['8', '9', '12'], 1, "72:8.", 'Вычисли 72:8.'),
      q('Sektor=15; bu 1/3', "Jami miqdor qancha?", 'Каково общее количество?', ['5', '30', '45'], 2, "Uchta shunday qism.", 'Три такие части.'),
      q("Eng kichik sektor eng ko'pni bildiradi", "Xatoni toping.", 'Найди ошибку.', [["Eng katta sektor eng ko'pni bildiradi", "Больший сектор означает большее количество"], ["Fikr to'g'ri", "Утверждение верно"], ["Sektorlar solishtirilmaydi", "Секторы нельзя сравнивать"]], 0, "Sektor yuzalarini solishtiring.", 'Сравни площади секторов.'),
      q('24 detal: A=1/2, B=1/4, C=qolgani', "C nechta detal?", 'Сколько деталей C?', ['6', '8', '12'], 0, "12+6 ishlatilgan, 6 qoladi.", 'Использовано 12+6, осталось 6.'),
      q('80 birlik: 35% va 25%; qolgani', "Qolgan ulush necha foiz?", 'Сколько процентов осталось?', ['20%', '40%', '60%'], 1, "100−35−25.", 'Вычисли 100−35−25.'),
      q('butun = sektorlar yig‘indisi', "Asosiy xulosa qaysi?", 'Какой вывод главный?', [["Diagrammada qismlar bir butunni beradi", "На диаграмме части составляют целое"], ["Har sektor teng", "Все секторы равны"], ["Eng kichik sektor eng katta qiymat", "Меньший сектор — большее значение"]], 0, "Barcha sektorlarni birlashtiring.", 'Объедини все секторы.'),
    ],
  },
  51: {
    titleUz: '51-dars. Yakuniy takrorlash',
    titleRu: 'Урок 51. Итоговое повторение',
    story: T("Bit va do'stlari Lumo bilim arxivini ochish uchun sonlar, amallar, kasrlar, o'lchov va geometriya kalitlarini birlashtiradi.", 'Бит и друзья объединяют ключи чисел, действий, дробей, измерений и геометрии, чтобы открыть архив знаний Лумо.'),
    rule: T("Masalani yechishda avval mavzu va so'ralgan miqdorni aniqlang, mos model yoki amalni tanlang, birlikni yozing va natijani tekshiring.", 'При решении сначала определи тему и искомую величину, выбери модель или действие, запиши единицу и проверь результат.'),
    finish: T("3-sinf nazariy sayohati yakunlandi: bilim arxivi ochildi. Keyingi bosqich — alohida yakuniy nazorat.", 'Теоретическое путешествие 3 класса завершено: архив знаний открыт. Следующий этап — отдельный итоговый контроль.'),
    checks: [
      q('507 = 500 + ? + 7', "Yetishmagan razryad qaysi?", 'Какой разряд пропущен?', ['0', '50', '70'], 0, "507 da o'nliklar yo'q.", 'В числе 507 нет десятков.'),
      q('348 ? 384', "Mos belgini tanlang.", 'Выбери знак.', ['<', '>', '='], 0, "Yuzlik teng, o'nliklarni solishtiring.", 'Сотни равны, сравни десятки.'),
      q('24×3', "Ko'paytmani toping.", 'Найди произведение.', ['27', '72', '84'], 1, "20×3 va 4×3 ni qo'shing.", 'Сложи 20×3 и 4×3.'),
      q('37:5', "Bo'linma va qoldiq qaysi?", 'Каковы частное и остаток?', ['7 qoldiq 2', '6 qoldiq 7', '8 qoldiq 3'], 0, "5×7=35.", '5×7=35.'),
      q('3/4 va 2/4', "Qaysi kasr katta?", 'Какая дробь больше?', ['3/4', '2/4', 'Teng'], 0, "Maxraj teng bo'lsa suratni solishtiring.", 'При равных знаменателях сравни числители.'),
      q('32 ning 3/4 qismi', "Natijani toping.", 'Найди результат.', ['8', '24', '28'], 1, "32:4×3.", 'Вычисли 32:4×3.'),
      q('P=(a+b)×2; S=a×b', "Qaysi formula chegarani topadi?", 'Какая формула находит границу?', ['P formulasi', 'S formulasi', 'Ikkalasi'], 0, "Chegara — perimetr.", 'Граница — периметр.'),
      q('▭ 8 cm × 5 cm', "Yuza qancha?", 'Какова площадь?', ['13 cm²', '26 cm²', '40 cm²'], 2, "8×5.", 'Вычисли 8×5.'),
      q('2 kg 300 g', "Grammda yozing.", 'Запиши в граммах.', ['230 g', '2030 g', '2300 g'], 2, "2 kg=2000 g.", '2 кг=2000 г.'),
      q('14:35 + 50 min', "Vaqtni toping.", 'Найди время.', ['15:15', '15:25', '15:35'], 1, "25 daqiqada 15:00, yana 25.", 'Через 25 минут 15:00, затем ещё 25.'),
      q('x+27=60', "Tenglamani yeching.", 'Реши уравнение.', ['33', '37', '87'], 0, "60−27.", 'Вычисли 60−27.'),
      q('6×7+8=40', "Xatoni toping.", 'Найди ошибку.', [["Natija 50", "Результат 50"], ["Natija 40", "Результат 40"], ["Avval 7+8", "Сначала 7+8"]], 0, "42+8.", 'Вычисли 42+8.'),
      q('Bog‘ 9×4 m; panjara', "Necha metr panjara kerak?", 'Сколько метров ограды нужно?', ['13 m', '26 m', '36 m'], 1, "Perimetrni toping.", 'Найди периметр.'),
      q('60 o‘quvchining 40%i', "Nechta o'quvchi?", 'Сколько учеников?', ['20', '24', '40'], 1, "40%=4/10; 60:10×4.", '40%=4/10; 60:10×4.'),
      q('tushunish → model → amal → tekshiruv', "Eng muhim umumiy strategiya qaysi?", 'Какова главная общая стратегия?', [["Savolni tushunib, mos usul tanlash va tekshirish", "Понять вопрос, выбрать способ и проверить"], ["Barcha sonlarni qo'shish", "Сложить все числа"], ["Birliklarni e'tiborsiz qoldirish", "Не учитывать единицы"]], 0, "Usul masala turiga bog'liq.", 'Способ зависит от типа задачи.'),
    ],
  },
};

export function FinalBlockLesson({ number }) {
  const config = FINAL_LESSONS[number];
  return (
    <Grade3LessonShell
      lessonId={`num-3-${number}`}
      screens={buildScreens(config)}
      titleUz={config.titleUz}
      titleRu={config.titleRu}
    />
  );
}
