const tx = (uz, ru) => ({
  uz: {
    eyebrow: uz.e,
    setup: uz.s,
    ask: uz.a,
    options: uz.o,
    correct: `To'g'ri! ${uz.y}`,
    wrong: `Maslahat: ${uz.n}`,
    rule: uz.r,
    visual: uz.v,
    tiles: uz.tiles,
    placeholder: uz.p,
    orderHint: "Kartalarni kerakli tartibda bosing.",
  },
  ru: {
    eyebrow: ru.e,
    setup: ru.s,
    ask: ru.a,
    options: ru.o,
    correct: `Верно! ${ru.y}`,
    wrong: `Подсказка: ${ru.n}`,
    rule: ru.r,
    visual: ru.v,
    tiles: ru.tiles,
    placeholder: ru.p,
    orderHint: 'Нажимай карточки в нужном порядке.',
  },
});

const q = (id, label, level, tag, type, emoji, correct, uz, ru, inputMode) => ({
  id, label, level, tag, type, emoji, correct, inputMode, text: tx(uz, ru),
});

const cq = (id, label, level, tag, type, emoji, correct, uz, ru, inputMode) => q(
  id, label, level, tag, type, emoji, correct,
  { e: 'Mashq', s: uz[0], a: uz[1], o: uz[2], y: uz[3], n: uz[4], v: uz[5], r: uz[6], p: 'Javob' },
  { e: 'Задание', s: ru[0], a: ru[1], o: ru[2], y: ru[3], n: ru[4], v: ru[5], r: ru[6], p: 'Ответ' },
  inputMode,
);

export const DARS10_BANK = {
  title: "Dars 10 · 10 va 100 ga ko'paytirish va bo'lish",
  items: [
    q('01', "O'n marta katta", '🟢', 'd11-times-ten', 'choice', '🔟', 1,
      { e: "Tanish qoida", s: "34 soni o'n marta kattalashtiriladi.", a: "34 × 10 nechaga teng?", o: ['34', '340', '3 400'], y: "Har bir raqam bir xona chapga siljidi: 34 × 10 = 340.", n: "10 ga ko'paytirganda razryadlar bir xona chapga siljiydi.", r: "10 ga ko'paytirish — razryadlarni bir xona chapga siljitish.", v: '34 × 10 = ?' },
      { e: 'Знакомое правило', s: 'Число 34 увеличивают в десять раз.', a: 'Чему равно 34 × 10?', o: ['34', '340', '3 400'], y: 'Каждая цифра сдвинулась на один разряд влево: 34 × 10 = 340.', n: 'При умножении на 10 разряды сдвигаются на одну позицию влево.', r: 'Умножить на 10 — сдвинуть разряды на одну позицию влево.', v: '34 × 10 = ?' }),
    q('02', "Yuz marta katta", '🟢', 'd11-times-hundred', 'input', '💯', ['700', '7*100'],
      { e: "Sonni yozing", s: "7 birlik yuz marta kattalashsa, 7 yuzlik hosil bo'ladi.", a: "7 × 100 natijasini kiriting.", y: "7 × 100 = 700.", n: "Yetti yuzlik raqam bilan qanday yozilishini eslang.", r: "100 ga ko'paytirishda razryadlar ikki xona chapga siljiydi.", v: '7 × 100 = ?', p: 'Javob' },
      { e: 'Запиши число', s: 'Если 7 единиц увеличить в сто раз, получится 7 сотен.', a: 'Введи результат 7 × 100.', y: '7 × 100 = 700.', n: 'Вспомни, как цифрами записать семь сотен.', r: 'При умножении на 100 разряды сдвигаются на две позиции влево.', v: '7 × 100 = ?', p: 'Ответ' }),
    q('03', "Razryad zinasi", '🟡', 'd11-place-order', 'order', '🪜', [0, 2, 1],
      { e: "Tartiblang", s: "6 sonini avval 10 ga, keyin yana 10 ga ko'paytiramiz.", a: "Sonlarni kichikdan katta razryadga qarab joylang.", o: ['6', '600', '60'], y: "6 → 60 → 600: har safar bir xona chapga siljish bor.", n: "Avval 6 × 10, so'ng hosil bo'lgan sonni yana 10 ga ko'paytiring.", r: "Ikki marta 10 ga ko'paytirish 100 ga ko'paytirish bilan teng.", v: '6 → ? → ?' },
      { e: 'Расположи', s: 'Число 6 сначала умножаем на 10, затем ещё раз на 10.', a: 'Расположи числа по возрастанию разряда.', o: ['6', '600', '60'], y: '6 → 60 → 600: каждый раз сдвиг на один разряд влево.', n: 'Сначала найди 6 × 10, затем ещё раз умножь результат на 10.', r: 'Дважды умножить на 10 — то же, что умножить на 100.', v: '6 → ? → ?' }),
    q('04', "Nolni qaytaring", '🟡', 'd11-divide-ten', 'input', '↩️', ['42', '420:10'],
      { e: "Teskari amal", s: "420 sonini 10 ga bo'lsak, razryadlar bir xona o'ngga qaytadi.", a: "420 : 10 natijasini kiriting.", y: "420 : 10 = 42.", n: "420 da nechta to'liq o'nlik borligini o'ylang.", r: "10 ga bo'lish — razryadlarni bir xona o'ngga siljitish.", v: '420 : 10 = ?', p: 'Javob' },
      { e: 'Обратное действие', s: 'При делении 420 на 10 разряды сдвигаются на одну позицию вправо.', a: 'Введи результат 420 : 10.', y: '420 : 10 = 42.', n: 'Подумай, сколько полных десятков в числе 420.', r: 'Деление на 10 сдвигает разряды на одну позицию вправо.', v: '420 : 10 = ?', p: 'Ответ' }),
    q('05', "Yo'qolgan ko'paytuvchi", '🟡', 'd11-missing-factor', 'choice', '🧩', 2,
      { e: "Yetishmayotgan son", s: "9 ni noma'lum songa ko'paytirganda 900 chiqdi.", a: "9 × □ = 900 tenglikdagi □ ni toping.", o: ['10', '90', '100'], y: "9 × 100 = 900, demak □ = 100.", n: "900 da nechta yuzlik bor?", r: "Noma'lum ko'paytuvchi bo'lish bilan tekshiriladi: 900 : 9 = 100.", v: '9 × □ = 900' },
      { e: 'Пропущенное число', s: 'При умножении 9 на неизвестное число получилось 900.', a: 'Найди □ в равенстве 9 × □ = 900.', o: ['10', '90', '100'], y: '9 × 100 = 900, значит □ = 100.', n: 'Сколько сотен в числе 900?', r: 'Неизвестный множитель проверяют делением: 900 : 9 = 100.', v: '9 × □ = 900' }),
    q('06', "Qutilar masalasi", '🟡', 'd11-boxes-story', 'choice', '📦', 1,
      { e: "Matnli masala", s: "Omborda 8 ta quti bor. Har bir qutida 100 tadan chiroq.", a: "Jami nechta chiroq bor?", o: ['80', '800', '8 000'], y: "8 ta yuzlik — 800 ta chiroq.", n: "Qutilar sonini har qutidagi chiroqlar soniga ko'paytiring.", r: "8 × 100 = 800.", v: '8 quti × 100 ta' },
      { e: 'Задача', s: 'На складе 8 коробок. В каждой коробке по 100 ламп.', a: 'Сколько всего ламп?', o: ['80', '800', '8 000'], y: 'Восемь сотен — это 800 ламп.', n: 'Умножь число коробок на число ламп в каждой.', r: '8 × 100 = 800.', v: '8 коробок × 100' }),
    q('07', "To'g'ri tengliklar", '🟡', 'd11-equivalent-multi', 'multi', '✅', [0, 1, 3],
      { e: "Bir nechtasini tanlang", s: "Har bir tenglikda razryad siljishini tekshiring.", a: "Barcha to'g'ri tengliklarni belgilang.", o: ['50 × 10 = 500', '700 : 100 = 7', '36 × 10 = 3 600', '900 : 10 = 90'], y: "Uchta tenglikda siljish to'g'ri bajarilgan.", n: "Har tenglikni alohida tekshiring; 36 o'n marta oshsa 360 bo'ladi.", r: "Ko'paytirish chapga, bo'lish o'ngga siljitadi.", v: '× 10   : 10   : 100' },
      { e: 'Выбери несколько', s: 'Проверь сдвиг разрядов в каждом равенстве.', a: 'Отметь все верные равенства.', o: ['50 × 10 = 500', '700 : 100 = 7', '36 × 10 = 3 600', '900 : 10 = 90'], y: 'В трёх равенствах сдвиг выполнен правильно.', n: 'Проверь каждое равенство отдельно; 36, увеличенное в десять раз, равно 360.', r: 'Умножение сдвигает влево, деление — вправо.', v: '× 10   : 10   : 100' }),
    q('08', "Nol ichkarida", '🔴', 'd11-zero-trap', 'choice', '🕳️', 2,
      { e: "Tuzoq holati", s: "405 sonidagi nol o'nlik o'rnini saqlab turibdi.", a: "405 × 10 qaysi son?", o: ['450', '405', '4 050'], y: "Barcha razryadlar siljidi: 405 × 10 = 4 050.", n: "Nolni tashlamang; butun 405 sonini bir xona chapga siljiting.", r: "Son ichidagi nol ham razryad o'rnini saqlaydi.", v: '405 × 10 = ?' },
      { e: 'Ловушка с нулём', s: 'Ноль в числе 405 сохраняет место десятков.', a: 'Чему равно 405 × 10?', o: ['450', '405', '4 050'], y: 'Все разряды сдвинулись: 405 × 10 = 4 050.', n: 'Не теряй ноль; сдвинь всё число 405 на одну позицию влево.', r: 'Ноль внутри числа тоже сохраняет место разряда.', v: '405 × 10 = ?' }),
    q('09', "Xatoni toping", '🔴', 'd11-find-error', 'choice', '🔎', 1,
      { e: "Xato tahlili", s: "Anvar: «27 × 10 = 2 700», dedi.", a: "Anvarning xatosi qayerda?", o: ["Nol qo'shmagan", "Razryadlarni ikki xona siljitgan", "27 ni 10 ga bo'lgan"], y: "U 100 ga ko'paytirgandek ikki xona siljitgan.", n: "10 va 100 ga ko'paytirishdagi siljishlar sonini solishtiring.", r: "×10 — bir xona; ×100 — ikki xona.", v: '27 × 10 = 2 700 ✗' },
      { e: 'Найди ошибку', s: 'Анвар сказал: «27 × 10 = 2 700».', a: 'В чём ошибка Анвара?', o: ['Не добавил ноль', 'Сдвинул разряды на две позиции', 'Разделил 27 на 10'], y: 'Он сдвинул число на две позиции, будто умножал на 100.', n: 'Сравни число сдвигов при умножении на 10 и на 100.', r: '×10 — одна позиция; ×100 — две позиции.', v: '27 × 10 = 2 700 ✗' }),
    q('10', "Ikki qadamli transfer", '🔴', 'd11-transfer', 'input', '🚀', ['36', '3600:100'],
      { e: "Yangi vaziyat", s: "3 600 signal 100 ta teng paketga ajratildi.", a: "Har paketdagi signal sonini kiriting.", y: "3 600 : 100 = 36.", n: "100 ga bo'lishda razryadlarni ikki xona o'ngga siljiting.", r: "Ko'paytirish bilan tekshiruv: 36 × 100 = 3 600.", v: '3 600 : 100 = ?', p: 'Har paketda' },
      { e: 'Новая ситуация', s: '3 600 сигналов разделили поровну на 100 пакетов.', a: 'Введи число сигналов в каждом пакете.', y: '3 600 : 100 = 36.', n: 'При делении на 100 сдвинь разряды на две позиции вправо.', r: 'Проверка умножением: 36 × 100 = 3 600.', v: '3 600 : 100 = ?', p: 'В пакете' }),
  ],
};

export const DARS11_BANK = {
  title: "Dars 11 · Yig'indini ko'paytirish",
  items: [
    q('01', "Qulay yoyilma", '🟢', 'd12-split', 'choice', '🧱', 0,
      { e: "Tanish va eslash", s: "14 soni 1 o'nlik va 4 birlikdan tuzilgan.", a: "14 × 3 ni hisoblash uchun qaysi yoyilma qulay?", o: ['(10 + 4) × 3', '(7 + 7) × 2', '10 + 4 × 3'], y: "14 = 10 + 4, ikkala qism ham 3 ga ko'payadi.", n: "14 ni o'nlik va birlikka ajrating.", r: "(a + b) × c = a × c + b × c.", v: '14 = 10 + 4' },
      { e: 'Удобное разложение', s: 'Число 14 состоит из 1 десятка и 4 единиц.', a: 'Какое разложение удобно для вычисления 14 × 3?', o: ['(10 + 4) × 3', '(7 + 7) × 2', '10 + 4 × 3'], y: '14 = 10 + 4, обе части умножаются на 3.', n: 'Разложи 14 на десятки и единицы.', r: '(a + b) × c = a × c + b × c.', v: '14 = 10 + 4' }),
    q('02', "Hisoblang", '🟢', 'd12-calculate', 'input', '✍️', ['92', '23*4'],
      { e: "Sodda qo'llash", s: "23 × 4 = 20 × 4 + 3 × 4.", a: "Natijani kiriting.", y: "80 + 12 = 92.", n: "Avval 20 × 4 va 3 × 4 ni alohida toping.", r: "Har bir qo'shiluvchi ko'paytiriladi, natijalar qo'shiladi.", v: '20 × 4 + 3 × 4 = ?', p: 'Natija' },
      { e: 'Простое применение', s: '23 × 4 = 20 × 4 + 3 × 4.', a: 'Введи результат.', y: '80 + 12 = 92.', n: 'Сначала отдельно найди 20 × 4 и 3 × 4.', r: 'Каждое слагаемое умножается, результаты складываются.', v: '20 × 4 + 3 × 4 = ?', p: 'Результат' }),
    q('03', "Qadamlar", '🟡', 'd12-step-order', 'order', '🪜', [1, 2, 0],
      { e: "Usulni tartiblang", s: "32 × 3 ni yig'indini ko'paytirish usulida yechamiz.", a: "Qadamlarni to'g'ri tartibga keltiring.", o: ['90 + 6 = 96', '32 = 30 + 2', '30 × 3 = 90; 2 × 3 = 6'], y: "Avval yoyamiz, so'ng qismlarni ko'paytirib, oxirida qo'shamiz.", n: "Sonni hisoblashdan oldin o'nlik va birlikka ajrating.", r: "Yoyish → har bo'lakni ko'paytirish → qo'shish.", v: '32 × 3' },
      { e: 'Порядок действий', s: 'Решим 32 × 3 умножением суммы.', a: 'Расположи шаги в правильном порядке.', o: ['90 + 6 = 96', '32 = 30 + 2', '30 × 3 = 90; 2 × 3 = 6'], y: 'Сначала раскладываем, затем умножаем части и складываем.', n: 'До вычислений разложи число на десятки и единицы.', r: 'Разложить → умножить каждую часть → сложить.', v: '32 × 3' }),
    q('04', "Ikki model", '🟡', 'd12-equivalent-model', 'choice', '🧮', 2,
      { e: "Boshqa ko'rinish", s: "46 ta kristall 2 ta teng qatorda joylashgan.", a: "46 × 2 ga teng yozuvni tanlang.", o: ['40 × 2 + 6', '46 + 2', '40 × 2 + 6 × 2'], y: "40 va 6 ning har biri 2 ga ko'paytiriladi.", n: "Birliklar qismi ham 2 ga ko'payishi kerak.", r: "(40 + 6) × 2 = 40 × 2 + 6 × 2.", v: '(40 + 6) × 2' },
      { e: 'Другая модель', s: '46 кристаллов расположены в двух одинаковых рядах.', a: 'Выбери запись, равную 46 × 2.', o: ['40 × 2 + 6', '46 + 2', '40 × 2 + 6 × 2'], y: 'И 40, и 6 умножаются на 2.', n: 'Часть с единицами тоже нужно умножить на 2.', r: '(40 + 6) × 2 = 40 × 2 + 6 × 2.', v: '(40 + 6) × 2' }),
    q('05', "Yetishmayotgan birlik", '🟡', 'd12-missing-part', 'input', '🧩', ['3'],
      { e: "Noma'lum qism", s: "(40 + □) × 2 = 86.", a: "Bo'sh katakka qaysi son yoziladi?", y: "43 × 2 = 86, demak □ = 3.", n: "86 ning yarmi 43; 43 da 40 dan ortiq nechta birlik bor?", r: "Yoyilmadagi qismlar asl sonni hosil qiladi.", v: '(40 + □) × 2 = 86', p: '□' },
      { e: 'Пропущенная часть', s: '(40 + □) × 2 = 86.', a: 'Какое число нужно записать вместо □?', y: '43 × 2 = 86, значит □ = 3.', n: 'Половина 86 равна 43; сколько единиц сверх 40?', r: 'Части разложения вместе образуют исходное число.', v: '(40 + □) × 2 = 86', p: '□' }),
    q('06', "Raflar masalasi", '🟡', 'd12-shelf-story', 'input', '🗄️', ['144', '24*6'],
      { e: "Matnli masala", s: "Ustaxonada 6 ta raf bor. Har bir rafda 24 tadan modul.", a: "Jami modullar sonini toping.", y: "20 × 6 + 4 × 6 = 120 + 24 = 144.", n: "24 ni 20 va 4 ga ajratib, ikkala qismini 6 ga ko'paytiring.", r: "6 × 24 = 144 ta modul.", v: '6 × 24 = ?', p: 'Modullar soni' },
      { e: 'Задача про полки', s: 'В мастерской 6 полок. На каждой по 24 модуля.', a: 'Найди общее число модулей.', y: '20 × 6 + 4 × 6 = 120 + 24 = 144.', n: 'Разложи 24 на 20 и 4 и умножь обе части на 6.', r: '6 × 24 = 144 модуля.', v: '6 × 24 = ?', p: 'Число модулей' }),
    q('07', "Teng yozuvlar", '🟡', 'd12-equivalents', 'multi', '🔗', [0, 1, 3],
      { e: "Mos natijalar", s: "18 × 5 qiymati 90 ga teng.", a: "18 × 5 ga teng barcha yozuvlarni belgilang.", o: ['10 × 5 + 8 × 5', '9 × 10', '18 + 5', '20 × 5 − 2 × 5'], y: "Uchala yozuv ham 90 ni beradi.", n: "Har bir variantni hisoblab, 90 bilan solishtiring.", r: "Sonni qo'shiluvchilarga ham, qulay ayirmaga ham ajratish mumkin.", v: '18 × 5 = 90' },
      { e: 'Равные записи', s: 'Значение 18 × 5 равно 90.', a: 'Отметь все записи, равные 18 × 5.', o: ['10 × 5 + 8 × 5', '9 × 10', '18 + 5', '20 × 5 − 2 × 5'], y: 'Три записи дают 90.', n: 'Вычисли каждый вариант и сравни с 90.', r: 'Число можно представить суммой или удобной разностью.', v: '18 × 5 = 90' }),
    q('08', "Teskari yig'ish", '🔴', 'd12-reverse', 'choice', '↩️', 1,
      { e: "Teskari topshiriq", s: "30 × 4 + 6 × 4 yozuvi bitta ko'paytmadan hosil bo'lgan.", a: "Asl ko'paytmani toping.", o: ['34 × 6', '36 × 4', '30 × 10'], y: "Umumiy ko'paytuvchi 4, qo'shiluvchilar 30 va 6: (30 + 6) × 4.", n: "Ikkala ko'paytmada takrorlangan ko'paytuvchini toping.", r: "a × c + b × c = (a + b) × c.", v: '30 × 4 + 6 × 4' },
      { e: 'Обратное задание', s: 'Запись 30 × 4 + 6 × 4 получена из одного произведения.', a: 'Найди исходное произведение.', o: ['34 × 6', '36 × 4', '30 × 10'], y: 'Общий множитель 4, части 30 и 6: (30 + 6) × 4.', n: 'Найди множитель, который повторяется в обоих произведениях.', r: 'a × c + b × c = (a + b) × c.', v: '30 × 4 + 6 × 4' }),
    q('09', "Xatoni tuzating", '🔴', 'd12-error', 'choice', '🔎', 0,
      { e: "Xato tahlili", s: "Jasur: «27 × 3 = 20 × 3 + 7 = 67», dedi.", a: "Qaysi qadam tuzatilishi kerak?", o: ['7 ham 3 ga ko‘paytirilishi kerak', '20 ni 3 ga bo‘lish kerak', '27 ni 20 + 3 deb yoyish kerak'], y: "Ikkala qo'shiluvchi ham 3 ga ko'payadi.", n: "Yig'indini ko'paytirishda qavs ichidagi har bir qismga qarang.", r: "27 × 3 = 20 × 3 + 7 × 3 = 81.", v: '20 × 3 + 7 = 67 ✗' },
      { e: 'Исправь ошибку', s: 'Жасур сказал: «27 × 3 = 20 × 3 + 7 = 67».', a: 'Какой шаг нужно исправить?', o: ['7 тоже нужно умножить на 3', '20 нужно разделить на 3', '27 нужно разложить как 20 + 3'], y: 'Обе части суммы умножаются на 3.', n: 'При умножении суммы проверь каждую часть в скобках.', r: '27 × 3 = 20 × 3 + 7 × 3 = 81.', v: '20 × 3 + 7 = 67 ✗' }),
    q('10', "Transfer", '🔴', 'd12-transfer', 'input', '🚀', ['240', '48*5'],
      { e: "Yangi son", s: "48 ni 50 − 2 yoki 40 + 8 ko'rinishida hisoblash mumkin.", a: "48 × 5 natijasini kiriting.", y: "40 × 5 + 8 × 5 = 200 + 40 = 240.", n: "48 ni 40 va 8 ga ajrating.", r: "Qulay yoyilma hisobni tezlashtiradi, natija o'zgarmaydi.", v: '48 × 5 = ?', p: 'Natija' },
      { e: 'Новое число', s: '48 можно представить как 50 − 2 или 40 + 8.', a: 'Введи результат 48 × 5.', y: '40 × 5 + 8 × 5 = 200 + 40 = 240.', n: 'Разложи 48 на 40 и 8.', r: 'Удобное разложение ускоряет вычисление, не меняя результат.', v: '48 × 5 = ?', p: 'Результат' }),
  ],
};

export const DARS12_BANK = {
  title: "Dars 12 · Yig'indini bo'lish",
  items: [
    q('01', "Bo'linadigan yoyilma", '🟢', 'd13-split', 'choice', '✂️', 0,
      { e: "Tanish qoida", s: "84 ni 4 ga bo'lish uchun qismlarning har biri 4 ga bo'linishi kerak.", a: "Qaysi yoyilma eng qulay?", o: ['(80 + 4) : 4', '(70 + 14) : 4', '(50 + 34) : 4'], y: "80 ham, 4 ham 4 ga qoldiqsiz bo'linadi.", n: "Har bir qism 4 ga qoldiqsiz bo'linadigan variantni toping.", r: "(a + b) : c = a : c + b : c, agar qismlar c ga bo'linsa.", v: '84 : 4' },
      { e: 'Делимое разложение', s: 'Чтобы разделить 84 на 4, каждая часть должна делиться на 4.', a: 'Какое разложение самое удобное?', o: ['(80 + 4) : 4', '(70 + 14) : 4', '(50 + 34) : 4'], y: 'И 80, и 4 делятся на 4 без остатка.', n: 'Найди вариант, где каждая часть делится на 4.', r: '(a + b) : c = a : c + b : c, если части делятся на c.', v: '84 : 4' }),
    q('02', "Hisoblang", '🟢', 'd13-calculate', 'input', '🧮', ['32', '96:3'],
      { e: "Sodda qo'llash", s: "96 : 3 = (90 + 6) : 3.", a: "Natijani kiriting.", y: "90 : 3 + 6 : 3 = 30 + 2 = 32.", n: "90 va 6 ni alohida 3 ga bo'ling.", r: "Qulay qismlarni alohida bo'lib, natijalarni qo'shamiz.", v: '96 : 3 = ?', p: 'Natija' },
      { e: 'Простое применение', s: '96 : 3 = (90 + 6) : 3.', a: 'Введи результат.', y: '90 : 3 + 6 : 3 = 30 + 2 = 32.', n: 'Отдельно раздели 90 и 6 на 3.', r: 'Удобные части делим отдельно и складываем результаты.', v: '96 : 3 = ?', p: 'Результат' }),
    q('03', "Qadamlar", '🟡', 'd13-step-order', 'order', '🪜', [2, 0, 1],
      { e: "Usulni tartiblang", s: "68 : 4 ni qulay qismlarga ajratib yechamiz.", a: "Qadamlarni to'g'ri tartibda joylang.", o: ['60 : 4 emas; 40 : 4 va 28 : 4', '10 + 7 = 17', '68 = 40 + 28'], y: "Avval qulay yoyilma, keyin bo'lish, oxirida qo'shish.", n: "Birinchi qadam sonni bo'linadigan qismlarga ajratishdir.", r: "Qulay yoyish → qismlarni bo'lish → natijalarni qo'shish.", v: '68 : 4' },
      { e: 'Порядок способа', s: 'Решим 68 : 4, разложив на удобные части.', a: 'Расположи шаги по порядку.', o: ['Не 60 : 4; берём 40 : 4 и 28 : 4', '10 + 7 = 17', '68 = 40 + 28'], y: 'Сначала удобное разложение, затем деление и сложение.', n: 'Первый шаг — разложить число на делящиеся части.', r: 'Удобно разложить → разделить части → сложить результаты.', v: '68 : 4' }),
    q('04', "Qulay qismlar", '🟡', 'd13-valid-split', 'choice', '🧱', 2,
      { e: "Yoyilmani tanlang", s: "78 : 6 ni hisoblamoqchimiz.", a: "Qaysi yoyilmada ikkala qism ham 6 ga bo'linadi?", o: ['70 + 8', '50 + 28', '60 + 18'], y: "60 : 6 = 10 va 18 : 6 = 3.", n: "Har bir qo'shiluvchini 6 ga bo'lib ko'ring.", r: "78 : 6 = 60 : 6 + 18 : 6 = 13.", v: '78 = ? + ?' },
      { e: 'Выбери части', s: 'Нужно вычислить 78 : 6.', a: 'В каком разложении обе части делятся на 6?', o: ['70 + 8', '50 + 28', '60 + 18'], y: '60 : 6 = 10 и 18 : 6 = 3.', n: 'Попробуй разделить каждое слагаемое на 6.', r: '78 : 6 = 60 : 6 + 18 : 6 = 13.', v: '78 = ? + ?' }),
    q('05', "Yo'qolgan qism", '🟡', 'd13-missing-part', 'input', '🧩', ['7'],
      { e: "Noma'lum qo'shiluvchi", s: "(70 + □) : 7 = 11.", a: "□ o'rniga qaysi son yoziladi?", y: "11 × 7 = 77; 77 = 70 + 7.", n: "Avval bo'linuvchini teskari amal bilan toping: 11 × 7.", r: "Bo'lish ko'paytirish bilan tekshiriladi.", v: '(70 + □) : 7 = 11', p: '□' },
      { e: 'Пропущенная часть', s: '(70 + □) : 7 = 11.', a: 'Какое число нужно записать вместо □?', y: '11 × 7 = 77; 77 = 70 + 7.', n: 'Сначала найди делимое обратным действием: 11 × 7.', r: 'Деление проверяется умножением.', v: '(70 + □) : 7 = 11', p: '□' }),
    q('06', "Taqsimot masalasi", '🟡', 'd13-story', 'input', '📦', ['21', '84:4'],
      { e: "Matnli masala", s: "84 ta detal 4 ta rafga teng taqsimlandi.", a: "Har bir rafda nechta detal bor?", y: "80 : 4 + 4 : 4 = 20 + 1 = 21.", n: "84 ni 80 va 4 ga ajratib bo'ling.", r: "84 : 4 = 21 ta detal.", v: '84 detal : 4 raf', p: 'Har rafda' },
      { e: 'Задача на распределение', s: '84 детали поровну распределили на 4 полки.', a: 'Сколько деталей на каждой полке?', y: '80 : 4 + 4 : 4 = 20 + 1 = 21.', n: 'Разложи 84 на 80 и 4.', r: '84 : 4 = 21 деталь.', v: '84 детали : 4 полки', p: 'На полке' }),
    q('07', "Yaroqli yoyilmalar", '🟡', 'd13-splits-multi', 'multi', '✅', [0, 1, 3],
      { e: "Bir nechtasini tanlang", s: "72 : 3 uchun har bir qism 3 ga bo'linishi kerak.", a: "Barcha yaroqli yoyilmalarni belgilang.", o: ['60 + 12', '30 + 42', '50 + 22', '69 + 3'], y: "Uchta yoyilmada ikkala qism ham 3 ga bo'linadi.", n: "Har juftlikdagi ikkala sonni 3 ga bo'lib tekshiring.", r: "Yoyilma yig'indisi 72 bo'lishi va qismlar 3 ga bo'linishi shart.", v: '72 : 3' },
      { e: 'Выбери несколько', s: 'Для 72 : 3 каждая часть должна делиться на 3.', a: 'Отметь все подходящие разложения.', o: ['60 + 12', '30 + 42', '50 + 22', '69 + 3'], y: 'В трёх разложениях обе части делятся на 3.', n: 'Проверь делением оба числа в каждой паре.', r: 'Сумма должна быть 72, а обе части должны делиться на 3.', v: '72 : 3' }),
    q('08', "Teskari tekshiruv", '🔴', 'd13-inverse', 'choice', '↩️', 1,
      { e: "Teskari topshiriq", s: "62 : 2 natijasi noma'lum.", a: "Qaysi ko'paytma javobni tekshiradi?", o: ['30 × 2 = 60', '31 × 2 = 62', '32 × 2 = 64'], y: "31 × 2 = 62, demak 62 : 2 = 31.", n: "Bo'linma × bo'luvchi bo'linuvchiga teng bo'lishi kerak.", r: "a : b = c bo'lsa, c × b = a.", v: '62 : 2 = ?' },
      { e: 'Обратная проверка', s: 'Результат 62 : 2 неизвестен.', a: 'Какое произведение проверяет ответ?', o: ['30 × 2 = 60', '31 × 2 = 62', '32 × 2 = 64'], y: '31 × 2 = 62, значит 62 : 2 = 31.', n: 'Частное × делитель должно равняться делимому.', r: 'Если a : b = c, то c × b = a.', v: '62 : 2 = ?' }),
    q('09', "Xatoni toping", '🔴', 'd13-error', 'choice', '🔎', 2,
      { e: "Xato tahlili", s: "Ra'no: «96 : 4 = 80 : 4 + 16 = 36», dedi.", a: "Qaysi xato qilingan?", o: ['80 ni 4 ga bo‘lgan', '96 ni noto‘g‘ri yoygan', '16 ni 4 ga bo‘lmagan'], y: "Yoyilmaning ikkala qismi ham 4 ga bo'linishi kerak.", n: "80 va 16 ning oldidagi amallarni solishtiring.", r: "96 : 4 = 80 : 4 + 16 : 4 = 24.", v: '80 : 4 + 16 = 36 ✗' },
      { e: 'Найди ошибку', s: 'Рано сказала: «96 : 4 = 80 : 4 + 16 = 36».', a: 'Какая ошибка допущена?', o: ['80 разделили на 4', '96 неверно разложили', '16 не разделили на 4'], y: 'Обе части разложения нужно разделить на 4.', n: 'Сравни действия перед числами 80 и 16.', r: '96 : 4 = 80 : 4 + 16 : 4 = 24.', v: '80 : 4 + 16 = 36 ✗' }),
    q('10', "Transfer", '🔴', 'd13-transfer', 'input', '🚀', ['22', '88:4'],
      { e: "Yangi vaziyat", s: "88 ni 80 + 8 ko'rinishida qulay yoyish mumkin.", a: "88 : 4 natijasini kiriting.", y: "80 : 4 + 8 : 4 = 20 + 2 = 22.", n: "Ikkala qulay qismni 4 ga bo'ling.", r: "Tekshiruv: 22 × 4 = 88.", v: '88 : 4 = ?', p: 'Natija' },
      { e: 'Новая ситуация', s: '88 удобно разложить как 80 + 8.', a: 'Введи результат 88 : 4.', y: '80 : 4 + 8 : 4 = 20 + 2 = 22.', n: 'Раздели обе удобные части на 4.', r: 'Проверка: 22 × 4 = 88.', v: '88 : 4 = ?', p: 'Результат' }),
  ],
};

export const DARS13_BANK = {
  title: "Dars 13 · Amallar tartibi",
  items: [
    cq('01', 'Avval qaysi amal?', '🟢', 'd14-priority', 'choice', '🥇', 1,
      ["5 + 3 × 2 ifodada ikki xil amal bor.", "To'g'ri natijani tanlang.", ['16', '11', '13'], "Avval 3 × 2 = 6, keyin 5 + 6 = 11.", "Ko'paytirish qo'shishdan oldin bajariladi.", '5 + 3 × 2', "Avval ko'paytirish va bo'lish."],
      ['В выражении 5 + 3 × 2 два разных действия.', 'Выбери верный результат.', ['16', '11', '13'], 'Сначала 3 × 2 = 6, затем 5 + 6 = 11.', 'Умножение выполняется раньше сложения.', '5 + 3 × 2', 'Сначала умножение и деление.']),
    cq('02', 'Qavs ichida', '🟢', 'd14-parentheses', 'input', '🧮', ['24'],
      ["Qavs amal tartibini o'zgartiradi.", "(12 − 4) × 3 ni hisoblang.", undefined, "12 − 4 = 8; 8 × 3 = 24.", "Avval qavs ichidagi ayirmani toping.", '(12 − 4) × 3', "Qavs ichidagi amal birinchi bajariladi."],
      ['Скобки меняют порядок действий.', 'Вычисли (12 − 4) × 3.', undefined, '12 − 4 = 8; 8 × 3 = 24.', 'Сначала найди разность в скобках.', '(12 − 4) × 3', 'Действие в скобках выполняется первым.']),
    cq('03', 'Qoidani tartiblang', '🟡', 'd14-rule-order', 'order', '🪜', [2, 0, 1],
      ["Ifodani hisoblashning uch pog'onasi bor.", "Qoidalarni tartiblang.", ["Ko'paytirish va bo'lish", "Qo'shish va ayirish", "Qavs ichidagi amal"], "Qavs → ko'paytirish/bo'lish → qo'shish/ayirish.", "Eng avval qavsni toping.", '1 → 2 → 3', "Bir xil pog'onadagi amallar chapdan o'ngga bajariladi."],
      ['У вычисления выражения есть три ступени.', 'Расположи правила по порядку.', ['Умножение и деление', 'Сложение и вычитание', 'Действие в скобках'], 'Скобки → умножение/деление → сложение/вычитание.', 'Сначала найди скобки.', '1 → 2 → 3', 'Действия одной ступени выполняются слева направо.']),
    cq('04', "Bo'lish va qo'shish", '🟡', 'd14-div-add', 'choice', '⚖️', 2,
      ["24 : 6 + 7 ifodada bo'lish ustun turadi.", "Natijani toping.", ['2', '8', '11'], "24 : 6 = 4; 4 + 7 = 11.", "24 ni avval 6 ga bo'ling.", '24 : 6 + 7', "Bo'lish qo'shishdan oldin bajariladi."],
      ['В выражении 24 : 6 + 7 деление главнее.', 'Найди результат.', ['2', '8', '11'], '24 : 6 = 4; 4 + 7 = 11.', 'Сначала раздели 24 на 6.', '24 : 6 + 7', 'Деление выполняется раньше сложения.']),
    cq('05', "Yo'qolgan son", '🟡', 'd14-missing', 'input', '🧩', ['5'],
      ["6 × □ + 4 = 34.", "□ o'rnidagi sonni kiriting.", undefined, "34 − 4 = 30; 30 : 6 = 5.", "Avval oxirgi +4 amalini teskari bajaring.", '6 × □ + 4 = 34', "Teskari amallar ifodani orqadan yechishga yordam beradi."],
      ['6 × □ + 4 = 34.', 'Введи число вместо □.', undefined, '34 − 4 = 30; 30 : 6 = 5.', 'Сначала выполни обратное к последнему +4 действие.', '6 × □ + 4 = 34', 'Обратные действия помогают решать выражение с конца.']),
    cq('06', 'Paketlar masalasi', '🟡', 'd14-story', 'input', '🎁', ['27'],
      ["4 paketning har birida 6 ta detal, stol ustida yana 3 ta detal bor.", "Jami nechta detal?", undefined, "4 × 6 + 3 = 24 + 3 = 27.", "Avval paketlardagi teng guruhlarni hisoblang.", '4 × 6 + 3', "Teng guruhlar avval ko'paytiriladi."],
      ['В каждом из 4 пакетов по 6 деталей, ещё 3 лежат на столе.', 'Сколько всего деталей?', undefined, '4 × 6 + 3 = 24 + 3 = 27.', 'Сначала посчитай равные группы в пакетах.', '4 × 6 + 3', 'Равные группы сначала умножаются.']),
    cq('07', '20 ga teng', '🟡', 'd14-equals-multi', 'multi', '✅', [0, 1, 3],
      ["Har bir ifodani amal tartibida hisoblang.", "20 ga teng ifodalarni belgilang.", ['4 × 5', '24 − 8 : 2', '6 + 6 × 2', '(7 − 3) × 5'], "Uchta ifoda 20 ga teng.", "Ko'paytirish va bo'lishni birinchi bajaring.", '= 20', "Qavs natijaga ta'sir qiladi."],
      ['Вычисли каждое выражение по порядку действий.', 'Отметь выражения, равные 20.', ['4 × 5', '24 − 8 : 2', '6 + 6 × 2', '(7 − 3) × 5'], 'Три выражения равны 20.', 'Сначала выполни умножение и деление.', '= 20', 'Скобки влияют на результат.']),
    cq('08', 'Ayirish tuzog‘i', '🔴', 'd14-trap', 'choice', '🪤', 1,
      ["18 − 6 : 3 da ayirish birinchi emas.", "Natijani tanlang.", ['4', '16', '12'], "6 : 3 = 2; 18 − 2 = 16.", "Bo'lishni ayirishdan oldin bajaring.", '18 − 6 : 3', "Amallarni shunchaki chapdan o'ngga bajarib bo'lmaydi."],
      ['В 18 − 6 : 3 вычитание не первое.', 'Выбери результат.', ['4', '16', '12'], '6 : 3 = 2; 18 − 2 = 16.', 'Выполни деление раньше вычитания.', '18 − 6 : 3', 'Нельзя всегда считать просто слева направо.']),
    cq('09', 'Xatoni toping', '🔴', 'd14-error', 'choice', '🔎', 0,
      ["Anvar 7 + 5 × 2 ni chapdan o'ngga bajarib, 24 oldi.", "Xato sababini tanlang.", ["Qo'shishni birinchi bajargan", "2 ga bo'lishi kerak edi", "Qavsni unutgan"], "Avval 5 × 2 bajarilishi kerak.", "Ko'paytirishning ustunligini eslang.", '7 + 5 × 2 = 24 ✗', "To'g'ri natija 17."],
      ['Анвар посчитал 7 + 5 × 2 слева направо и получил 24.', 'Выбери причину ошибки.', ['Первым выполнил сложение', 'Нужно было делить на 2', 'Забыл скобки'], 'Сначала нужно выполнить 5 × 2.', 'Вспомни приоритет умножения.', '7 + 5 × 2 = 24 ✗', 'Верный результат — 17.']),
    cq('10', 'Murakkab transfer', '🔴', 'd14-transfer', 'input', '🚀', ['24'],
      ["Ifodada qavs, bo'lish, qo'shish va ko'paytirish bor.", "(36 : 4 + 3) × 2 ni hisoblang.", undefined, "36 : 4 = 9; 9 + 3 = 12; 12 × 2 = 24.", "Qavs ichini chapdan o'ngga hisoblang.", '(36 : 4 + 3) × 2', "Qavs ichida ham amal tartibi saqlanadi."],
      ['В выражении есть скобки, деление, сложение и умножение.', 'Вычисли (36 : 4 + 3) × 2.', undefined, '36 : 4 = 9; 9 + 3 = 12; 12 × 2 = 24.', 'Вычисли содержимое скобок слева направо.', '(36 : 4 + 3) × 2', 'Внутри скобок порядок действий тоже сохраняется.']),
  ],
};

export const DARS14_BANK = {
  title: "Dars 14 · Komponentlar bog'lanishi",
  items: [
    cq('01', 'Komponent nomi', '🟢', 'd15-product-name', 'choice', '🏷️', 2,
      ["7 × 6 = 42 tengligida 7 va 6 ko'paytuvchilar.", "42 nima deb ataladi?", ["Bo'linma", "Yig'indi", "Ko'paytma"], "42 — ko'paytma.", "Ko'paytirish amalining natijasi nomini eslang.", '7 × 6 = 42', "Ko'paytuvchi × ko'paytuvchi = ko'paytma."],
      ['В равенстве 7 × 6 = 42 числа 7 и 6 — множители.', 'Как называется 42?', ['Частное', 'Сумма', 'Произведение'], '42 — произведение.', 'Вспомни название результата умножения.', '7 × 6 = 42', 'Множитель × множитель = произведение.']),
    cq('02', "Noma'lum ko'paytuvchi", '🟢', 'd15-factor', 'input', '🧩', ['7'],
      ["□ × 8 = 56.", "Noma'lum ko'paytuvchini toping.", undefined, "56 : 8 = 7.", "Ko'paytmani ma'lum ko'paytuvchiga bo'ling.", '□ × 8 = 56', "Noma'lum ko'paytuvchi bo'lish orqali topiladi."],
      ['□ × 8 = 56.', 'Найди неизвестный множитель.', undefined, '56 : 8 = 7.', 'Раздели произведение на известный множитель.', '□ × 8 = 56', 'Неизвестный множитель находят делением.']),
    cq('03', 'Tengliklar oilasi', '🟡', 'd15-family-order', 'order', '👨‍👩‍👧‍👦', [1, 3, 0, 2],
      ["5, 7 va 35 sonlari bitta tengliklar oilasini tuzadi.", "Avval ikki ko'paytma, keyin ikki bo'linmani joylang.", ['35 : 5 = 7', '5 × 7 = 35', '35 : 7 = 5', '7 × 5 = 35'], "To'rtta tenglik bir xil bog'lanishni ko'rsatadi.", "Ko'paytirish tengliklarini oldinga qo'ying.", '5 · 7 · 35', "Ko'paytuvchilar o'rin almashadi; bo'lish teskari amal."],
      ['Числа 5, 7 и 35 образуют семейство равенств.', 'Сначала поставь два произведения, затем два деления.', ['35 : 5 = 7', '5 × 7 = 35', '35 : 7 = 5', '7 × 5 = 35'], 'Четыре равенства показывают одну связь.', 'Поставь равенства с умножением первыми.', '5 · 7 · 35', 'Множители меняются местами; деление — обратное действие.']),
    cq('04', "Noma'lum bo'luvchi", '🟡', 'd15-divisor', 'choice', '🔐', 1,
      ["54 : □ = 6.", "Bo'luvchini toping.", ['6', '9', '48'], "54 : 9 = 6.", "6 ni qaysi songa ko'paytirsak 54 chiqadi?", '54 : □ = 6', "Bo'luvchi = bo'linuvchi : bo'linma."],
      ['54 : □ = 6.', 'Найди делитель.', ['6', '9', '48'], '54 : 9 = 6.', 'На какое число умножить 6, чтобы получить 54?', '54 : □ = 6', 'Делитель = делимое : частное.']),
    cq('05', "Noma'lum bo'linuvchi", '🟡', 'd15-dividend', 'input', '🔐', ['56'],
      ["□ : 7 = 8.", "Bo'linuvchini toping.", undefined, "8 × 7 = 56.", "Bo'linma bilan bo'luvchini ko'paytiring.", '□ : 7 = 8', "Bo'linuvchi = bo'luvchi × bo'linma."],
      ['□ : 7 = 8.', 'Найди делимое.', undefined, '8 × 7 = 56.', 'Умножь частное на делитель.', '□ : 7 = 8', 'Делимое = делитель × частное.']),
    cq('06', 'Guruhlar masalasi', '🟡', 'd15-story', 'choice', '📦', 0,
      ["6 ta guruhning har birida 9 tadan modul bor.", "Jami modullar va teskari tekshiruvni tanlang.", ['54; 54 : 6 = 9', '15; 15 − 6 = 9', '54; 54 : 9 = 6 emas'], "6 × 9 = 54 va 54 : 6 = 9.", "Ko'paytirish natijasini bo'lish bilan tekshiring.", '6 × 9 = ?', "Bitta oiladagi amallar bir-birini tekshiradi."],
      ['В 6 группах по 9 модулей.', 'Выбери общее число и обратную проверку.', ['54; 54 : 6 = 9', '15; 15 − 6 = 9', '54; 54 : 9 ≠ 6'], '6 × 9 = 54 и 54 : 6 = 9.', 'Проверь произведение делением.', '6 × 9 = ?', 'Действия одного семейства проверяют друг друга.']),
    cq('07', 'Oilani tanlang', '🟡', 'd15-family-multi', 'multi', '✅', [0, 1, 3],
      ["5, 8 va 40 sonlariga qarang.", "Shu oilaga kiradigan tengliklarni belgilang.", ['5 × 8 = 40', '8 × 5 = 40', '40 : 8 = 6', '40 : 5 = 8'], "Uchta tenglik bir oilaga tegishli.", "Faqat 5, 8 va 40 orasidagi to'g'ri bog'lanishlarni tanlang.", '5 · 8 · 40', "Oilada ikkita ko'paytirish va ikkita bo'lish tengligi bo'ladi."],
      ['Рассмотри числа 5, 8 и 40.', 'Отметь равенства этого семейства.', ['5 × 8 = 40', '8 × 5 = 40', '40 : 8 = 6', '40 : 5 = 8'], 'Три равенства входят в семейство.', 'Выбирай только верные связи между 5, 8 и 40.', '5 · 8 · 40', 'В семействе два умножения и два деления.']),
    cq('08', 'Nol tuzog‘i', '🔴', 'd15-zero', 'choice', '🕳️', 0,
      ["99 ta guruhning har birida 0 tadan obyekt.", "99 × 0 nechaga teng?", ['0', '99', '9'], "Hech bir guruhda obyekt yo'q, jami 0.", "Nolni necha marta qo'shsak ham nol.", '99 × 0', "Har qanday son × 0 = 0."],
      ['В каждой из 99 групп по 0 предметов.', 'Чему равно 99 × 0?', ['0', '99', '9'], 'Во всех группах нет предметов, всего 0.', 'Сколько ни складывай ноль, останется ноль.', '99 × 0', 'Любое число × 0 = 0.']),
    cq('09', 'Tekshiruvdagi xato', '🔴', 'd15-error', 'choice', '🔎', 2,
      ["Jasur 36 : 4 = 8 dedi va 8 × 4 = 32 bilan tekshirdi.", "Tekshiruv nimani ko'rsatadi?", ["Javob to'g'ri", "36 xato son", "Bo'linma 8 emas"], "8 × 4 36 emas; to'g'ri bo'linma 9.", "Tekshiruv natijasi bo'linuvchiga teng bo'lishi kerak.", '36 : 4 = 8 ✗', "9 × 4 = 36."],
      ['Жасур решил 36 : 4 = 8 и проверил: 8 × 4 = 32.', 'Что показывает проверка?', ['Ответ верный', 'Число 36 ошибочно', 'Частное не равно 8'], '8 × 4 не равно 36; верное частное — 9.', 'Результат проверки должен совпасть с делимым.', '36 : 4 = 8 ✗', '9 × 4 = 36.']),
    cq('10', 'Transfer', '🔴', 'd15-transfer', 'input', '🚀', ['12'],
      ["a × 6 = 72.", "a ning qiymatini kiriting.", undefined, "72 : 6 = 12.", "Noma'lum ko'paytuvchini bo'lish bilan toping.", 'a × 6 = 72', "12 × 6 = 72 bilan tekshiriladi."],
      ['a × 6 = 72.', 'Введи значение a.', undefined, '72 : 6 = 12.', 'Найди неизвестный множитель делением.', 'a × 6 = 72', 'Проверка: 12 × 6 = 72.']),
  ],
};

export const DARS15_BANK = {
  title: "Dars 15 · Ko'paytirish va bo'lishga masalalar",
  items: [
    cq('01', 'Amalni tanlang', '🟢', 'd16-operation', 'choice', '🧭', 1,
      ["5 ta savat bor. Har bir savatda 7 tadan olma bor.", "Barcha savatlardagi olmalar sonini topish uchun qaysi amalni tanlaysiz?", ['7 + 5', '5 × 7', '7 : 5'], "5 × 7 = 35. Beshta teng guruhning har birida 7 tadan olma bor.", "Nechta savat borligini va har birida nechta olma borligini aniqlang.", '5 ta savat · har birida 7 ta', "Teng guruhlardagi jami miqdor guruhlar sonini har bir guruhdagi miqdorga ko'paytirib topiladi."],
      ['Есть 5 корзин. В каждой корзине по 7 яблок.', 'Какое действие выберешь, чтобы найти число яблок во всех корзинах?', ['7 + 5', '5 × 7', '7 : 5'], '5 × 7 = 35. В каждой из пяти равных групп по 7 яблок.', 'Определи число корзин и число яблок в каждой.', '5 корзин · в каждой по 7', 'Общее количество в равных группах находят умножением числа групп на количество в каждой группе.']),
    cq('02', 'Jami qancha?', '🟢', 'd16-total', 'input', '📦', ['56'],
      ["7 ta quti bor. Har bir qutida 8 tadan chiroq bor.", "Barcha qutilarda jami nechta chiroq bor?", undefined, "7 × 8 = 56 ta chiroq.", "7 ta teng guruhning har birida 8 tadan chiroq bor. 7 ni 8 ga ko'paytiring.", '7 × 8 = ?', "Javob: 56 ta chiroq."],
      ['Есть 7 коробок. В каждой коробке по 8 ламп.', 'Сколько всего ламп во всех коробках?', undefined, '7 × 8 = 56 ламп.', 'Есть 7 равных групп по 8 ламп. Умножь 7 на 8.', '7 × 8 = ?', 'Ответ: 56 ламп.']),
    cq('03', 'Teng taqsimlash', '🟡', 'd16-share', 'choice', '⚖️', 2,
      ["63 ta detal 9 ta teng guruhga ajratildi.", "Har bir guruhda nechta detal borligini qaysi yozuv topadi?", ['63 × 9', '63 − 9', '63 : 9'], "63 : 9 = 7. Har bir guruhda 7 tadan detal bor.", "Jami 63 ta detalni 9 ta teng guruhga bo'ling.", '63 ta detal → 9 ta teng guruh', "Har bir teng guruhdagi miqdor jami miqdorni guruhlar soniga bo'lib topiladi."],
      ['63 детали разделили на 9 равных групп.', 'Какая запись поможет найти число деталей в каждой группе?', ['63 × 9', '63 − 9', '63 : 9'], '63 : 9 = 7. В каждой группе по 7 деталей.', 'Раздели все 63 детали на 9 равных групп.', '63 детали → 9 равных групп', 'Количество в каждой равной группе находят делением общего количества на число групп.']),
    cq('04', 'Masala qadamlari', '🟡', 'd16-steps', 'order', '🪜', [2, 0, 3, 1],
      ["Masalani to'g'ri yechish uchun to'rtta qadam bajariladi.", "Qadamlarni boshidan oxirigacha tartiblang.", ["Nima so'ralganini aniqlash", "Birlik bilan javob yozish", "Ma'lum sonlarni topish", "Amalni tanlash va hisoblash"], "Ma'lum sonlar → savol → amal va hisob → birlik bilan javob.", "Avval masalada berilgan sonlarni toping. So'ng nima so'ralganini aniqlang.", 'Ma’lum sonlar → Savol → Amal → Javob', "Amal bitta kalit so'zga emas, sonlar orasidagi bog'lanishga qarab tanlanadi."],
      ['Чтобы правильно решить задачу, нужно выполнить четыре шага.', 'Расположи шаги от первого до последнего.', ['Определить, что нужно найти', 'Записать ответ с единицей', 'Найти известные числа', 'Выбрать действие и вычислить'], 'Известные числа → вопрос → действие и вычисление → ответ с единицей.', 'Сначала найди данные в задаче. Затем определи, что нужно узнать.', 'Известные числа → Вопрос → Действие → Ответ', 'Действие выбирают по связи между числами, а не по одному ключевому слову.']),
    cq('05', "Noma'lum guruh", '🟡', 'd16-missing-group', 'input', '🧩', ['8'],
      ["48 nafar o'quvchi 6 ta teng jamoaga bo'lindi.", "Har bir jamoada necha nafardan o'quvchi bor?", undefined, "48 : 6 = 8. Har bir jamoada 8 nafardan o'quvchi bor.", "Barcha 48 nafar o'quvchini 6 ta teng jamoaga bo'ling.", '48 nafar → 6 ta teng jamoa', "Javob: har bir jamoada 8 nafar o'quvchi."],
      ['48 учеников разделили на 6 равных команд.', 'Сколько учеников в каждой команде?', undefined, '48 : 6 = 8. В каждой команде по 8 учеников.', 'Раздели всех 48 учеников на 6 равных команд.', '48 учеников → 6 равных команд', 'Ответ: в каждой команде 8 учеников.']),
    cq('06', 'Ikki qadamli masala', '🟡', 'd16-two-step', 'input', '🧺', ['52'],
      ["5 ta savatning har birida 9 tadan kristall bor. Stol ustida yana 7 ta kristall bor.", "Savatlar va stol ustidagi kristallar jami nechta?", undefined, "5 × 9 + 7 = 45 + 7 = 52 ta kristall.", "Avval beshta savatdagi kristallar sonini toping. Keyin stol ustidagi 7 tani qo'shing.", '5 × 9 + 7 = ?', "Ikki qadam: avval ko'paytirish, keyin qo'shish."],
      ['В каждой из 5 корзин по 9 кристаллов. На столе лежат ещё 7 кристаллов.', 'Сколько всего кристаллов в корзинах и на столе?', undefined, '5 × 9 + 7 = 45 + 7 = 52 кристалла.', 'Сначала найди число кристаллов в пяти корзинах. Затем прибавь ещё 7.', '5 × 9 + 7 = ?', 'Два шага: сначала умножение, затем сложение.']),
    cq('07', "Bo'lish vaziyatlari", '🟡', 'd16-division-multi', 'multi', '✅', [0, 2],
      ["Har bir vaziyatda jami miqdor bilan nima qilinayotganiga qarang.", "Bo'lish amali kerak bo'lgan barcha vaziyatlarni belgilang.", ["40 ta gulni 5 ta guldonga teng joylash", "6 ta qutining har birida 7 tadan qalam", "54 km yo'lni 6 kunda teng masofadan yurish", "8 ta kitobga yana 4 ta kitob qo'shish"], "Birinchi va uchinchi vaziyatda jami miqdor teng qismlarga bo'linmoqda.", "Jami miqdor bir nechta teng qismga ajratilgan vaziyatlarni toping.", 'Jami miqdor → teng qismlar', "Bo'lish jami miqdorni teng qismlarga ajratishda yoki teng guruhlar sonini topishda ishlatiladi."],
      ['Посмотри, что происходит с общим количеством в каждой ситуации.', 'Отметь все ситуации, в которых нужно деление.', ['40 цветов поровну поставить в 5 ваз', 'В каждой из 6 коробок по 7 карандашей', '54 км пройти за 6 дней равными расстояниями', 'К 8 книгам добавить ещё 4'], 'В первой и третьей ситуациях общее количество делят на равные части.', 'Найди ситуации, где общее количество делят на несколько равных частей.', 'Общее количество → равные части', 'Деление используют, когда общее количество делят на равные части или находят число равных групп.']),
    cq('08', 'Nol holati', '🔴', 'd16-zero', 'choice', '🕳️', 0,
      ["5 ta rafga teng taqsimlash uchun birorta ham detal yo'q.", "Har bir rafga nechta detal qo'yiladi?", ['0', '5', 'Aniqlab bo‘lmaydi'], "0 : 5 = 0. Har bir raf bo'sh qoladi.", "Taqsimlanadigan detal yo'q, shuning uchun barcha raflar bo'sh qoladi.", '0 ta detal : 5 ta raf', "Nolni noldan farqli songa bo'lganda natija nol bo'ladi."],
      ['Нет ни одной детали, которую нужно поровну разложить на 5 полок.', 'Сколько деталей окажется на каждой полке?', ['0', '5', 'Нельзя определить'], '0 : 5 = 0. Каждая полка останется пустой.', 'Распределять нечего, поэтому все полки останутся пустыми.', '0 деталей : 5 полок', 'При делении нуля на ненулевое число получается ноль.']),
    cq('09', 'Xato amal', '🔴', 'd16-error', 'choice', '🔎', 1,
      ["4 ta qutining har birida 6 tadan detal bor. Jasur jami miqdorni 4 + 6 = 10 deb topdi.", "Jasur nimani hisobga olmadi?", ["Sonlar juda kichikligini", "6 ta detal 4 marta takrorlanishini", "Ayirish amalini ishlatish kerakligini"], "6 ta detal 4 marta takrorlanadi: 4 × 6 = 24.", "To'rtta qutining har birida bir xil 6 tadan detal borligini kuzating.", '6 + 6 + 6 + 6 = 24', "Teng 6 talik guruh to'rt marta takrorlangan, shuning uchun 4 × 6 ishlatiladi."],
      ['В каждой из 4 коробок по 6 деталей. Жасур нашёл общее количество так: 4 + 6 = 10.', 'Что не учёл Жасур?', ['Что числа слишком малы', 'Что 6 деталей повторяются 4 раза', 'Что нужно использовать вычитание'], '6 деталей повторяются 4 раза: 4 × 6 = 24.', 'Заметь, что в каждой из четырёх коробок одинаково по 6 деталей.', '6 + 6 + 6 + 6 = 24', 'Равная группа из 6 деталей повторяется четыре раза, поэтому используем 4 × 6.']),
    cq('10', 'Transfer masalasi', '🔴', 'd16-transfer', 'input', '🚀', ['32'],
      ["96 betli kitob 3 kunda o'qib tugatildi. Har kuni bir xil miqdorda bet o'qildi.", "Har kuni necha betdan o'qilgan?", undefined, "96 : 3 = 32. Har kuni 32 betdan o'qilgan.", "Kitobdagi jami 96 betni 3 kunga teng taqsimlang.", '96 bet → 3 ta teng kun', "Javob: har kuni 32 bet."],
      ['Книгу из 96 страниц прочитали за 3 дня. Каждый день читали одинаковое число страниц.', 'Сколько страниц читали каждый день?', undefined, '96 : 3 = 32. Каждый день читали по 32 страницы.', 'Раздели все 96 страниц поровну на 3 дня.', '96 страниц → 3 равных дня', 'Ответ: по 32 страницы каждый день.']),
  ],
};

export const DARS16_BANK = {
  title: "Dars 16 · Bo'luvchilar va karrali sonlar",
  items: [
    cq('01', "Bo'luvchini tanlang", '🟢', 'd17-divisor', 'choice', '🔑', 1,
      ["Bo'luvchi sonni qoldiqsiz bo'ladi.", "Qaysi son 18 ning bo'luvchisi?", ['4', '6', '7'], "18 : 6 = 3, qoldiq yo'q.", "Har variantga 18 ni bo'lib ko'ring.", '18 : ? = butun son', "6 — 18 ning bo'luvchisi."],
      ['Делитель делит число без остатка.', 'Какое число является делителем 18?', ['4', '6', '7'], '18 : 6 = 3 без остатка.', 'Попробуй разделить 18 на каждый вариант.', '18 : ? = целое число', '6 — делитель 18.']),
    cq('02', "12 ning bo'luvchilari", '🟢', 'd17-all-divisors', 'multi', '✅', [0, 1, 2, 3, 5, 6],
      ["12 ni qoldiqsiz bo'ladigan sonlarni toping.", "Barcha bo'luvchilarni belgilang.", ['1', '2', '3', '4', '5', '6', '12'], "1, 2, 3, 4, 6 va 12 qoldiqsiz bo'ladi.", "Ko'paytuvchilar juftlarini eslang: 1×12, 2×6, 3×4.", '12', "Bo'luvchilar juft bo'lib topiladi."],
      ['Найди числа, на которые 12 делится без остатка.', 'Отметь все делители.', ['1', '2', '3', '4', '5', '6', '12'], '1, 2, 3, 4, 6 и 12 делят без остатка.', 'Вспомни пары множителей: 1×12, 2×6, 3×4.', '12', 'Делители удобно находить парами.']),
    cq('03', 'Keyingi karrali', '🟡', 'd17-next-multiple', 'input', '➡️', ['42'],
      ["7 ning karralilari: 7, 14, 21, 28, 35, ...", "Keyingi sonni kiriting.", undefined, "35 + 7 = 42.", "Karralilar qatoriga yana 7 qo'shing.", '7, 14, 21, 28, 35, ?', "Karralilar qatori cheksiz davom etadi."],
      ['Кратные 7: 7, 14, 21, 28, 35, ...', 'Введи следующее число.', undefined, '35 + 7 = 42.', 'Прибавь ещё 7.', '7, 14, 21, 28, 35, ?', 'Ряд кратных продолжается бесконечно.']),
    cq('04', 'Karralilar tartibi', '🟡', 'd17-order', 'order', '🪜', [1, 3, 0, 2],
      ["6 ning dastlabki to'rtta musbat karralisini tuzing.", "Sonlarni tartiblang.", ['18', '6', '24', '12'], "6, 12, 18, 24.", "6 dan boshlang va har safar 6 qo'shing.", '6 × 1, 6 × 2, ...', "n-karrali son 6 × n ko'rinishida."],
      ['Составь первые четыре положительных кратных 6.', 'Расположи числа по порядку.', ['18', '6', '24', '12'], '6, 12, 18, 24.', 'Начни с 6 и каждый раз прибавляй 6.', '6 × 1, 6 × 2, ...', 'Кратные имеют вид 6 × n.']),
    cq('05', 'Nega karrali?', '🟡', 'd17-why-multiple', 'choice', '💬', 2,
      ["24 sonini 8 ga bo'lib tekshiramiz.", "Nega 24 soni 8 ning karralisi?", ["24 katta bo'lgani uchun", "24 juft bo'lgani uchun", "8 × 3 = 24 bo'lgani uchun"], "24 soni 8 ning butun marta olingan ko'paytmasi.", "8 ni nechaga ko'paytirib 24 olish mumkin?", '8 × 3 = 24', "a × n = b bo'lsa, b — a ning karralisi."],
      ['Проверим число 24 делением на 8.', 'Почему 24 кратно 8?', ['Потому что 24 большое', 'Потому что 24 чётное', 'Потому что 8 × 3 = 24'], '24 — произведение 8 на целое число.', 'На что умножить 8, чтобы получить 24?', '8 × 3 = 24', 'Если a × n = b, то b кратно a.']),
    cq('06', 'Teng qatorlar', '🟡', 'd17-story', 'multi', '📐', [0, 1, 3],
      ["30 ta kristallni teng qatorlarga qoldiqsiz joylash kerak.", "Qatorlar soni bo'la oladiganlarni belgilang.", ['3', '5', '7', '6'], "30 soni 3, 5 va 6 ga qoldiqsiz bo'linadi.", "30 ning bo'luvchilarini tanlang.", '30 kristall', "Qatorlar soni 30 ning bo'luvchisi bo'lishi kerak."],
      ['30 кристаллов нужно разложить в равные ряды без остатка.', 'Отметь возможное число рядов.', ['3', '5', '7', '6'], '30 делится без остатка на 3, 5 и 6.', 'Выбери делители 30.', '30 кристаллов', 'Число рядов должно быть делителем 30.']),
    cq('07', 'Umumiy karrali', '🟡', 'd17-common-multiple', 'multi', '🔗', [1, 3],
      ["3 va 4 ning 30 dan kichik umumiy karralilarini izlaymiz.", "Mos sonlarni belgilang.", ['8', '12', '18', '24'], "12 va 24 ikkala qatorga ham kiradi.", "Son 3 ga ham, 4 ga ham qoldiqsiz bo'linishi kerak.", '3: 3,6,9...  4: 4,8,12...', "Umumiy karrali ikkala sonning karralisi."],
      ['Ищем общие кратные 3 и 4 меньше 30.', 'Отметь подходящие числа.', ['8', '12', '18', '24'], '12 и 24 входят в оба ряда.', 'Число должно делиться и на 3, и на 4.', '3: 3,6,9...  4: 4,8,12...', 'Общее кратное кратно обоим числам.']),
    cq('08', 'Bir soni', '🔴', 'd17-one-trap', 'choice', '1️⃣', 0,
      ["Har bir natural son 1 ga qoldiqsiz bo'linadi.", "1 soni 37 ning bo'luvchisimi?", ["Ha, 37 : 1 = 37", "Yo'q, 1 juda kichik", "Faqat juft sonlarda"], "1 har bir natural sonning bo'luvchisi.", "37 ni 1 ga bo'lib ko'ring.", '37 : 1 = 37', "1 va sonning o'zi doim bo'luvchi."],
      ['Каждое натуральное число делится на 1 без остатка.', 'Является ли 1 делителем 37?', ['Да, 37 : 1 = 37', 'Нет, 1 слишком мало', 'Только у чётных чисел'], '1 — делитель любого натурального числа.', 'Раздели 37 на 1.', '37 : 1 = 37', '1 и само число всегда являются делителями.']),
    cq('09', 'Xatoni toping', '🔴', 'd17-error', 'choice', '🔎', 1,
      ["Zuhra 16 ning bo'luvchilari ichiga 3 ni ham yozdi.", "Nega 3 bo'luvchi emas?", ["3 toq son", "16 : 3 qoldiqli", "3 soni 16 dan kichik"], "16 soni 3 ga qoldiqsiz bo'linmaydi.", "Bo'luvchi uchun kattalik emas, qoldiq muhim.", '16 : 3 = 5 (qoldiq 1)', "Qoldiq bo'lsa, son bo'luvchi emas."],
      ['Зухра записала 3 среди делителей 16.', 'Почему 3 не является делителем?', ['3 нечётное', '16 : 3 имеет остаток', '3 меньше 16'], '16 не делится на 3 без остатка.', 'Для делителя важен остаток, а не размер.', '16 : 3 = 5 (ост. 1)', 'Если есть остаток, число не делитель.']),
    cq('10', 'Eng kichik umumiy', '🔴', 'd17-transfer', 'input', '🚀', ['12'],
      ["4 va 6 ning musbat karralilarini solishtiring.", "Eng kichik umumiy karralini kiriting.", undefined, "4: 4, 8, 12; 6: 6, 12. Birinchi umumiy son 12.", "Ikki karralilar qatorini yonma-yon yozing.", '4 → 4,8,12   6 → 6,12', "12 — 4 va 6 ning eng kichik umumiy karralisi."],
      ['Сравни положительные кратные 4 и 6.', 'Введи наименьшее общее кратное.', undefined, '4: 4, 8, 12; 6: 6, 12. Первое общее число — 12.', 'Запиши рядом два ряда кратных.', '4 → 4,8,12   6 → 6,12', '12 — наименьшее общее кратное 4 и 6.']),
  ],
};

export const DARS17_BANK = {
  title: "Dars 17 · Ikki xonali sonni ko'paytirish",
  items: [
    cq('01', 'Yoyilmani tanlang', '🟢', 'd19-split', 'choice', '🧱', 0,
      ["23 × 4 da 23 ni o'nlik va birlikka ajratamiz.", "To'g'ri yozuvni tanlang.", ['20 × 4 + 3 × 4', '20 × 3 + 4', '23 + 4'], "20 ham, 3 ham 4 ga ko'payadi.", "23 = 20 + 3 ekanini ishlating.", '23 × 4', "(20 + 3) × 4 = 20 × 4 + 3 × 4."],
      ['В 23 × 4 раскладываем 23 на десятки и единицы.', 'Выбери верную запись.', ['20 × 4 + 3 × 4', '20 × 3 + 4', '23 + 4'], 'И 20, и 3 умножаются на 4.', 'Используй 23 = 20 + 3.', '23 × 4', '(20 + 3) × 4 = 20 × 4 + 3 × 4.']),
    cq('02', 'Hisoblang', '🟢', 'd19-calculate', 'input', '🧮', ['93'],
      ["31 × 3 = 30 × 3 + 1 × 3.", "Natijani kiriting.", undefined, "90 + 3 = 93.", "O'nlik va birlik ko'paytmalarini qo'shing.", '31 × 3 = ?', "Har ikki razryad alohida ko'payadi."],
      ['31 × 3 = 30 × 3 + 1 × 3.', 'Введи результат.', undefined, '90 + 3 = 93.', 'Сложи произведения десятков и единиц.', '31 × 3 = ?', 'Оба разряда умножаются отдельно.']),
    cq('03', 'Algoritm qadamlari', '🟡', 'd19-steps', 'order', '🪜', [2, 0, 3, 1],
      ["42 × 2 ni razryadlar orqali hisoblaymiz.", "Qadamlarni tartiblang.", ['40 × 2 = 80', '80 + 4 = 84', '42 = 40 + 2', '2 × 2 = 4'], "Yoyish → o'nlik → birlik → qo'shish.", "Avval 42 ni razryadlarga ajrating.", '42 × 2', "Razryad natijalari oxirida qo'shiladi."],
      ['Вычислим 42 × 2 по разрядам.', 'Расположи шаги.', ['40 × 2 = 80', '80 + 4 = 84', '42 = 40 + 2', '2 × 2 = 4'], 'Разложить → десятки → единицы → сложить.', 'Сначала разложи 42 по разрядам.', '42 × 2', 'Результаты по разрядам складываются в конце.']),
    cq('04', 'Ikki baravar', '🟡', 'd19-double', 'choice', '✌️', 2,
      ["46 ni ikki marta olish 46 × 2.", "Natijani toping.", ['82', '88', '92'], "40 × 2 + 6 × 2 = 80 + 12 = 92.", "Birliklar ko'paytmasi 12 ekanini unutmang.", '46 × 2', "Birliklardan yangi o'nlik hosil bo'lishi mumkin."],
      ['Взять 46 два раза — это 46 × 2.', 'Найди результат.', ['82', '88', '92'], '40 × 2 + 6 × 2 = 80 + 12 = 92.', 'Не забудь, что 6 × 2 = 12.', '46 × 2', 'Из единиц может получиться новый десяток.']),
    cq('05', "Noma'lum son", '🟡', 'd19-missing', 'input', '🧩', ['23'],
      ["□ × 3 = 69.", "Ikki xonali noma'lum sonni toping.", undefined, "69 : 3 = 23.", "Ko'paytirishga teskari amalni bajaring.", '□ × 3 = 69', "23 × 3 = 69 bilan tekshiriladi."],
      ['□ × 3 = 69.', 'Найди неизвестное двузначное число.', undefined, '69 : 3 = 23.', 'Выполни обратное умножению действие.', '□ × 3 = 69', 'Проверка: 23 × 3 = 69.']),
    cq('06', 'Ustaxona masalasi', '🟡', 'd19-story', 'input', '🔩', ['90'],
      ["5 ta ramkaning har biriga 18 tadan bolt kerak.", "Jami boltlar sonini toping.", undefined, "10 × 5 + 8 × 5 = 50 + 40 = 90.", "18 ni 10 va 8 ga ajrating.", '18 × 5 = ?', "Javob: 90 ta bolt."],
      ['Для каждой из 5 рам нужно по 18 болтов.', 'Найди общее число болтов.', undefined, '10 × 5 + 8 × 5 = 50 + 40 = 90.', 'Разложи 18 на 10 и 8.', '18 × 5 = ?', 'Ответ: 90 болтов.']),
    cq('07', 'Teng yozuvlar', '🟡', 'd19-equivalents', 'multi', '✅', [0, 1, 3],
      ["27 × 4 qiymati 108.", "Teng yozuvlarni belgilang.", ['20 × 4 + 7 × 4', '108', '27 + 4', '54 × 2'], "Uchala variant 108 ni ifodalaydi.", "Har bir variant qiymatini toping.", '27 × 4 = 108', "Bitta son turli qulay yozuvlarda ifodalanadi."],
      ['Значение 27 × 4 равно 108.', 'Отметь равные записи.', ['20 × 4 + 7 × 4', '108', '27 + 4', '54 × 2'], 'Три варианта выражают 108.', 'Найди значение каждого варианта.', '27 × 4 = 108', 'Одно число можно записать разными удобными способами.']),
    cq('08', 'Nol birlik', '🔴', 'd19-zero', 'choice', '0️⃣', 1,
      ["40 sonida birliklar nol.", "40 × 6 nechaga teng?", ['24', '240', '2 400'], "4 o'nlik × 6 = 24 o'nlik = 240.", "40 ni 4 o'nlik deb o'qing.", '40 × 6', "Nol birlik o'rnini saqlaydi."],
      ['В числе 40 ноль единиц.', 'Чему равно 40 × 6?', ['24', '240', '2 400'], '4 десятка × 6 = 24 десятка = 240.', 'Прочитай 40 как 4 десятка.', '40 × 6', 'Ноль сохраняет место единиц.']),
    cq('09', 'Xatoni tuzating', '🔴', 'd19-error', 'choice', '🔎', 2,
      ["Anvar: «34 × 3 = 30 × 3 + 4 = 94».", "Xato qaysi?", ["30 ni ko'paytirgan", "34 ni noto'g'ri yoygan", "4 ni 3 ga ko'paytirmagan"], "Birliklar qismi ham 3 ga ko'payishi kerak.", "Ikkala qo'shiluvchiga bir xil ko'paytuvchi ta'sir qiladi.", '30 × 3 + 4 = 94 ✗', "34 × 3 = 90 + 12 = 102."],
      ['Анвар: «34 × 3 = 30 × 3 + 4 = 94».', 'Где ошибка?', ['Умножил 30', 'Неверно разложил 34', 'Не умножил 4 на 3'], 'Часть с единицами тоже умножается на 3.', 'Один множитель действует на обе части.', '30 × 3 + 4 = 94 ✗', '34 × 3 = 90 + 12 = 102.']),
    cq('10', 'Transfer', '🔴', 'd19-transfer', 'input', '🚀', ['240'],
      ["48 × 5 ni qulay usulda hisoblang.", "Natijani kiriting.", undefined, "40 × 5 + 8 × 5 = 200 + 40 = 240.", "48 ni 40 va 8 ga ajrating.", '48 × 5 = ?', "Taxmin: 50 × 5 = 250, 240 mantiqli."],
      ['Вычисли 48 × 5 удобным способом.', 'Введи результат.', undefined, '40 × 5 + 8 × 5 = 200 + 40 = 240.', 'Разложи 48 на 40 и 8.', '48 × 5 = ?', 'Оценка: 50 × 5 = 250, поэтому 240 логично.']),
  ],
};

export const DARS18_BANK = {
  title: "Dars 18 · Ikki xonali sonni bo'lish",
  items: [
    cq('01', 'Qulay yoyilma', '🟢', 'd20-split', 'choice', '✂️', 0,
      ["96 : 4 uchun ikkala qism 4 ga bo'linishi kerak.", "Qulay yoyilmani tanlang.", ['(80 + 16) : 4', '(90 + 6) : 4', '(70 + 26) : 4'], "80 va 16 qoldiqsiz bo'linadi.", "Har bir qismni 4 ga bo'lib ko'ring.", '96 : 4', "Qismlar qulay bo'linishi shart."],
      ['Для 96 : 4 обе части должны делиться на 4.', 'Выбери удобное разложение.', ['(80 + 16) : 4', '(90 + 6) : 4', '(70 + 26) : 4'], '80 и 16 делятся без остатка.', 'Попробуй разделить каждую часть на 4.', '96 : 4', 'Части должны делиться удобно.']),
    cq('02', 'Hisoblang', '🟢', 'd20-calculate', 'input', '🧮', ['21'],
      ["84 : 4 = 80 : 4 + 4 : 4.", "Natijani kiriting.", undefined, "20 + 1 = 21.", "Qismlarni alohida bo'ling.", '84 : 4 = ?', "Tekshiruv: 21 × 4 = 84."],
      ['84 : 4 = 80 : 4 + 4 : 4.', 'Введи результат.', undefined, '20 + 1 = 21.', 'Раздели части отдельно.', '84 : 4 = ?', 'Проверка: 21 × 4 = 84.']),
    cq('03', 'Algoritm qadamlari', '🟡', 'd20-steps', 'order', '🪜', [2, 0, 3, 1],
      ["92 : 4 ni qulay bo'laklarda yechamiz.", "Qadamlarni tartiblang.", ['80 : 4 = 20; 12 : 4 = 3', '23 × 4 = 92', '92 = 80 + 12', '20 + 3 = 23'], "Yoyish → bo'lish → qo'shish → tekshirish.", "Avval bo'linadigan qismlarni toping.", '92 : 4', "Ko'paytirish oxirgi tekshiruv."],
      ['Решим 92 : 4 удобными частями.', 'Расположи шаги.', ['80 : 4 = 20; 12 : 4 = 3', '23 × 4 = 92', '92 = 80 + 12', '20 + 3 = 23'], 'Разложить → разделить → сложить → проверить.', 'Сначала найди делящиеся части.', '92 : 4', 'Умножение — последняя проверка.']),
    cq('04', 'Uchga bo‘lish', '🟡', 'd20-divide-three', 'choice', '3️⃣', 2,
      ["78 : 3 = 60 : 3 + 18 : 3.", "Natijani tanlang.", ['23', '24', '26'], "20 + 6 = 26.", "60 va 18 ni alohida 3 ga bo'ling.", '78 : 3', "Qulay qismlar bir xil bo'luvchiga bo'linadi."],
      ['78 : 3 = 60 : 3 + 18 : 3.', 'Выбери результат.', ['23', '24', '26'], '20 + 6 = 26.', 'Отдельно раздели 60 и 18 на 3.', '78 : 3', 'Удобные части делятся на один делитель.']),
    cq('05', "Yo'qolgan qism", '🟡', 'd20-missing', 'input', '🧩', ['24'],
      ["(60 + □) : 3 = 28.", "□ ni toping.", undefined, "28 × 3 = 84; 84 − 60 = 24.", "Avval teskari amal bilan bo'linuvchini toping.", '(60 + □) : 3 = 28', "24 ham 3 ga qoldiqsiz bo'linadi."],
      ['(60 + □) : 3 = 28.', 'Найди □.', undefined, '28 × 3 = 84; 84 − 60 = 24.', 'Сначала найди делимое обратным действием.', '(60 + □) : 3 = 28', '24 тоже делится на 3 без остатка.']),
    cq('06', 'Detallar masalasi', '🟡', 'd20-story', 'input', '📦', ['23'],
      ["92 ta detal 4 ta qutiga teng joylandi.", "Har qutida nechta detal?", undefined, "92 : 4 = 80 : 4 + 12 : 4 = 23.", "92 ni 80 va 12 ga ajrating.", '92 detal : 4 quti', "Javob: 23 ta detal."],
      ['92 детали поровну разложили в 4 коробки.', 'Сколько деталей в каждой коробке?', undefined, '92 : 4 = 80 : 4 + 12 : 4 = 23.', 'Разложи 92 на 80 и 12.', '92 детали : 4 коробки', 'Ответ: 23 детали.']),
    cq('07', 'Yaroqli yoyilmalar', '🟡', 'd20-splits', 'multi', '✅', [0, 1, 3],
      ["88 : 4 uchun qismlarning har biri 4 ga bo'linsin.", "Yaroqli yoyilmalarni belgilang.", ['80 + 8', '40 + 48', '70 + 18', '60 + 28'], "Uchta yoyilma shartga mos.", "Har bir juftlikdagi ikkala sonni tekshiring.", '88 : 4', "Yig'indi 88, qismlar 4 ga bo'linishi kerak."],
      ['Для 88 : 4 каждая часть должна делиться на 4.', 'Отметь подходящие разложения.', ['80 + 8', '40 + 48', '70 + 18', '60 + 28'], 'Три разложения подходят.', 'Проверь оба числа в каждой паре.', '88 : 4', 'Сумма равна 88, части делятся на 4.']),
    cq('08', 'Nol bilan son', '🔴', 'd20-zero', 'choice', '0️⃣', 1,
      ["90 : 5 ni 50 + 40 ga yoyish qulay.", "Natijani toping.", ['16', '18', '20'], "50 : 5 + 40 : 5 = 10 + 8 = 18.", "90 ni bo'linadigan o'nliklarga ajrating.", '90 : 5', "Bo'linma × 5 = 90 bo'lishi kerak."],
      ['90 : 5 удобно разложить как 50 + 40.', 'Найди результат.', ['16', '18', '20'], '50 : 5 + 40 : 5 = 10 + 8 = 18.', 'Разложи 90 на делящиеся десятки.', '90 : 5', 'Частное × 5 должно равняться 90.']),
    cq('09', 'Xatoni toping', '🔴', 'd20-error', 'choice', '🔎', 2,
      ["Ra'no: «84 : 4 = 80 : 4 + 4 = 24».", "Xato qaysi?", ["80 ni bo'lgan", "84 ni 80 + 4 ga yoygan", "4 ni 4 ga bo'lmagan"], "Ikkala qism ham bo'luvchiga bo'linadi.", "Ikkinchi 4 oldidagi amalni tekshiring.", '80 : 4 + 4 = 24 ✗', "84 : 4 = 20 + 1 = 21."],
      ['Рано: «84 : 4 = 80 : 4 + 4 = 24».', 'Где ошибка?', ['Разделила 80', 'Разложила 84 на 80 + 4', 'Не разделила 4 на 4'], 'Обе части делятся на делитель.', 'Проверь действие перед второй четвёркой.', '80 : 4 + 4 = 24 ✗', '84 : 4 = 20 + 1 = 21.']),
    cq('10', 'Transfer va tekshiruv', '🔴', 'd20-transfer', 'input', '🚀', ['24'],
      ["96 ta modul 4 ta teng rafga bo'lindi.", "Har rafdagi sonni kiriting.", undefined, "96 : 4 = 24; 24 × 4 = 96.", "80 + 16 yoyilmasidan foydalaning.", '96 : 4 = ?', "Natija taxminan 100 : 4 = 25 ga yaqin."],
      ['96 модулей разделили поровну на 4 полки.', 'Введи число модулей на полке.', undefined, '96 : 4 = 24; 24 × 4 = 96.', 'Используй разложение 80 + 16.', '96 : 4 = ?', 'Результат близок к оценке 100 : 4 = 25.']),
  ],
};

export const DARS19_BANK = {
  title: "Dars 19 · Qoldiqli bo'lish",
  items: [
    cq('01', 'Qoldiqni toping', '🟢', 'd21-remainder', 'choice', '📦', 1,
      ["17 ta detal 5 tadan guruhlanadi.", "Qoldiq nechta?", ['1', '2', '3'], "5 × 3 = 15, 17 − 15 = 2.", "17 dan oshmaydigan 5 karralisini toping.", '17 : 5', "17 : 5 = 3, qoldiq 2."],
      ['17 деталей группируют по 5.', 'Каков остаток?', ['1', '2', '3'], '5 × 3 = 15, 17 − 15 = 2.', 'Найди кратное 5, не превышающее 17.', '17 : 5', '17 : 5 = 3, остаток 2.']),
    cq('02', "Bo'linma", '🟢', 'd21-quotient', 'input', '🧮', ['4'],
      ["23 : 5 = 4, qoldiq 3.", "Bo'linmani kiriting.", undefined, "Bo'linma 4.", "5 tadan nechta to'liq guruh bor?", '23 = 5 × 4 + 3', "Bo'linma to'liq guruhlar soni."],
      ['23 : 5 = 4, остаток 3.', 'Введи частное.', undefined, 'Частное равно 4.', 'Сколько полных групп по 5?', '23 = 5 × 4 + 3', 'Частное — число полных групп.']),
    cq('03', 'Yozuvni tanlang', '🟡', 'd21-record', 'choice', '✍️', 0,
      ["26 ni 6 ga bo'lamiz.", "To'g'ri yozuv qaysi?", ['26 : 6 = 4 (qoldiq 2)', '26 : 6 = 3 (qoldiq 8)', '26 : 6 = 5 (qoldiq 4)'], "6 × 4 + 2 = 26.", "26 dan oshmaydigan 6 karralisini toping.", '26 : 6', "Qoldiq bo'luvchidan kichik."],
      ['Делим 26 на 6.', 'Какая запись верна?', ['26 : 6 = 4 (остаток 2)', '26 : 6 = 3 (остаток 8)', '26 : 6 = 5 (остаток 4)'], '6 × 4 + 2 = 26.', 'Найди кратное 6, не превышающее 26.', '26 : 6', 'Остаток меньше делителя.']),
    cq('04', 'Tekshiruv', '🟡', 'd21-check', 'order', '🪜', [1, 2, 0],
      ["31 : 7 ni tekshiramiz.", "Qadamlarni tartiblang.", ['31 − 28 = 3', '7 × 4 = 28', '28 < 31 < 35'], "Avval ko'paytma, keyin chegara va farq.", "7 ning 31 ga yaqin karralisidan boshlang.", '31 : 7', "31 : 7 = 4, qoldiq 3."],
      ['Проверим 31 : 7.', 'Расположи шаги.', ['31 − 28 = 3', '7 × 4 = 28', '28 < 31 < 35'], 'Сначала произведение, затем граница и разность.', 'Начни с кратного 7, близкого к 31.', '31 : 7', '31 : 7 = 4, остаток 3.']),
    cq('05', "Bo'linuvchini tiklang", '🟡', 'd21-inverse', 'input', '🧩', ['38'],
      ["Bo'luvchi 6, bo'linma 6, qoldiq 2.", "Bo'linuvchini toping.", undefined, "6 × 6 + 2 = 38.", "Ko'paytmaga qoldiqni qo'shing.", '□ = 6 × 6 + 2', "Bo'linuvchi = bo'luvchi × bo'linma + qoldiq."],
      ['Делитель 6, частное 6, остаток 2.', 'Найди делимое.', undefined, '6 × 6 + 2 = 38.', 'Прибавь остаток к произведению.', '□ = 6 × 6 + 2', 'Делимое = делитель × частное + остаток.']),
    cq('06', 'Ustaxona masalasi', '🟡', 'd21-story', 'choice', '🔩', 2,
      ["34 ta murvat 8 tadan ramkalarga sarflanadi.", "Nechta to'liq ramka va nechta qoldiq?", ['3 va 10', '5 va 2', '4 va 2'], "8 × 4 + 2 = 34.", "34 dan oshmaydigan 8 karralisini toping.", '34 : 8', "4 ta ramka, 2 ta murvat qoldiq."],
      ['34 болта расходуют по 8 на раму.', 'Сколько полных рам и каков остаток?', ['3 и 10', '5 и 2', '4 и 2'], '8 × 4 + 2 = 34.', 'Найди кратное 8, не превышающее 34.', '34 : 8', '4 рамы, остаток 2 болта.']),
    cq('07', "Mumkin qoldiqlar", '🟡', 'd21-valid', 'multi', '✅', [0, 1, 2],
      ["Son 4 ga bo'linmoqda.", "Mumkin qoldiqlarni belgilang.", ['0', '1', '3', '4'], "0, 1 va 3 sonlari 4 dan kichik.", "Qoldiq 0 dan 3 gacha bo'lishi mumkin.", ': 4', "Qoldiq bo'luvchidan kichik."],
      ['Число делят на 4.', 'Отметь возможные остатки.', ['0', '1', '3', '4'], '0, 1 и 3 меньше 4.', 'Остаток может быть от 0 до 3.', ': 4', 'Остаток меньше делителя.']),
    cq('08', 'Chegara holati', '🔴', 'd21-zero', 'choice', '0️⃣', 0,
      ["42 soni 7 ga qoldiqsiz bo'linadi.", "Qoldiq nechaga teng?", ['0', '6', '7'], "7 × 6 = 42, ortiqcha birlik yo'q.", "Barcha birliklar guruhlarga kirdi.", '42 : 7', "Qoldiq nol ham bo'lishi mumkin."],
      ['42 делится на 7 без остатка.', 'Каков остаток?', ['0', '6', '7'], '7 × 6 = 42, лишних единиц нет.', 'Все единицы вошли в группы.', '42 : 7', 'Остаток может быть равен нулю.']),
    cq('09', 'Xatoni toping', '🔴', 'd21-error', 'choice', '🔎', 1,
      ["Zuhra: «29 : 6 = 4, qoldiq 5». Jasur: «29 : 6 = 3, qoldiq 11».", "Qaysi fikr to'g'ri?", ['Jasurniki', 'Zuhraniki', 'Ikkalasi ham'], "6 × 4 + 5 = 29 va 5 < 6.", "Qoldiq bo'luvchidan kichikligini tekshiring.", '29 : 6', "Katta qoldiqdan yana to'liq guruh tuzish mumkin."],
      ['Зухра: «29 : 6 = 4, остаток 5». Жасур: «29 : 6 = 3, остаток 11».', 'Кто прав?', ['Жасур', 'Зухра', 'Оба'], '6 × 4 + 5 = 29 и 5 < 6.', 'Проверь, что остаток меньше делителя.', '29 : 6', 'Из большого остатка можно составить ещё одну полную группу.']),
    cq('10', 'Transfer', '🔴', 'd21-transfer', 'input', '🚀', ['5'],
      ["53 ta signal 8 tadan paketlanadi.", "Qoldiqni kiriting.", undefined, "8 × 6 = 48; 53 − 48 = 5.", "53 dan oshmaydigan eng katta 8 karralisini toping.", '53 : 8', "53 : 8 = 6, qoldiq 5."],
      ['53 сигнала упаковывают по 8.', 'Введи остаток.', undefined, '8 × 6 = 48; 53 − 48 = 5.', 'Найди наибольшее кратное 8, не превышающее 53.', '53 : 8', '53 : 8 = 6, остаток 5.']),
  ],
};
